### ISSUE TITLE
Error importing .tped files with genomic_converter()

### ISSUE THREAD

**Issue by IdoBar** [thierrygosselin/radiator#1]
Hi Thierry,

I'm trying to import/convert a *PLINK* `.tped` file using `genomic_converter()`, but I keep getting the same error (tried it with a few different sources).
```
GBS_data <- genomic_converter("../1A-CB478ANXX_NS_filtered_plink.tped", imputation.method = "rf")
Error in data.table::fread(input = stringi::stri_replace_all_fixed(str = data,  : 
  Column number 2 (colClasses[[1]][2]) is out of range [1,ncol=1]
```
There is a relevant `.tfam` file and I'm able to use these `.tped` files with other packages (such as *GenABEL*)
Thank you very much for developing this (and *stackr*) package!!

**Comment by thierrygosselin** [comment]
Hi Ido, I no longer use PLINK file much, but the ones I have still work in `radiator::genomic_converter`.

Could you send me your files (.tped and .tfam) or part of it to help me find the bug.

Best,
Thierry

**Comment by IdoBar** [comment]
Thanks Thierry,

The file was produced by [SnpSift's](http://snpeff.sourceforge.net/SnpSift.html#vcf2tped) `vcf2tped` and I guess the conversion is somehow unusual.
When I converted the same `vcf` file to `tped` using PLINK, it worked alright (though this time the imputation is failing, but I'll open a new issue for that).

Thanks, Ido
