### ISSUE TITLE
genomic_converter vcf to dadi errors

### ISSUE THREAD

**Issue by adamfreedman** [thierrygosselin/radiator#109]
A few years back, I used the vcf2dadi function in v. 0.0.4 to convert a stacks vcf file to dadi for ~ 65k snps without a problem. i guess that function was deprecated in favor of genomic_converter, but running it on a smaller filtered vcf of ~ 15k snps generated an error.

the cmd line:
genomic_converter(data="oneperrad_trachylepis_RAD_maxmis25pcent_maf05.recode.vcf",strata="maf05_maxmis25_taffinis_dadi_strata_forVecotone.tsv",output=c("dadi"),filename="mydadi.tsv")

where the strata file looks like this:
INDIVIDUALS     STRATA
0125ME3 ECO
0126ME3 ECO
0128ME3 ECO
0169ME3 ECO
...

The output and error:

Function call and arguments stored in: radiator_genomic_converter_args_20210104@1303.tsv
Filters parameters file generated: filters_parameters_20210104@1303.tsv

Importing data: vcf.file

Reading VCF... 

Data summary: 
    number of samples: 194
    number of markers: 14896

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0

Generating individual stats...
Error: Can't recycle `ID_SEQ` (size 2889824) to match `length` (size 14896).
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Outer names are only allowed for unnamed scalar atomic inputs 

Computation time, overall: 8 sec

Also ...potentially of use:

rlang::last_trace()
<error/vctrs_error_incompatible_size>
Can't recycle `ID_SEQ` (size 2889824) to match `length` (size 14896).
Backtrace:
     █
  1. ├─radiator::genomic_converter(...)
  2. │ └─radiator::tidy_genomic_data(...)
  3. │   └─radiator::tidy_vcf(...)
  4. │     └─radiator::read_vcf(...)
  5. │       ├─`%$%`(...)
  6. │       └─radiator::generate_id_stats(...)
  7. │         └─radiator::extract_coverage(gds, markers = FALSE)
  8. │           └─radiator::parse_gds_metadata(...)
  9. │             └─res %<>% purrr::flatten_dfc(.)
 10. ├─base::with(., info)
 11. ├─purrr::flatten_dfc(.)
 12. │ └─dplyr::bind_cols(res)
 13. │   └─vctrs::vec_cbind(!!!dots, .name_repair = .name_repair)
 14. └─vctrs::stop_incompatible_size(...)
 15.   └─vctrs:::stop_incompatible(...)
 16.     └─vctrs:::stop_vctrs(...)

**Comment by thierrygosselin** [comment]
`dadi` is not implemented as an output option for `genomic_converter`, check the [doc here](https://thierrygosselin.github.io/radiator/reference/genomic_converter.html). I might do it in the future, but it would require many arguments to be passed in `...` which is not ideal for this. 

I've lost interest in *dadi* in favour of [rmetasim](https://github.com/stranda/rmetasim)...

Try using [write_dadi](https://thierrygosselin.github.io/radiator/reference/write_dadi.html) with a tidy dataset. 
To get a tidy dataset from a VCF file you can either use [tidy_vcf](https://thierrygosselin.github.io/radiator/reference/tidy_vcf.html) or [tidy_genomic_data](https://thierrygosselin.github.io/radiator/reference/tidy_genomic_data.html).
