### ISSUE TITLE
unable to read vcf into radiator

### ISSUE THREAD

**Issue by dryak01** [thierrygosselin/radiator#112]
> test1 <- radiator::read_vcf(
>      data = "OCall208_75pctmsng.recode.vcf",
>      strata = "OCall208_85clust_75pctmsng_oneSNPmac2_20190205_radiator_strata.txt",
>      verbose = TRUE)

For me on Windows, the same input returns the error

```
Error in .DynamicClusterCall(cl, length(cl), .fun = function(.proc_idx,  : 
  One of the nodes produced an error: Can not open file 'C:\Users\kevin\Documents\Rtest\read_vcf_20190320@1141\01_import_gds\radiator_20190320@1141.gds'. The process cannot access the file because it is being used by another process.
```

I did use a genome fasta for alignment. I was wondering if incorporating that fasta into radiator operations added more information than is found in the VCF, but probably not, so ignore that.

Also, I did run more tests on long LD filtering with filter.common.markers either TRUE or FALSE, using long.ld.missing TRUE or FALSE. No combination seems to be filtering, so I'm really not sure what to do now. I think I might have gotten it to successfully filter once, but I don't remember the parameters there again (I really should be better at logging, but I've been running this dozens of times.)

_Originally posted by @kevinmneal in https://github.com/thierrygosselin/radiator/issues/44#issuecomment-474978563_

**Comment by dryak01** [comment]
I have a similar issue with radiator 1.1.9.  When I try read a vcf derived from stacks I get a similar error.
```
radiator::filter_rad("./sbra.M3_all/populations.snps.vcf",
                     strata = "sbra_strata.tsv",
                     output = c("genind", "stockr")
                     )
```

This gives the following error:

> ################################################################################
> ############################# radiator::filter_rad #############################
> ################################################################################
> Execution date@time: 20210120@1141
> Folder created: filter_rad_20210120@1141
> Function call and arguments stored in: radiator_filter_rad_args_20210120@1141.tsv
> File written: random.seed (387788)
> Filters parameters file generated: filters_parameters_20210120@1141.tsv
> 
> Reading VCF... 
> 
> Data summary: 
>     number of samples: 49
>     number of markers: 304900
> 
> Generating individual stats...
> Error: Problem with `mutate()` input `MISSING_PROP`.
> x One of the nodes produced an error: Can not open file 'D:\R_data\Sbra\sbra_denovo_all\filter_rad_20210120@1141\01_radiator\radiator_20210120@1141.gds'. The process cannot access the file because it is being used by another process.
> 
> i Input `MISSING_PROP` is `round(...)`.
> Run `rlang::last_error()` to see where the error occurred.
> 
> Computation time, overall: 41 sec
> ############################# completed filter_rad #############################
> 

If I use a genepop version of the data (which can be read by adegenet, I get a different error.

> ################################################################################
> ############################# radiator::filter_rad #############################
> ################################################################################
> Execution date@time: 20210120@1156
> Folder created: filter_rad_20210120@1156
> Function call and arguments stored in: radiator_filter_rad_args_20210120@1156.tsv
> File written: random.seed (40251)
> Filters parameters file generated: filters_parameters_20210120@1156.tsv
> 
> Unknowned arguments identified inside "...": 
>     gt
>     gt.bin
>     gt.vcf
>     gt.vcf.nuc
> 
> Read documentation, for latest changes, and modify your codes!
> 
> Synchronizing data and strata...
>     Number of strata: 4
>     Number of individuals: 49
> Calibrating REF/ALT alleles...
> Error in if (detect.gt == "GT_VCF_NUC") { : argument is of length zero
> 
> Computation time, overall: 50 sec
> ############################# completed filter_rad #############################
> 

The headers of the vcf are as follows:

##fileformat=VCFv4.2
##fileDate=20210118
##source="Stacks v2.54"
##INFO=<ID=AD,Number=R,Type=Integer,Description="Total Depth for Each Allele">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allele Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=loc_strand,Number=1,Type=Character,Description="Genomic strand the corresponding Stacks locus aligns on">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sbra_KB021	Sbra_KB023	Sbra_KB024	Sbra_KB031	Sbra_KB032	Sbra_KB034	Sbra_KB035	Sbra_KB036	Sbra_KB037	Sbra_KB038	Sbra_LS003	Sbra_LS005	Sbra_LS007	Sbra_LS008	Sbra_LS009	Sbra_LS010	Sbra_LS041	Sbra_LS042	Sbra_LS043	Sbra_LS046	Sbra_LS047	Sbra_LS048	Sbra_LS049	Sbra_LS101	Sbra_LS102	Sbra_LS106	Sbra_LS107	Sbra_LS108	Sbra_LS115	Sbra_NM116	Sbra_NM117	Sbra_NM119	Sbra_NM120	Sbra_NM121	Sbra_NM122	Sbra_NM123	Sbra_NM124	Sbra_NM125	Sbra_NM126	Sbra_NM127	Sbra_TM137	Sbra_TM138	Sbra_TM139	Sbra_TM140	Sbra_TM142	Sbra_TM143	Sbra_TM144	Sbra_TM145	Sbra_TM146
1	136	1:136	T	C	.	PASS	NS=6;AF=0.333	GT:DP:AD:GQ:GL	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	1/1:16:0,16:40:-61.95,-5.77,-0.00	./.	0/0:11:11,0:40:-0.00,-4.56,-43.08	./.	./.	0/0:20:20,0:40:-0.00,-7.27,-78.09	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:199:199,0:40:0.00,-61.14,-774.36	./.	./.	./.	./.	0/0:12:12,0:40:-0.00,-4.86,-46.97	./.	./.	./.	./.	1/1:130:0,130:40:-505.39,-40.08,0.00	./.	./.	./.	./.	./.	./.	./.	./.
1	137	1:137	G	T	.	PASS	NS=6;AF=0.167	GT:DP:AD:GQ:GL	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:16:16,0:40:-0.00,-6.18,-62.90	./.	1/1:11:0,11:40:-42.13,-4.01,-0.00	./.	./.	0/0:20:20,0:40:-0.00,-7.38,-78.46	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:199:199,0:40:0.00,-61.26,-774.73	./.	./.	./.	./.	0/0:12:12,0:40:-0.00,-4.98,-47.34	./.	./.	./.	./.	0/0:130:130,0:40:0.00,-40.49,-506.34	./.	./.	./.	./.	./.	./.	./.	./.
1	138	1:138	A	C	.	PASS	NS=6;AF=0.167	GT:DP:AD:GQ:GL	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:16:16,0:40:-0.00,-6.42,-62.76	./.	0/0:11:11,0:40:-0.00,-4.92,-43.36	./.	./.	0/0:20:20,0:40:-0.00,-7.63,-78.28	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:199:199,0:40:-0.00,-61.50,-772.94	./.	./.	./.	./.	1/1:4:0,4:27:-14.86,-2.15,-0.00	./.	./.	./.	./.	0/0:130:130,0:40:0.00,-40.74,-505.17	./.	./.	./.	./.	./.	./.	./.	./.

**Comment by fraser-combe** [comment]
I had this problem before, try adding , parallel.core = 1L)
test1<-radiator::filter_rad("./sbra.M3_all/populations.snps.vcf",
                     strata = "sbra_strata.tsv",
                     output = c("genind", "stockr"), parallel.core = 1L)

**Comment by dryak01** [comment]
Hi,

Thank you very much.  That worked right up to the end - I was able to run the whole filter_rad process interactively using the following command:

```
data.sbra.rad <- radiator::filter_rad(
  data = "./sbra.M3_all/populations.snps.vcf",
  strata = "sbra_strata.tsv",
  output = c("genind", "stockr"),
  parallel.core = 1L
)
```

However it appears to be unable to write the final output - there seems to be issues with missing fonts but I don't know which font families to replace...

My questions are the following:

1. How do I get a genind file that I can use in adgenet?
2. What are the graphics it is trying to write and what font family is it using? All the other graphics it produced during the interactive phase (pdf and png) seem fine...
3. Can I read in the final tidy dataset (radiator_data_20210202@0947.rad) so I don't have to go through the whole process again?
 

So, after going through the whole process I get:

> ############################# completed filter_hwe #############################
> 
> Preparing output files...
> File written: whitelist.markers.tsv
> File written: blacklist.markers.tsv
> File written: blacklist.id.tsv
> Writing the filtered strata: strata.filtered.tsvstrata.filtered.tsv
> 
> Generating statistics after filtering
> calculating individual stats...
> File written: individuals qc info and stats summary
> File written: individuals qc plot
> calculating markers stats...
> [==================================================] 100%, completed, 0s
> [==================================================] 100%, completed, 0s
> 
> Transferring data to genomic converter...
> Calibrating REF/ALT alleles...
> Synchronizing data and strata...
>     Number of strata: 4
>     Number of individuals: 42
> 
> Writing tidy data set:
> radiator_data_20210202@0947.rad
> 
> Data summary: 
>     number of samples: 42
>     number of markers: 10830
> 
> Computation time, overall: 2980 sec
> ############################# completed filter_rad #############################
> There were 50 or more warnings (use warnings() to see the first 50)
> > warnings()
> Warning messages:
> 1: Removed 7 row(s) containing missing values (geom_path).
> 2: Removed 14 rows containing missing values (geom_point).
> 3: Removed 7 row(s) containing missing values (geom_path).
> 4: Removed 14 rows containing missing values (geom_point).
> 5: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 6: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 7: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 8: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 9: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 10: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 11: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 12: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 13: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 14: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 15: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 16: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 17: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 18: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 19: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 20: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 21: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 22: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 23: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 24: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 25: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 26: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 27: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 28: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 29: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 30: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 31: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 32: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 33: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 34: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 35: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 36: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 37: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 38: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 39: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 40: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 41: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 42: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 43: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 44: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 45: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 46: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 47: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 48: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 49: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 50: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   font family not found in Windows font database
> 

The output file data.sbra.rad is not reconised as a genind object - I've attached the file from reading >data.sbra.rad
[data,sbra.rad_structure.txt](https://github.com/thierrygosselin/radiator/files/5909977/data.sbra.rad_structure.txt)

Thanks for your input.


===================
My session_info() is the following:
devtools::session_info()

> - Session info ---------------------------------------------------------
>  setting  value                       
>  version  R version 4.0.3 (2020-10-10)
>  os       Windows 10 x64              
>  system   x86_64, mingw32             
>  ui       RStudio                     
>  language (EN)                        
>  collate  English_South Africa.1252   
>  ctype    English_South Africa.1252   
>  tz       Africa/Johannesburg         
>  date     2021-02-02                  
> 
> - Packages -------------------------------------------------------------
>  package          * version  date       lib
>  ade4               1.7-16   2020-10-28 [1]
>  adegenet           2.1.3    2020-05-10 [1]
>  ape                5.4-1    2020-08-13 [1]
>  assertthat         0.2.1    2019-03-21 [1]
>  backports          1.2.1    2020-12-09 [1]
>  BiocGenerics       0.36.0   2020-10-27 [1]
>  BiocManager        1.30.10  2019-11-16 [1]
>  Biostrings         2.58.0   2020-10-27 [1]
>  bitops             1.0-6    2013-08-17 [1]
>  boot               1.3-26   2021-01-25 [2]
>  broom              0.7.3    2020-12-16 [1]
>  cachem             1.0.1    2021-01-21 [1]
>  callr              3.5.1    2020-10-13 [1]
>  carrier            0.1.0    2018-10-16 [1]
>  class              7.3-18   2021-01-24 [2]
>  classInt           0.4-3    2020-04-07 [1]
>  cli                2.2.0    2020-11-20 [1]
>  cluster            2.1.0    2019-06-19 [2]
>  coda               0.19-4   2020-09-30 [1]
>  codetools          0.2-18   2020-11-04 [2]
>  colorspace         2.0-0    2020-11-11 [1]
>  crayon             1.3.4    2017-09-16 [1]
>  data.table         1.13.6   2020-12-30 [1]
>  DBI                1.1.1    2021-01-15 [1]
>  deldir             0.2-9    2021-01-16 [1]
>  desc               1.2.0    2018-05-01 [1]
>  devtools           2.3.2    2020-09-18 [1]
>  digest             0.6.27   2020-10-24 [1]
>  dplyr              1.0.3    2021-01-15 [1]
>  e1071              1.7-4    2020-10-14 [1]
>  ellipsis           0.3.1    2020-05-15 [1]
>  expm               0.999-6  2021-01-13 [1]
>  fansi              0.4.2    2021-01-15 [1]
>  farver             2.0.3    2020-01-16 [1]
>  fastmap            1.1.0    2021-01-25 [1]
>  fs                 1.5.0    2020-07-31 [1]
>  fst                0.9.4    2020-08-27 [1]
>  furrr              0.2.1    2020-10-21 [1]
>  future             1.21.0   2020-12-10 [1]
>  gdata              2.18.0   2017-06-06 [1]
>  gdsfmt             1.26.1   2020-12-22 [1]
>  generics           0.1.0    2020-10-31 [1]
>  GenomeInfoDb       1.26.2   2020-12-08 [1]
>  GenomeInfoDbData   1.2.4    2021-01-15 [1]
>  GenomicRanges      1.42.0   2020-10-27 [1]
>  ggplot2            3.3.3    2020-12-30 [1]
>  globals            0.14.0   2020-11-22 [1]
>  glue               1.4.2    2020-08-27 [1]
>  gmodels            2.18.1   2018-06-25 [1]
>  gridExtra          2.3      2017-09-09 [1]
>  gtable             0.3.0    2019-03-25 [1]
>  gtools             3.8.2    2020-03-31 [1]
>  HardyWeinberg      1.7.1    2021-01-04 [1]
>  hms                1.0.0    2021-01-13 [1]
>  htmltools          0.5.1.1  2021-01-22 [1]
>  httpuv             1.5.5    2021-01-13 [1]
>  igraph             1.2.6    2020-10-06 [1]
>  IRanges            2.24.1   2020-12-12 [1]
>  KernSmooth         2.23-18  2020-10-29 [2]
>  labeling           0.4.2    2020-10-20 [1]
>  later              1.1.0.1  2020-06-05 [1]
>  lattice            0.20-41  2020-04-02 [2]
>  LearnBayes         2.15.1   2018-03-18 [1]
>  lifecycle          0.2.0    2020-03-06 [1]
>  listenv            0.8.0    2019-12-05 [1]
>  magrittr           2.0.1    2020-11-17 [1]
>  MASS               7.3-53   2020-09-09 [2]
>  Matrix             1.3-2    2021-01-06 [2]
>  memoise            2.0.0    2021-01-26 [1]
>  mgcv               1.8-33   2020-08-27 [2]
>  mice               3.13.0   2021-01-27 [1]
>  mime               0.9      2020-02-04 [1]
>  munsell            0.5.0    2018-06-12 [1]
>  nlme               3.1-151  2020-12-10 [2]
>  parallelly         1.23.0   2021-01-04 [1]
>  permute            0.9-5    2019-03-12 [1]
>  pillar             1.4.7    2020-11-20 [1]
>  pkgbuild           1.2.0    2020-12-15 [1]
>  pkgconfig          2.0.3    2019-09-22 [1]
>  pkgload            1.1.0    2020-05-29 [1]
>  plyr               1.8.6    2020-03-03 [1]
>  prettyunits        1.1.1    2020-01-24 [1]
>  processx           3.4.5    2020-11-30 [1]
>  progress           1.2.2    2019-05-16 [1]
>  progressr          0.7.0    2020-12-11 [1]
>  promises           1.1.1    2020-06-09 [1]
>  ps                 1.5.0    2020-12-05 [1]
>  purrr            * 0.3.4    2020-04-17 [1]
>  R6                 2.5.0    2020-10-28 [1]
>  radiator         * 1.1.9    2021-01-27 [1]
>  raster             3.4-5    2020-11-14 [1]
>  Rcpp               1.0.6    2021-01-15 [1]
>  RCurl              1.98-1.2 2020-04-18 [1]
>  readr              1.4.0    2020-10-05 [1]
>  remotes            2.2.0    2020-07-21 [1]
>  reshape2           1.4.4    2020-04-09 [1]
>  rlang              0.4.10   2020-12-30 [1]
>  rprojroot          2.0.2    2020-11-15 [1]
>  Rsolnp             1.16     2015-12-28 [1]
>  rstudioapi         0.13     2020-11-12 [1]
>  S4Vectors          0.28.1   2020-12-09 [1]
>  scales             1.1.1    2020-05-11 [1]
>  SeqArray           1.30.0   2020-10-28 [1]
>  seqinr             4.2-5    2020-12-17 [1]
>  sessioninfo        1.1.1    2018-11-05 [1]
>  sf                 0.9-7    2021-01-06 [1]
>  shiny              1.6.0    2021-01-25 [1]
>  SNPRelate          1.24.0   2020-10-28 [1]
>  sp                 1.4-5    2021-01-10 [1]
>  spData             0.3.8    2020-07-03 [1]
>  spdep              1.1-5    2020-06-29 [1]
>  stringi            1.5.3    2020-09-09 [1]
>  stringr            1.4.0    2019-02-10 [1]
>  testthat           3.0.1    2020-12-17 [1]
>  tibble             3.0.5    2021-01-15 [1]
>  tidyr              1.1.2    2020-08-27 [1]
>  tidyselect         1.1.0    2020-05-11 [1]
>  truncnorm          1.0-8    2018-02-27 [1]
>  units              0.6-7    2020-06-13 [1]
>  UpSetR             1.4.0    2019-05-22 [1]
>  usethis            2.0.0    2020-12-10 [1]
>  vctrs              0.3.6    2020-12-17 [1]
>  vegan              2.5-7    2020-11-28 [1]
>  viridisLite        0.3.0    2018-02-01 [1]
>  withr              2.4.1    2021-01-26 [1]
>  xtable             1.8-4    2019-04-21 [1]
>  XVector            0.30.0   2020-10-28 [1]
>  zlibbioc           1.36.0   2020-10-28 [1]

**Comment by dryak01** [comment]
Hi,

Following on from the issue above. I was able to read the output data from the final .rad file after renaming it and moving it into the working directory.  However I am not able to use genomic_converter to write any other kind of output. It appears as if there is a column (GT) missing in the rad file - there is GT_BIN...

```
radiator::genomic_converter(data = data.sbra.rad.1, 
                            output = c("genind", "genepop", "structure"),
                            parallel.core = 1L)
```
I get the following error:

> ################################################################################
> ######################### radiator::genomic_converter ##########################
> ################################################################################
> Execution date@time: 20210202@1124
> Folder created: -14_radiator_genomic_converter_20210202@1124
> Function call and arguments stored in: radiator_genomic_converter_args_20210202@1124.tsv
> Filters parameters file generated: filters_parameters_20210202@1124.tsv
> 
> Importing data: tbl_df
> 
> Writing tidy data set:
> radiator_data_20210202@1124.rad
> 
> Preparing data for output
> 
> Data is bi-allelic
> Calibrating REF/ALT alleles...
> Generating genepop file
> Calibrating REF/ALT alleles...
> Error: Can't subset columns that don't exist.
> x Column `GT` doesn't exist.
> Run `rlang::last_error()` to see where the error occurred.
> 
> Computation time, overall: 3 sec
> ######################### completed genomic_converter ##########################
> > rlang::last_error()
> <error/vctrs_error_subscript_oob>
> Can't subset columns that don't exist.
> x Column `GT` doesn't exist.
> Backtrace:
>   1. radiator::genomic_converter(...)
>   5. dplyr:::select.data.frame(., POP_ID, INDIVIDUALS, MARKERS, GT)
>   6. tidyselect::eval_select(expr(c(...)), .data)
>   7. tidyselect:::eval_select_impl(...)
>  15. tidyselect:::vars_select_eval(...)
>  16. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
>  17. tidyselect:::eval_c(expr, data_mask, context_mask)
>  18. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
>  19. tidyselect:::walk_data_tree(new, data_mask, context_mask)
>  20. tidyselect:::as_indices_sel_impl(...)
>  21. tidyselect:::as_indices_impl(x, vars, strict = strict)
>  22. tidyselect:::chr_as_locations(x, vars)
>  23. vctrs::vec_as_location(x, n = length(vars), names = vars)
>  25. vctrs:::stop_subscript_oob(...)
>  26. vctrs:::stop_subscript(...)
> Run `rlang::last_trace()` to see the full context.




The input file is as follows:

> > data.sbra.rad.1
>  \# A tibble: 454,860 x 14
>    POP_ID INDIVIDUALS ID_SEQ M_SEQ GT_BIN VARIANT_ID CHROM LOCUS POS  
>    <fct>  <chr>        <int> <int>  <int>      <int> <chr> <chr> <chr>
>  1 KB     Sbra-KB021       1     7      0          7 1     2     93   
>  2 KB     Sbra-KB023       2     7     NA          7 1     2     93   
>  3 KB     Sbra-KB024       3     7     NA          7 1     2     93   
>  4 KB     Sbra-KB031       4     7      0          7 1     2     93   
>  5 KB     Sbra-KB032       5     7     NA          7 1     2     93   
>  6 KB     Sbra-KB034       6     7      1          7 1     2     93   
>  7 KB     Sbra-KB035       7     7      0          7 1     2     93   
>  8 KB     Sbra-KB036       8     7      1          7 1     2     93   
>  9 KB     Sbra-KB037       9     7      0          7 1     2     93   
> 10 LS     Sbra-LS003      11     7      0          7 1     2     93   
> \# ... with 454,850 more rows, and 5 more variables: COL <dbl>,
> \#   MARKERS <chr>, REF <chr>, ALT <chr>, STRATA_SEQ <int
> 

Thanks,
Dave

**Comment by fraser-combe** [comment]
I have been having problems reading in data with the updated package too. Even  on data I have been able to previously read in.

If you want to quickly get your data into adegenet without cleaning up through radiator to do  quick check you can use vcfR package
vcf <- read.vcfR("populations.snpss.vcf")
pop_map <- read.table("sbra_strata.tsv", header=TRUE, stringsAsFactors = TRUE)
genind <- vcfR2genind(vcf)
genind@pop <- pop_map$STRATA

you should be able to read in the .rad file using the read.rad function that reads in a radiator data frame

**Comment by thierrygosselin** [comment]
should work now

**Comment by GiuliaT94** [comment]
Hello, I am having the same issue. 
I have updated the package with radiator_pkg_install() and tried again both from the vcf file and from the genind object created with adegenet, but I still get the same error message. Is there a way around it? 

Thanks

Giulia
