### ISSUE TITLE
Running Bayescan through Radiator error

### ISSUE THREAD

**Issue by fraser-combe** [thierrygosselin/radiator#116]
Trying to run Bayescan through Radiator on Windows Laptop however, I keep getting the following error.  I have tried multiple computers but the same problem.  To check we are using BayeScan2.0_win32bits_cmd_line.exe for running through radiator, I did try the GUI version by chance but same output

I updated my Radiator to 1.1.9 with all packages successfully loaded

I ran
 run_bayescan(
+   data="radiator_bayescan_20210119@1853.txt", n = 5000,  thin = 10,
nbp = 20,  pilot = 5000,  burn = 50000, pr_odds=10, subsample = NULL,
iteration.subsample = 1, parallel.core = parallel::detectCores() - 1,
bayescan.path = "C:/Users/frasc/Downloads/BayeScan2.01/bayescan_distributed_2.01/binaries/BayeScan2.0_win32bits_cmd_line.exe")

#######################################################################
#######################################################################

Folder created: 
radiator_bayescan_20210129@1210
For progress, look in the log file: radiator_bayescan_20210129@1210.log
Copying input BayeScan file in folder
Importing BayeScan results
Error in if (length(x) > 1 || grepl("\n", x)) { : 
  missing value where TRUE/FALSE needed

**Comment by thierrygosselin** [comment]
I cannot reproduce
If it's still relevant to you, do you mind sharing the necessary file by email
re-open if it's still not working with latest version
