### ISSUE TITLE
problem converting tidy dart to vcf or structure or any other format, 

### ISSUE THREAD

**Issue by Farhad63** [thierrygosselin/radiator#117]
Dear Thierry

I am trying to convert tidy filtered DArTseq data into vcf (to use easy sfs to make fastsimcoal input), I import, tidy and filter the data but when I want to write vcf it gives me the below error. 
I have also tried writing other version (e.g; structure, dadi, etc) but still I get the  error. 

`Error in readLines(con = data, n = 1L) : 'con' is not a connection`

I do appreciate your comment in advance.

Many thanks 
Farhad

[DArT_error_radiator.txt](https://github.com/thierrygosselin/radiator/files/5908497/DArT_error_radiator.txt)

**Comment by thierrygosselin** [comment]
try with latest release please if still relevant
and follow guidelines to report bug, I cannot reproduce
