### ISSUE TITLE
Problem with reading in / converting TASSEL-generated .vcf

### ISSUE THREAD

**Issue by GePetersen** [thierrygosselin/radiator#121]
I was trying to convert from a TASSEL-generated vcf to a genepop file (which I have done in the past with no issues for this exact file), but got an error related to not being able to access a file because it was in use by another process. 

Command: radiator::tidy_genomic_data("tassel_pilot.vcf", filename = "pilot.vcf")

output:
################################################################################
################################################################################
Execution date@time: 20210224@1234
Folder created: -28162_radiator_tidy_genomic_20210224@1234
Function call and arguments stored in: radiator_tidy_genomic_data_args_20210224@1234.tsv
Importing and tidying the VCF...
Execution date@time: 20210224@1234

Reading VCF... 

Data summary: 
    number of samples: 79
    number of markers: 108405

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 215 / 60888
Filter common markers: only 1 strata, returning data

Generating individual stats...
Error: Problem with `mutate()` input `MISSING_PROP`.
x One of the nodes produced an error: Can not open file 'C:\Users\GPetersen.ABACUSBIOLTD\Documents\-28162_radiator_tidy_genomic_20210224@1234\radiator_20210224@1234.gds'. The process cannot access the file because it is being used by another process.

i Input `MISSING_PROP` is `round(...)`.
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 31 sec
############################## completed tidy_vcf ##############################

Doing the error tracing resulted in the following output:

> rlang::last_error()
<error/dplyr:::mutate_error>
Problem with `mutate()` input `MISSING_PROP`.
x One of the nodes produced an error: Can not open file 'C:\Users\GPetersen.ABACUSBIOLTD\Documents\-28162_radiator_tidy_genomic_20210224@1234\radiator_20210224@1234.gds'. The process cannot access the file because it is being used by another process.

i Input `MISSING_PROP` is `round(...)`.
Backtrace:
  1. radiator::tidy_genomic_data("tassel_pilot.vcf", filename = "pilot.vcf")
 18. base::.handleSimpleError(...)
 19. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.

> rlang::last_trace()
<error/dplyr:::mutate_error>
Problem with `mutate()` input `MISSING_PROP`.
x One of the nodes produced an error: Can not open file 'C:\Users\GPetersen.ABACUSBIOLTD\Documents\-28162_radiator_tidy_genomic_20210224@1234\radiator_20210224@1234.gds'. The process cannot access the file because it is being used by another process.

i Input `MISSING_PROP` is `round(...)`.
Backtrace:
     x
  1. +-radiator::tidy_genomic_data("tassel_pilot.vcf", filename = "pilot.vcf")
  2. | \-radiator::tidy_vcf(...)
  3. |   \-radiator::read_vcf(...)
  4. |     +-`%$%`(...)
  5. |     \-radiator::generate_id_stats(...)
  6. |       \-`%<>%`(...)
  7. +-base::with(., info)
  8. +-dplyr::mutate(...)
  9. +-dplyr:::mutate.data.frame(...)
 10. | \-dplyr:::mutate_cols(.data, ...)
 11. |   +-base::withCallingHandlers(...)
 12. |   \-mask$eval_all_mutate(quo)
 13. +-SeqArray::seqMissing(gdsfile = gds, per.variant = FALSE, parallel = parallel.core)
 14. | \-SeqArray::seqParallel(...)
 15. |   \-SeqArray::seqParallel(...)
 16. |     \-SeqArray:::.DynamicClusterCall(...)
 17. |       \-base::stop("One of the nodes produced an error: ", as.character(dv))
 18. \-base::.handleSimpleError(...)
 19.   \-dplyr:::h(simpleError(msg, call))
<error/simpleError>
One of the nodes produced an error: Can not open file 'C:\Users\GPetersen.ABACUSBIOLTD\Documents\-28162_radiator_tidy_genomic_20210224@1234\radiator_20210224@1234.gds'. The process cannot access the file because it is being used by another process.

Computation time, overall: 35 sec
######################### completed tidy_genomic_data ##########################

SeqArray is version 1.30.0 (I figured that might have something to do with it, since it looks to be what tries to interact with that file in question last...?

**Comment by thierrygosselin** [comment]
try with latest release if still relevant
