### ISSUE TITLE
Filters bug 

### ISSUE THREAD

**Issue by laiajulianamu** [thierrygosselin/radiator#126]
Hi 
I have the follow bug. Could you help me please. 

################################################################################
################################################################################
Execution date@time: 20210427@1008
Function call and arguments stored in: radiator_filter_individuals_args_20210427@1008.tsv
Interactive mode: on

Step 1. Visualization
Step 2. Missingness
Step 3. Heterozygosity
Step 4. Coverage (if available)

Step 1. Visualization of samples QC

Error: Problem with `filter()` input `..1`.
x object 'MARKERS' not found
i Input `..1` is `MARKERS %in% markers`.
Run `rlang::last_error()` to see where the error occurred.
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Computation time, overall: 2 sec
######################### completed filter_individuals #########################

Computation time, overall: 129 sec

**Comment by pfeutry** [comment]
Hi there, have you been able to resolve this issue? I have the exact same one since I updated my OS and R as well as all the packages. Same code was working fine before then.

**Comment by laiajulianamu** [comment]
Hi, thanks for your comment! I  still have the error, I updated but anything changed.

**Comment by thierrygosselin** [comment]
should work with latest release
