### ISSUE TITLE
Errors with creating tibbles when using genomic_converter

### ISSUE THREAD

**Issue by andemexoax** [thierrygosselin/radiator#127]
In attempting to convert a vcf file (created by freebayes) to genepop file the following error pops up. Using RStudio on windows 10.  It looks like everything is fine up until it says 
```
Genotypes formats generated with 1052 SNPs: 
    GT_BIN (the dosage of ALT allele: 0, 1, 2 NA): TRUE
    GT_VCF (the genotype coding VCFs: 0/0, 0/1, 1/1, ./.): TRUE
    GT_VCF_NUC (the genotype coding in VCFs, but with nucleotides: A/C, ./.): TRUE
    GT (the genotype coding 'a la genepop': 001002, 001001, 000000): TRUE
Error: All columns in a tibble must be vectors.
x Column `GQ` is a `SeqVarDataList` object.
```
The same issue happens with tidy_vcf. After I deleted the GQ line in the header(there was no GQ info in the rest of the file), the following error popped up when using tidy_vcf, 
```
Parsing and tidying genotypes metadata: GL, DP
DP column: cleaning and renaming to READ_DEPTH
GL column: cleaning Genotype Likelihood column
Error: Can't recycle `ID_SEQ` (size 41028) to match `GL_HOM_REF` (size 44889).
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In if (gl > 0) { :
  the condition has length > 1 and only the first element will be used
```
Here is the traceback
```
> rlang::last_trace()
<error/vctrs_error_incompatible_size>
Can't recycle `ID_SEQ` (size 41028) to match `GL_HOM_REF` (size 44889).
Backtrace:
    x
 1. +-radiator::tidy_vcf(...)
 2. | \-radiator::parse_gds_metadata(...)
 3. |   \-res %<>% purrr::flatten_dfc(.)
 4. +-purrr::flatten_dfc(.)
 5. | \-dplyr::bind_cols(res)
 6. |   \-vctrs::vec_cbind(!!!dots, .name_repair = .name_repair)
 7. \-vctrs::stop_incompatible_size(...)
 8.   \-vctrs:::stop_incompatible(...)
 9.     \-vctrs:::stop_vctrs(...)
```

**Comment by thierrygosselin** [comment]
should work with latest release

**Comment by siberianhigh** [comment]
Hi, there is still the same issue, with a VCF file from freebayes as well. 

> devtools::package_info(pkgs = "radiator")
 package          * version     date (UTC) lib source
 backports          1.5.0       2024-05-23 [1] CRAN (R 4.4.0)
 BiocGenerics       0.48.1      2023-11-01 [1] Bioconductor
 Biostrings         2.70.3      2024-03-13 [1] Bioconductor 3.18 (R 4.4.2)
 bit                4.5.0.1     2024-12-03 [1] CRAN (R 4.4.2)
 bit64              4.5.2       2024-09-22 [1] CRAN (R 4.4.2)
 bitops             1.0-9       2024-10-03 [1] CRAN (R 4.4.1)
 boot               1.3-31      2024-08-28 [2] CRAN (R 4.4.2)
 broom              1.0.7       2024-09-26 [1] CRAN (R 4.4.2)
 carrier            0.1.1       2023-04-28 [1] CRAN (R 4.4.2)
 cli                3.6.3       2024-06-21 [1] CRAN (R 4.4.2)
 clipr              0.8.0       2022-02-22 [1] CRAN (R 4.4.2)
 codetools          0.2-20      2024-03-31 [2] CRAN (R 4.4.2)
 colorspace         2.1-1       2024-07-26 [1] CRAN (R 4.4.2)
 cpp11              0.5.1       2024-12-04 [1] CRAN (R 4.4.2)
 crayon             1.5.3       2024-06-20 [1] CRAN (R 4.4.2)
 data.table         1.16.4      2024-12-06 [1] CRAN (R 4.4.2)
 digest             0.6.37      2024-08-19 [1] CRAN (R 4.4.2)
 dplyr              1.1.4       2023-11-17 [1] CRAN (R 4.4.2)
 fansi              1.0.6       2023-12-08 [1] CRAN (R 4.4.2)
 farver             2.1.2       2024-05-13 [1] CRAN (R 4.4.2)
 forcats            1.0.0       2023-01-29 [1] CRAN (R 4.4.2)
 foreach            1.5.2       2022-02-02 [1] CRAN (R 4.4.2)
 fst                0.9.8       2022-02-08 [1] CRAN (R 4.4.2)
 fstcore            0.9.18      2023-12-02 [1] CRAN (R 4.4.2)
 furrr              0.3.1       2022-08-15 [1] CRAN (R 4.4.2)
 future             1.34.0      2024-07-29 [1] CRAN (R 4.4.2)
 gdsfmt             1.38.0      2023-10-24 [1] Bioconductor
 generics           0.1.3       2022-07-05 [1] CRAN (R 4.4.2)
 GenomeInfoDb       1.38.8      2024-03-15 [1] Bioconductor 3.18 (R 4.4.2)
 GenomeInfoDbData   1.2.11      2024-12-17 [1] Bioconductor
 GenomicRanges      1.54.1      2023-10-29 [1] Bioconductor
 ggplot2            3.5.1       2024-04-23 [1] CRAN (R 4.4.2)
 glmnet             4.1-8       2023-08-22 [1] CRAN (R 4.4.2)
 globals            0.16.3      2024-03-08 [1] CRAN (R 4.4.0)
 glue               1.8.0       2024-09-30 [1] CRAN (R 4.4.2)
 gridExtra          2.3         2017-09-09 [1] CRAN (R 4.4.2)
 gtable             0.3.6       2024-10-25 [1] CRAN (R 4.4.2)
 HardyWeinberg      1.7.8       2024-04-06 [1] CRAN (R 4.4.2)
 haven              2.5.4       2023-11-30 [1] CRAN (R 4.4.2)
 hms                1.1.3       2023-03-21 [1] CRAN (R 4.4.2)
 IRanges            2.36.0      2023-10-24 [1] Bioconductor
 isoband            0.2.7       2022-12-20 [1] CRAN (R 4.4.2)
 iterators          1.0.14      2022-02-05 [1] CRAN (R 4.4.2)
 jomo               2.7-6       2023-04-15 [1] CRAN (R 4.4.2)
 labeling           0.4.3       2023-08-29 [1] CRAN (R 4.4.0)
 lattice            0.22-6      2024-03-20 [2] CRAN (R 4.4.2)
 lifecycle          1.0.4       2023-11-07 [1] CRAN (R 4.4.2)
 listenv            0.9.1       2024-01-29 [1] CRAN (R 4.4.2)
 lme4               1.1-35.5    2024-07-03 [1] CRAN (R 4.4.2)
 lobstr             1.1.2       2022-06-22 [1] CRAN (R 4.4.2)
 magrittr           2.0.3       2022-03-30 [1] CRAN (R 4.4.2)
 MASS               7.3-61      2024-06-13 [2] CRAN (R 4.4.2)
 Matrix             1.7-1       2024-10-18 [2] CRAN (R 4.4.2)
 mgcv               1.9-1       2023-12-21 [2] CRAN (R 4.4.2)
 mice               3.17.0      2024-11-27 [1] CRAN (R 4.4.2)
 minqa              1.2.8       2024-08-17 [1] CRAN (R 4.4.2)
 mitml              0.4-5       2023-03-08 [1] CRAN (R 4.4.2)
 munsell            0.5.1       2024-04-01 [1] CRAN (R 4.4.2)
 nlme               3.1-166     2024-08-14 [2] CRAN (R 4.4.2)
 nloptr             2.1.1       2024-06-25 [1] CRAN (R 4.4.2)
 nnet               7.3-19      2023-05-03 [2] CRAN (R 4.4.2)
 numDeriv           2016.8-1.1  2019-06-06 [1] CRAN (R 4.4.0)
 ordinal            2023.12-4.1 2024-08-19 [1] CRAN (R 4.4.2)
 pan                1.9         2023-08-21 [1] CRAN (R 4.4.2)
 parallelly         1.40.1      2024-12-04 [1] CRAN (R 4.4.2)
 pillar             1.9.0       2023-03-22 [1] CRAN (R 4.4.2)
 pkgconfig          2.0.3       2019-09-22 [1] CRAN (R 4.4.2)
 plyr               1.8.9       2023-10-02 [1] CRAN (R 4.4.2)
 prettyunits        1.2.0       2023-09-24 [1] CRAN (R 4.4.2)
 progress           1.2.3       2023-12-06 [1] CRAN (R 4.4.2)
 purrr              1.0.2       2023-08-10 [1] CRAN (R 4.4.2)
 R6                 2.5.1       2021-08-19 [1] CRAN (R 4.4.2)
 radiator         * 1.3.5       2024-12-17 [1] Github (thierrygosselin/radiator@625193a)
 RColorBrewer       1.1-3       2022-04-03 [1] CRAN (R 4.4.0)
 Rcpp               1.0.13-1    2024-11-02 [1] CRAN (R 4.4.2)
 RcppEigen          0.3.4.0.2   2024-08-24 [1] CRAN (R 4.4.2)
 RCurl              1.98-1.16   2024-07-11 [1] CRAN (R 4.4.1)
 readr              2.1.5       2024-01-10 [1] CRAN (R 4.4.2)
 rlang              1.1.4       2024-06-04 [1] CRAN (R 4.4.2)
 rpart              4.1.23      2023-12-05 [2] CRAN (R 4.4.2)
 Rsolnp             1.16        2015-12-28 [1] CRAN (R 4.4.2)
 S4Vectors          0.40.2      2023-11-23 [1] Bioconductor 3.18 (R 4.4.2)
 scales             1.3.0       2023-11-28 [1] CRAN (R 4.4.2)
 SeqArray           1.42.4      2024-04-03 [1] Bioconductor 3.18 (R 4.4.2)
 shape              1.4.6.1     2024-02-23 [1] CRAN (R 4.4.0)
 stringi            1.8.4       2024-05-06 [1] CRAN (R 4.4.0)
 stringr            1.5.1       2023-11-14 [1] CRAN (R 4.4.2)
 survival           3.7-0       2024-06-05 [2] CRAN (R 4.4.2)
 tibble             3.2.1       2023-03-20 [1] CRAN (R 4.4.2)
 tidyr              1.3.1       2024-01-24 [1] CRAN (R 4.4.2)
 tidyselect         1.2.1       2024-03-11 [1] CRAN (R 4.4.2)
 truncnorm          1.0-9       2023-03-20 [1] CRAN (R 4.4.2)
 tzdb               0.4.0       2023-05-12 [1] CRAN (R 4.4.2)
 ucminf             1.2.2       2024-06-24 [1] CRAN (R 4.4.1)
 UpSetR             1.4.0       2019-05-22 [1] CRAN (R 4.4.2)
 utf8               1.2.4       2023-10-22 [1] CRAN (R 4.4.2)
 vctrs              0.6.5       2023-12-01 [1] CRAN (R 4.4.2)
 viridisLite        0.4.2       2023-05-02 [1] CRAN (R 4.4.2)
 vroom              1.6.5       2023-12-05 [1] CRAN (R 4.4.2)
 withr              3.0.2       2024-10-28 [1] CRAN (R 4.4.2)
 XVector            0.42.0      2023-10-24 [1] Bioconductor
 zlibbioc           1.48.2      2024-03-13 [1] Bioconductor 3.18 (R 4.4.2)
