### ISSUE TITLE
File conversion errors

### ISSUE THREAD

**Issue by kwojtusik** [thierrygosselin/radiator#128]
Hello,

There seem to be some bugs with the newest version when it comes to file conversions. I can convert my vcf to a tidy genomic file with no problems, but when I try to convert that into Rubias format i get the following error:

`Error in data.table::melt.data.table(data = ., id.vars = cols, measure.vars = measure_vars,  : 
  One or more values in 'id.vars' is invalid.`

Here is the traceback if it helps:

`22: data.table::melt.data.table(data = ., id.vars = cols, measure.vars = measure_vars, 
        variable.name = names_to, value.name = values_to, variable.factor = variable_factor)
21: tibble::as_tibble(.)
20: x %<>% data.table::as.data.table(., keep.rownames = keep_rownames) %>% 
        data.table::melt.data.table(data = ., id.vars = cols, measure.vars = measure_vars, 
            variable.name = names_to, value.name = values_to, variable.factor = variable_factor) %>% 
        tibble::as_tibble(.)
19: radiator::rad_long(x = ., cols = exclude, names_to = "ALLELES_GROUP", 
        values_to = "ALLELES", variable_factor = FALSE)
18: x %<>% radiator::rad_long(x = ., cols = exclude, names_to = "ALLELES_GROUP", 
        values_to = "ALLELES", variable_factor = FALSE)
17: FUN(X[[i]], ...)
16: lapply(X = X, FUN = FUN, ...)
15: parallel::mclapply(X = ., FUN = .f, ..., mc.cores = parallel.core)
14: purrr::flatten_dfr(.)
13: .x %<>% parallel::mclapply(X = ., FUN = .f, ..., mc.cores = parallel.core) %>% 
        purrr::flatten_dfr(.)
12: radiator_future(.x = ., .f = separate_genotype, flat.future = "dfr", 
        split.vec = TRUE, split.with = NULL, split.chunks = split.chunks, 
        parallel.core = split.chunks, forking = TRUE, gt = gt, alleles.naming = alleles.naming, 
        remove = remove, filter.missing = filter.missing, gather = gather, 
        haplotypes = haplotypes, exclude = exclude)
11: x %<>% radiator_future(.x = ., .f = separate_genotype, flat.future = "dfr", 
        split.vec = TRUE, split.with = NULL, split.chunks = split.chunks, 
        parallel.core = split.chunks, forking = TRUE, gt = gt, alleles.naming = alleles.naming, 
        remove = remove, filter.missing = filter.missing, gather = gather, 
        haplotypes = haplotypes, exclude = exclude)
10: separate_gt(x = ., gt = gt.format, gather = TRUE, exclude = c("MARKERS", 
        "POP_ID", "INDIVIDUALS"), remove = TRUE, split.chunks = split.chunks)
9: dplyr::mutate(., MARKERS_ALLELES = stringi::stri_join(MARKERS, 
       ALLELES_GROUP, sep = "."), MARKERS = NULL, ALLELES_GROUP = NULL)
8: data.table::as.data.table(.)
7: is.data.table(data)
6: data.table::dcast.data.table(data = ., formula = formula, value.var = values_from, 
       sep = sep, fill = values_fill)
5: tibble::as_tibble(.)
4: x %>% data.table::as.data.table(.) %>% data.table::dcast.data.table(data = ., 
       formula = formula, value.var = values_from, sep = sep, fill = values_fill) %>% 
       tibble::as_tibble(.)
3: rad_wide(x = ., formula = "POP_ID + INDIVIDUALS ~ MARKERS_ALLELES", 
       values_from = "ALLELES")
2: data %<>% dplyr::select(tidyselect::any_of(want)) %>% separate_gt(x = ., 
       gt = gt.format, gather = TRUE, exclude = c("MARKERS", "POP_ID", 
           "INDIVIDUALS"), remove = TRUE, split.chunks = split.chunks) %>% 
       dplyr::mutate(MARKERS_ALLELES = stringi::stri_join(MARKERS, 
           ALLELES_GROUP, sep = "."), MARKERS = NULL, ALLELES_GROUP = NULL) %>% 
       {
           if (gt.format == "GT") 
               dplyr::mutate(.data = ., ALLELES = replace(x = ALLELES, 
                   which(ALLELES == "000"), NA))
           else .
       } %>% rad_wide(x = ., formula = "POP_ID + INDIVIDUALS ~ MARKERS_ALLELES", 
       values_from = "ALLELES")
1: write_rubias(Bobo_rad, strata = Bobo_strata, filename = NULL)
`

I am not really sure what is happening since all this worked before I updated to the newest version of radiator. Here is the code I ran
`bobo_rubias <- write_rubias(Bobo_rad, strata = Bobo_strata, filename = NULL)`

**Comment by thierrygosselin** [comment]
should work now
