### ISSUE TITLE
Error: Problem with `mutate()` column `ALLELE_REF_DEPTH"

### ISSUE THREAD

**Issue by aabpaola** [thierrygosselin/radiator#129]
I cannot help you if I cannot reproduce the problem.
Consequently, when reporting an issue, make sure to include:

**Describe the bug**

**To Reproduce**
Include the steps to reproduce the behavior:
* the exact command (function, arguments, values) used
* the complete error message you're getting
* the output of `devtools::session_info()`
* complete data required to reproduce the problem, a subset of it. The data remains confidential.

**Screenshots**

**Comment by aabpaola** [comment]
Hi, I have an issue with radiator. When I try read a vcf  I get an following error.


BLTteste <- genomic_converter(data = "BLT2021_filtered_within_ld.vcf", strata = NULL,
                Execution date@time: 20210519@1646
Folder created: 09_radiator_genomic_converter_20210519@1646
Function call and arguments stored in: radiator_genomic_converter_args_20210519@1646.tsv
Filters parameters file generated: filters_parameters_20210519@1646.tsv

Importing data: vcf.file

Reading VCF... 

Data summary: 
    number of samples: 49
    number of markers: 2597

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0
Filter common markers: only 1 strata, returning data

Generating individual stats...
Generating markers stats...
[==================================================] 100%, completed, 0s
[==================================================] 100%, completed, 1s

Number of chromosome/contig/scaffold: 1
Number of locus: 2597
Number of markers: 2597
Number of strata: 1
Number of individuals: 49

Number of ind/strata:
1pop = 49

Number of duplicate id: 0
radiator Genomic Data Structure (GDS) file: radiator_20210519@1646.gds

Genotypes formats generated with 2597 SNPs: 
    GT_BIN (the dosage of ALT allele: 0, 1, 2 NA): TRUE
    GT_VCF (the genotype coding VCFs: 0/0, 0/1, 1/1, ./.): TRUE
    GT_VCF_NUC (the genotype coding in VCFs, but with nucleotides: A/C, ./.): TRUE
    GT (the genotype coding 'a la genepop': 001002, 001001, 000000): TRUE
Error: Problem with `mutate()` column `ALLELE_REF_DEPTH`.
i `ALLELE_REF_DEPTH = dplyr::case_when(...)`.
x objeto 'REF' no encontrado
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 29 sec

Computation time, overall: 30 sec             output = c("bayescan"), filename="BLTteste.geste",parallel.core = 1L)

###I am not getting the output .geno file
Could someone help me to solve this problem?

**Comment by thierrygosselin** [comment]
try again with latest issue if it's still of interest
