### ISSUE TITLE
R crashes when attempting to import VCF file from Stacks2

### ISSUE THREAD

**Issue by IdoBar** [thierrygosselin/radiator#13]
Hi Thierry,

I'm trying to import a `.vcf` file produced by `gstacks` command of Stacks2.
Variants were called from mapped BAM files, not _de novo_.

Initially I had this error:
```
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'

```
This is caused by the fact that in the current Stacks2 VCF output, the ID is left blank `.`, so `tidy_vcf()` fails at this command:
```
# Since stacks v.1.44 ID as LOCUS + COL (from sumstats) the position of the SNP on the locus.
  # Choose the first 100 markers to scan
  detect.snp.col <- sample(x = unique(input$LOCUS), size = 100, replace = FALSE) %>%
    stringi::stri_detect_fixed(str = ., pattern = "_") %>%
    unique 
```

In order to circumnavigate this, I tried to change the ID column (imported as LOCUS) to be as mentioned in `tidy_vcf()` (CHROM_POS), or just POS, but then it completely crashes without giving any message.

Any ideas?

Thanks, Ido

**Comment by IdoBar** [comment]
Hi Thierry,

I realised that it was my bad regarding the total crash (when changing the ID's in the file I accidentally changed all the separators to SPACE instead of TAB.

Nevertheless, I still think that the function should be modified to better accommodate cases where the ID is not provided. The solution implemented (changing the ID into POS) doesn't guarantee producing more than a 100 unique values for `sample()` to work.
I suggest either combining CHROM_POS for ID, or making sure that `sample()` doesn't exceeds the length of unique positions:
```
# Choose the first 100 (or less) markers to scan
  sample_size <- ifelse(length(unique(input$LOCUS))>100, 100, length(unique(input$LOCUS)))
  detect.snp.col <- sample(x = unique(input$LOCUS), size = sample_size , replace = FALSE) %>%
    stringi::stri_detect_fixed(str = ., pattern = "_") %>%
    unique 
```

Cheers, Ido

**Comment by thierrygosselin** [comment]
Hi Ido, I’ll have a look at this later today or early tomorrow.

I have used the latest beta release yet
Thierry

**Comment by thierrygosselin** [comment]
Hi Ido, sorry for the long delay in getting back at this.

**stacks:** 
Version 2.0Beta7c integrates back the ID using both locus and col info.


**What to do when the ID as NA or `.`**

Currently it puts `POS` but the function really works with markers info that will be generated by combining `CHROM` + `ID` + `POS` . Do you think it's really necessary to duplicate CHROM_POS twice? It's really just to fill the ID. I don't think it's a good idea to put `.` in the ID column in the first place...

**detect.snp.col** portion of the code

This was really problematic when the VCF file had less than 100 line of markers. Which I never saw until very recently.

The purpose of sampling 100 unique LOCUS was to speed up detection. it's now changed to:

```
if (nrow(input) > 100) {
    detect.snp.col <- sample(x = unique(input$LOCUS), size = 100, replace = FALSE) %>%
      stringi::stri_detect_fixed(str = ., pattern = "_") %>%
      unique
  } else {
    detect.snp.col <- unique(stringi::stri_detect_fixed(str = input$LOCUS, pattern = "_"))
  }
```

Hope this help
Thierry

**Comment by thierrygosselin** [comment]
I actually prefer your version (I had not see the pull request example)

```
sample.size <- min(length(unique(input$LOCUS)), 100)

  detect.snp.col <- sample(x = unique(input$LOCUS), size = sample.size, replace = FALSE) %>%
    stringi::stri_detect_fixed(str = ., pattern = "_") %>%
    unique
  sample.size <- NULL
```
