### ISSUE TITLE
write_colony producing NAs

### ISSUE THREAD

**Issue by Brittbrockers** [thierrygosselin/radiator#130]
**Describe the bug**
Hi Thierry, 
We've been trying to create a colony file from SNP data and I'm having trouble with a bunch of NAs being produced from seemingly nowhere - every locus is duplicated meaning there's twice the number of alleles in the output compared to my data, with the duplicate always being an NA. I thought this was an issue with my data until we went back and tried to recreate a colony input file for a previous dataset that had worked- NA's are now produced there, too. 

**To Reproduce**

install.packages("remotes")
remotes::install_github("thierrygosselin/radiator")
library(radiator)
# load filtered genlight file
load("gl_maf05_sourceinds.R")
gl.data.filt <- source
# callrate to 1 to remove NA from data - colony cannot deal with NAs. 
gl.data.filt <- gl.filter.callrate(gl.data.filt, method="loc", threshold=1, plot=FALSE) 
# create a tidy dataset from the genlight file 
tidy_quoll_gl_filt<-tidy_genlight(gl.data.filt)
# new radiator output has GT_BIN instead of GT, renamed column so function write_colony will run
tidy_quoll <- rename(tidy_quoll_gl_filt, GT=GT_BIN)
# test file production with short runtimes
write_colony(data = tidy_quoll, run.length = 2, analysis = 1, filename = "Quoll_colony_maf05.txt")

* the complete error message you're getting*
There is no error message being produced now we renamed the GT_BIN column as GT so that write_colony will run. 
Previously, when the renaming step is not used, the error read:

> tidy_quoll<-tidy_genlight(gl.data.filt)
Calibrating REF/ALT alleles...
Generating GDS...
File written: radiator_20210607@1522.gds.rad
> write_colony(data = tidy_quoll, run.length = 2, analysis = 1, filename = "Quoll_colony_maf05_FL.txt")
Importing data...
Calibrating REF/ALT alleles...
Generating COLONY file...
Error: Can't subset columns that don't exist.
x Column `GT` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
Computation time, overall: 0 sec

We are not sure if the the issue is a the tidy_genlight step, where the column now reads GT_BIN where it used to be GT, or if it's later on when running the write_colony function. Basically, it seems as though the DArT SNP data we are working with is not properly being distributed into the tibble, with both alleles being coded for in one column as a 0,1,2 genotype and a second allele column receiving only NAs. 

As a second note, we are not sure that the data is compatible with colony even when these extra NA columns are removed by hand, as the dataset contains a lot of 0's for homozygous state loci and COLONY reads 0's as NAs.

* the output of `devtools::session_info()`
- Session info -------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.1.0 (2021-05-18)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Sydney            
 date     2021-06-07                  

- Packages -----------------------------------------------------------------------------------------------------------------------------------------------
 package          * version   date       lib source                                   
 ade4             * 1.7-16    2020-10-28 [1] CRAN (R 4.1.0)                           
 adegenet         * 2.1.3     2020-05-10 [1] CRAN (R 4.1.0)                           
 ape                5.5       2021-04-25 [1] CRAN (R 4.1.0)                           
 assertthat         0.2.1     2019-03-21 [1] CRAN (R 4.1.0)                           
 BiocGenerics       0.38.0    2021-05-19 [1] Bioconductor                             
 Biostrings         2.60.0    2021-05-20 [1] Bioconductor                             
 bitops             1.0-7     2021-04-24 [1] CRAN (R 4.1.0)                           
 boot               1.3-28    2021-05-03 [2] CRAN (R 4.1.0)                           
 cachem             1.0.5     2021-05-15 [1] CRAN (R 4.1.0)                           
 calibrate          1.7.7     2020-06-19 [1] CRAN (R 4.1.0)                           
 callr              3.7.0     2021-04-20 [1] CRAN (R 4.1.0)                           
 class              7.3-19    2021-05-03 [2] CRAN (R 4.1.0)                           
 classInt           0.4-3     2020-04-07 [1] CRAN (R 4.1.0)                           
 cli                2.5.0     2021-04-26 [1] CRAN (R 4.1.0)                           
 cluster            2.1.2     2021-04-17 [2] CRAN (R 4.1.0)                           
 coda               0.19-4    2020-09-30 [1] CRAN (R 4.1.0)                           
 codetools          0.2-18    2020-11-04 [2] CRAN (R 4.1.0)                           
 colorspace         2.0-1     2021-05-04 [1] CRAN (R 4.1.0)                           
 combinat           0.0-8     2012-10-29 [1] CRAN (R 4.1.0)                           
 crayon             1.4.1     2021-02-08 [1] CRAN (R 4.1.0)                           
 dartR            * 1.9.9.1   2021-05-28 [1] CRAN (R 4.1.0)                           
 data.table         1.14.0    2021-02-21 [1] CRAN (R 4.1.0)                           
 DBI                1.1.1     2021-01-15 [1] CRAN (R 4.1.0)                           
 deldir             0.2-10    2021-02-16 [1] CRAN (R 4.1.0)                           
 DEoptimR           1.0-9     2021-05-24 [1] CRAN (R 4.1.0)                           
 desc               1.3.0     2021-03-05 [1] CRAN (R 4.1.0)                           
 devtools           2.4.1     2021-05-05 [1] CRAN (R 4.1.0)                           
 digest             0.6.27    2020-10-24 [1] CRAN (R 4.1.0)                           
 dismo              1.3-3     2020-11-17 [1] CRAN (R 4.1.0)                           
 doParallel         1.0.16    2020-10-16 [1] CRAN (R 4.1.0)                           
 dplyr              1.0.6     2021-05-05 [1] CRAN (R 4.1.0)                           
 e1071              1.7-7     2021-05-23 [1] CRAN (R 4.1.0)                           
 ellipsis           0.3.2     2021-04-29 [1] CRAN (R 4.1.0)                           
 expm               0.999-6   2021-01-13 [1] CRAN (R 4.1.0)                           
 fansi              0.4.2     2021-01-15 [1] CRAN (R 4.1.0)                           
 fastmap            1.1.0     2021-01-25 [1] CRAN (R 4.1.0)                           
 foreach            1.5.1     2020-10-15 [1] CRAN (R 4.1.0)                           
 fs                 1.5.0     2020-07-31 [1] CRAN (R 4.1.0)                           
 gap                1.2.3-1   2021-04-21 [1] CRAN (R 4.1.0)                           
 gdata              2.18.0    2017-06-06 [1] CRAN (R 4.1.0)                           
 gdistance          1.3-6     2020-06-29 [1] CRAN (R 4.1.0)                           
 gdsfmt             1.28.0    2021-05-19 [1] Bioconductor                             
 generics           0.1.0     2020-10-31 [1] CRAN (R 4.1.0)                           
 genetics           1.3.8.1.3 2021-03-01 [1] CRAN (R 4.1.0)                           
 GenomeInfoDb       1.28.0    2021-05-19 [1] Bioconductor                             
 GenomeInfoDbData   1.2.6     2021-06-06 [1] Bioconductor                             
 GenomicRanges      1.44.0    2021-05-19 [1] Bioconductor                             
 GGally             2.1.1     2021-03-08 [1] CRAN (R 4.1.0)                           
 ggplot2          * 3.3.3     2020-12-30 [1] CRAN (R 4.1.0)                           
 glue               1.4.2     2020-08-27 [1] CRAN (R 4.1.0)                           
 gmodels            2.18.1    2018-06-25 [1] CRAN (R 4.1.0)                           
 gridExtra          2.3       2017-09-09 [1] CRAN (R 4.1.0)                           
 gtable             0.3.0     2019-03-25 [1] CRAN (R 4.1.0)                           
 gtools             3.8.2     2020-03-31 [1] CRAN (R 4.1.0)                           
 hierfstat        * 0.5-7     2020-07-20 [1] CRAN (R 4.1.0)                           
 hms                1.1.0     2021-05-17 [1] CRAN (R 4.1.0)                           
 htmltools          0.5.1.1   2021-01-22 [1] CRAN (R 4.1.0)                           
 htmlwidgets        1.5.3     2020-12-10 [1] CRAN (R 4.1.0)                           
 httpuv             1.6.1     2021-05-07 [1] CRAN (R 4.1.0)                           
 httr               1.4.2     2020-07-20 [1] CRAN (R 4.1.0)                           
 igraph             1.2.6     2020-10-06 [1] CRAN (R 4.1.0)                           
 IRanges            2.26.0    2021-05-19 [1] Bioconductor                             
 iterators          1.0.13    2020-10-15 [1] CRAN (R 4.1.0)                           
 jsonlite           1.7.2     2020-12-09 [1] CRAN (R 4.1.0)                           
 KernSmooth         2.23-20   2021-05-03 [2] CRAN (R 4.1.0)                           
 knitr              1.33      2021-04-24 [1] CRAN (R 4.1.0)                           
 later              1.2.0     2021-04-23 [1] CRAN (R 4.1.0)                           
 lattice            0.20-44   2021-05-02 [2] CRAN (R 4.1.0)                           
 lazyeval           0.2.2     2019-03-15 [1] CRAN (R 4.1.0)                           
 LearnBayes         2.15.1    2018-03-18 [1] CRAN (R 4.1.0)                           
 lifecycle          1.0.0     2021-02-15 [1] CRAN (R 4.1.0)                           
 magrittr           2.0.1     2020-11-17 [1] CRAN (R 4.1.0)                           
 MASS               7.3-54    2021-05-03 [2] CRAN (R 4.1.0)                           
 Matrix             1.3-3     2021-05-04 [2] CRAN (R 4.1.0)                           
 memoise            2.0.0     2021-01-26 [1] CRAN (R 4.1.0)                           
 mgcv               1.8-35    2021-04-18 [2] CRAN (R 4.1.0)                           
 mime               0.10      2021-02-13 [1] CRAN (R 4.1.0)                           
 mmod               1.3.3     2017-04-06 [1] CRAN (R 4.1.0)                           
 munsell            0.5.0     2018-06-12 [1] CRAN (R 4.1.0)                           
 mvtnorm            1.1-1     2020-06-09 [1] CRAN (R 4.1.0)                           
 nlme               3.1-152   2021-02-04 [2] CRAN (R 4.1.0)                           
 pegas              1.0-1     2021-05-17 [1] CRAN (R 4.1.0)                           
 permute            0.9-5     2019-03-12 [1] CRAN (R 4.1.0)                           
 pillar             1.6.1     2021-05-16 [1] CRAN (R 4.1.0)                           
 pkgbuild           1.2.0     2020-12-15 [1] CRAN (R 4.1.0)                           
 pkgconfig          2.0.3     2019-09-22 [1] CRAN (R 4.1.0)                           
 pkgload            1.2.1     2021-04-06 [1] CRAN (R 4.1.0)                           
 plotly           * 4.9.3     2021-01-10 [1] CRAN (R 4.1.0)                           
 plyr               1.8.6     2020-03-03 [1] CRAN (R 4.1.0)                           
 png                0.1-7     2013-12-03 [1] CRAN (R 4.1.0)                           
 PopGenReport       3.0.4     2019-02-04 [1] CRAN (R 4.1.0)                           
 prettyunits        1.1.1     2020-01-24 [1] CRAN (R 4.1.0)                           
 processx           3.5.2     2021-04-30 [1] CRAN (R 4.1.0)                           
 progress           1.2.2     2019-05-16 [1] CRAN (R 4.1.0)                           
 promises           1.2.0.1   2021-02-11 [1] CRAN (R 4.1.0)                           
 proxy              0.4-25    2021-03-05 [1] CRAN (R 4.1.0)                           
 ps                 1.6.0     2021-02-28 [1] CRAN (R 4.1.0)                           
 purrr              0.3.4     2020-04-17 [1] CRAN (R 4.1.0)                           
 R.methodsS3        1.8.1     2020-08-26 [1] CRAN (R 4.1.0)                           
 R.oo               1.24.0    2020-08-26 [1] CRAN (R 4.1.0)                           
 R.utils            2.10.1    2020-08-26 [1] CRAN (R 4.1.0)                           
 R6                 2.5.0     2020-10-28 [1] CRAN (R 4.1.0)                           
 radiator         * 1.1.9     2021-06-06 [1] Github (thierrygosselin/radiator@5c6b865)
 raster             3.4-10    2021-05-03 [1] CRAN (R 4.1.0)                           
 RColorBrewer       1.1-2     2014-12-07 [1] CRAN (R 4.1.0)                           
 Rcpp               1.0.6     2021-01-15 [1] CRAN (R 4.1.0)                           
 RCurl              1.98-1.3  2021-03-16 [1] CRAN (R 4.1.0)                           
 readr              1.4.0     2020-10-05 [1] CRAN (R 4.1.0)                           
 remotes            2.4.0     2021-06-02 [1] CRAN (R 4.1.0)                           
 reshape            0.8.8     2018-10-23 [1] CRAN (R 4.1.0)                           
 reshape2           1.4.4     2020-04-09 [1] CRAN (R 4.1.0)                           
 rgdal              1.5-23    2021-02-03 [1] CRAN (R 4.1.0)                           
 RgoogleMaps        1.4.5.3   2020-02-12 [1] CRAN (R 4.1.0)                           
 rlang              0.4.11    2021-04-30 [1] CRAN (R 4.1.0)                           
 robustbase         0.93-7    2021-01-04 [1] CRAN (R 4.1.0)                           
 rprojroot          2.0.2     2020-11-15 [1] CRAN (R 4.1.0)                           
 rstudioapi         0.13      2020-11-12 [1] CRAN (R 4.1.0)                           
 S4Vectors          0.30.0    2021-05-19 [1] Bioconductor                             
 scales             1.1.1     2020-05-11 [1] CRAN (R 4.1.0)                           
 SeqArray           1.32.0    2021-05-19 [1] Bioconductor                             
 seqinr             4.2-5     2020-12-17 [1] CRAN (R 4.1.0)                           
 sessioninfo        1.1.1     2018-11-05 [1] CRAN (R 4.1.0)                           
 sf                 0.9-8     2021-03-17 [1] CRAN (R 4.1.0)                           
 shiny              1.6.0     2021-01-25 [1] CRAN (R 4.1.0)                           
 SNPRelate          1.26.0    2021-05-19 [1] Bioconductor                             
 sp                 1.4-5     2021-01-10 [1] CRAN (R 4.1.0)                           
 spData             0.3.8     2020-07-03 [1] CRAN (R 4.1.0)                           
 spdep              1.1-8     2021-05-23 [1] CRAN (R 4.1.0)                           
 StAMPP             1.6.2     2021-04-26 [1] CRAN (R 4.1.0)                           
 stringi            1.6.1     2021-05-10 [1] CRAN (R 4.1.0)                           
 stringr            1.4.0     2019-02-10 [1] CRAN (R 4.1.0)                           
 testthat           3.0.2     2021-02-14 [1] CRAN (R 4.1.0)                           
 tibble             3.1.2     2021-05-16 [1] CRAN (R 4.1.0)                           
 tidyr              1.1.3     2021-03-03 [1] CRAN (R 4.1.0)                           
 tidyselect         1.1.1     2021-04-30 [1] CRAN (R 4.1.0)                           
 units              0.7-1     2021-03-16 [1] CRAN (R 4.1.0)                           
 usethis            2.0.1     2021-02-10 [1] CRAN (R 4.1.0)                           
 utf8               1.2.1     2021-03-12 [1] CRAN (R 4.1.0)                           
 vctrs              0.3.8     2021-04-29 [1] CRAN (R 4.1.0)                           
 vegan              2.5-7     2020-11-28 [1] CRAN (R 4.1.0)                           
 viridisLite        0.4.0     2021-04-13 [1] CRAN (R 4.1.0)                           
 withr              2.4.2     2021-04-18 [1] CRAN (R 4.1.0)                           
 xfun               0.23      2021-05-15 [1] CRAN (R 4.1.0)                           
 xtable             1.8-4     2019-04-21 [1] CRAN (R 4.1.0)                           
 XVector            0.32.0    2021-05-19 [1] Bioconductor                             
 zlibbioc           1.38.0    2021-05-19 [1] Bioconductor                             

[1] C:/Users/britt/OneDrive - Australian National University/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.0/library

* complete data required to reproduce the problem, a subset of it. The data remains confidential.
See attachments
**Screenshots**
See attachments

[WRITE_COLONY-ISSUE.zip](https://github.com/thierrygosselin/radiator/files/6606079/WRITE_COLONY-ISSUE.zip)

**Comment by thierrygosselin** [comment]
> tidy_quoll <- rename(tidy_quoll_gl_filt, GT=GT_BIN)

That will definitely won't work, it's not the same format. `GT` format is gene pop with 6 digits for the 2 alleles e.g. 001002
`GT_BIN` format is the dosage of alternate allele and in the published version it will probably be called GT_DA or GT_ALT, still not sure.

**Comment by thierrygosselin** [comment]
Ho it's your genlight object, I thought it was your code... sorry, I'll have a look at it

**Comment by thierrygosselin** [comment]
**dartR** ok ... so running this:

```
library(radiator)
library(dartR)

load("gl_maf05_sourceinds.R")
gl.data.filt <- source
gl.data.filt2 <- dartR::gl.filter.callrate(x = gl.data.filt, method = "loc", threshold = 1, plot = FALSE)
```

gives me this:

```
Starting Error in cat("Starting", funname, "\n") : 
  argument 2 (type 'language') cannot be handled by 'cat'
```

I don't really have time to troubleshoot **dartR** so I'm going to explore your data like I usually do with datasets I receive. And colony requires filtered data...

**Comment by thierrygosselin** [comment]
Removing `dartR::` in front of the function
```
gl.data.filt2 <- gl.filter.callrate(x = gl.data.filt, method = "loc", threshold = 1, plot = FALSE)
Starting gl.filter.callrate 
  Processing a SNP dataset
  Warning: Dataset contains monomorphic loci which will be included in the Call Rate calculations for the filtering
  Recalculating Call Rate
  Removing loci based on Call Rate, threshold = 1 
Completed: gl.filter.callrate 
```

**Comment by thierrygosselin** [comment]
will run with dartR filtered data like you did in your example and with radiator filters in parallel

**Comment by thierrygosselin** [comment]
Ok so I had a look at the data.

1. before running colony you'll probably want to remove the duplicate samples in your dataset:

88DB3a = 88DB3b: **keep 88DB3b**
FD9EBa = FD9EBb: **keep FD9EBa**

2. remove samples with obvious heterozygosity problems
- it's either a different species (if that's possible for your project) or wet lab / sequencing problem, it's usually 99% the later
- Strata *Surrey_Hills* is the most affected by this, sample **8F1D7** is definitely an outlier that I would remove
- problematic samples will generate false / artifact close kin ...

**Comment by thierrygosselin** [comment]
All the tests below works for me, reopen the issue if you're still experiencing issues.

```
library(radiator) # install the latest release
load("gl_maf05_sourceinds.R")
data <- source
test1 <- radiator::tidy_genlight(data = data, verbose = TRUE)
test2 <- radiator::write_colony(data = test1, print.all.colony.opt = TRUE)
test3 <- radiator::tidy_genomic_data(data = data)
test4 <- radiator::filter_rad(data = data)
```
