### ISSUE TITLE
Axes missing on interactive filtering plots

### ISSUE THREAD

**Issue by Istiompax1** [thierrygosselin/radiator#131]
[example plot 1.pdf](https://github.com/thierrygosselin/radiator/files/6644971/example.plot.1.pdf)
[example plot 2.pdf](https://github.com/thierrygosselin/radiator/files/6644972/example.plot.2.pdf)

When I look to use Filter_rad and sex.markers interactive filtering functions, the code executes fine, however, the axes on the plots are missing. I have attached two example plots to show this. I have looking to reinstalled ggplot and radiator but these did not seem in resolve the issue. 

An example of the code and processing as as below:

> test1<-radiator::filter_rad(data = "mudcrab2.csv",
+                             strata = "Mudcrab_Strata1.tsv", output = c("genlight"),
+                             parallel.core = 1L)
################################################################################
################################################################################
Execution date@time: 20210614@1042
Folder created: filter_rad_20210614@1042
Function call and arguments stored in: radiator_filter_rad_args_20210614@1042.tsv
File written: random.seed (483426)
Filters parameters file generated: filters_parameters_20210614@1042.tsv
Reading DArT file...
Number of blacklisted samples: 0
DArT SNP format: genotypes in 1 Row
Generating genotypes and calibrating REF/ALT alleles...
Number of markers recalibrated based on counts of allele: 4846
Generating GDS...
File written: radiator_20210614@1042.gds.rad

Number of chrom: 1
Number of locus: 32632
Number of SNPs: 38693
Number of strata: 10
Number of individuals: 188

Number of ind/strata:
Mackay = 19
Hinchinbrook = 19
Karumba = 18
Moreton = 19
Gladstone = 19
Port_Stephens = 19
Wallis = 18
Macleay = 19
Clarence = 19
Tweed = 19

Number of duplicate id: 0

Computation time, overall: 22 sec
################################################################################
################################################################################
Execution date@time: 20210614@1043
Function call and arguments stored in: radiator_filter_dart_reproducibility_args_20210614@1043.tsv

**Comment by thierrygosselin** [comment]
try with latest release if it's still relevant

**Comment by Istiompax1** [comment]
Hi,

I updated to package version 1.2.0, and looked to run the filtering but still do not have axis labels on any plots.

- Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Brisbane          
 date     2021-06-17                  

- Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------
 package          * version  date       lib source                                   
 abind              1.4-5    2016-07-21 [1] CRAN (R 4.0.3)                           
 ade4             * 1.7-16   2020-10-28 [1] CRAN (R 4.0.3)                           
 adegenet         * 2.1.3    2020-05-10 [1] CRAN (R 4.0.3)                           
 ape              * 5.4-1    2020-08-13 [1] CRAN (R 4.0.3)                           
 assertthat         0.2.1    2019-03-21 [1] CRAN (R 4.0.3)                           
 backports          1.2.1    2020-12-09 [1] CRAN (R 4.0.2)                           
 base64enc          0.1-3    2015-07-28 [1] CRAN (R 4.0.3)                           
 bayesm             3.1-4    2019-10-15 [1] CRAN (R 4.0.3)                           
 BiocGenerics       0.36.0   2020-10-27 [1] Bioconductor                             
 BiocManager        1.30.12  2021-03-28 [1] CRAN (R 4.0.5)                           
 Biostrings         2.56.0   2020-04-27 [1] Bioconductor                             
 bitops             1.0-6    2013-08-17 [1] CRAN (R 4.0.3)                           
 boot               1.3-25   2020-04-26 [2] CRAN (R 4.0.3)                           
 broom              0.7.6    2021-04-05 [1] CRAN (R 4.0.5)                           
 cachem             1.0.4    2021-02-13 [1] CRAN (R 4.0.5)                           
 callr              3.6.0    2021-03-28 [1] CRAN (R 4.0.5)                           
 carrier            0.1.0    2018-10-16 [1] CRAN (R 4.0.3)                           
 checkmate          2.0.0    2020-02-06 [1] CRAN (R 4.0.3)                           
 class              7.3-17   2020-04-26 [2] CRAN (R 4.0.3)                           
 classInt           0.4-3    2020-04-07 [1] CRAN (R 4.0.3)                           
 cli                2.4.0    2021-04-05 [1] CRAN (R 4.0.5)                           
 cluster            2.1.1    2021-02-14 [1] CRAN (R 4.0.5)                           
 coda               0.19-4   2020-09-30 [1] CRAN (R 4.0.3)                           
 codetools          0.2-16   2018-12-24 [2] CRAN (R 4.0.3)                           
 colorspace         2.0-0    2020-11-11 [1] CRAN (R 4.0.3)                           
 compositions       2.0-1    2021-01-08 [1] CRAN (R 4.0.3)                           
 corpcor            1.6.9    2017-04-01 [1] CRAN (R 4.0.3)                           
 crayon             1.4.1    2021-02-08 [1] CRAN (R 4.0.5)                           
 data.table         1.14.0   2021-02-21 [1] CRAN (R 4.0.5)                           
 DBI                1.1.1    2021-01-15 [1] CRAN (R 4.0.3)                           
 deldir             0.2-10   2021-02-16 [1] CRAN (R 4.0.4)                           
 DEoptimR           1.0-8    2016-11-19 [1] CRAN (R 4.0.3)                           
 desc               1.3.0    2021-03-05 [1] CRAN (R 4.0.5)                           
 devtools         * 2.4.0    2021-04-07 [1] CRAN (R 4.0.5)                           
 digest             0.6.27   2020-10-24 [1] CRAN (R 4.0.3)                           
 diveRsity          1.9.90   2017-04-04 [1] CRAN (R 4.0.5)                           
 dplyr            * 1.0.5    2021-03-05 [1] CRAN (R 4.0.5)                           
 e1071              1.7-6    2021-03-18 [1] CRAN (R 4.0.5)                           
 ellipsis           0.3.1    2020-05-15 [1] CRAN (R 4.0.3)                           
 expm               0.999-6  2021-01-13 [1] CRAN (R 4.0.3)                           
 fansi              0.4.2    2021-01-15 [1] CRAN (R 4.0.3)                           
 farver             2.1.0    2021-02-28 [1] CRAN (R 4.0.5)                           
 fastmap            1.1.0    2021-01-25 [1] CRAN (R 4.0.3)                           
 fdrtool            1.2.16   2021-01-06 [1] CRAN (R 4.0.3)                           
 foreign            0.8-80   2020-05-24 [2] CRAN (R 4.0.3)                           
 Formula            1.2-4    2020-10-16 [1] CRAN (R 4.0.3)                           
 fs                 1.5.0    2020-07-31 [1] CRAN (R 4.0.3)                           
 fst                0.9.4    2020-08-27 [1] CRAN (R 4.0.3)                           
 furrr              0.2.2    2021-01-29 [1] CRAN (R 4.0.3)                           
 future             1.21.0   2020-12-10 [1] CRAN (R 4.0.3)                           
 gdata              2.18.0   2017-06-06 [1] CRAN (R 4.0.3)                           
 gdsfmt           * 1.26.1   2020-12-22 [1] Bioconductor                             
 generics           0.1.0    2020-10-31 [1] CRAN (R 4.0.3)                           
 GenomeInfoDb       1.24.2   2020-06-15 [1] Bioconductor                             
 GenomeInfoDbData * 1.2.3    2021-04-29 [1] Bioconductor                             
 GenomicRanges      1.40.0   2020-04-27 [1] Bioconductor                             
 ggplot2          * 3.3.3    2020-12-30 [1] CRAN (R 4.0.5)                           
 ggtern           * 3.3.0    2020-04-11 [1] CRAN (R 4.0.3)                           
 glasso             1.11     2019-10-01 [1] CRAN (R 4.0.3)                           
 globals            0.14.0   2020-11-22 [1] CRAN (R 4.0.3)                           
 glue               1.4.2    2020-08-27 [1] CRAN (R 4.0.3)                           
 gmodels            2.18.1   2018-06-25 [1] CRAN (R 4.0.3)                           
 gridExtra          2.3      2017-09-09 [1] CRAN (R 4.0.3)                           
 gtable             0.3.0    2019-03-25 [1] CRAN (R 4.0.3)                           
 gtools             3.8.2    2020-03-31 [1] CRAN (R 4.0.3)                           
 HardyWeinberg    * 1.7.1    2021-01-04 [1] CRAN (R 4.0.3)                           
 hierfstat        * 0.5-7    2020-07-20 [1] CRAN (R 4.0.3)                           
 Hmisc              4.5-0    2021-02-28 [1] CRAN (R 4.0.5)                           
 hms                1.0.0    2021-01-13 [1] CRAN (R 4.0.3)                           
 htmlTable          2.1.0    2020-09-16 [1] CRAN (R 4.0.3)                           
 htmltools          0.5.1.1  2021-01-22 [1] CRAN (R 4.0.3)                           
 htmlwidgets        1.5.3    2020-12-10 [1] CRAN (R 4.0.3)                           
 httpuv             1.5.5    2021-01-13 [1] CRAN (R 4.0.3)                           
 igraph             1.2.6    2020-10-06 [1] CRAN (R 4.0.3)                           
 IRanges            2.24.1   2020-12-12 [1] Bioconductor                             
 jpeg               0.1-8.1  2019-10-24 [1] CRAN (R 4.0.3)                           
 KernSmooth         2.23-17  2020-04-26 [2] CRAN (R 4.0.3)                           
 knitr              1.31     2021-01-27 [1] CRAN (R 4.0.3)                           
 labeling           0.4.2    2020-10-20 [1] CRAN (R 4.0.3)                           
 later              1.1.0.1  2020-06-05 [1] CRAN (R 4.0.3)                           
 latex2exp          0.5.0    2021-03-18 [1] CRAN (R 4.0.5)                           
 lattice            0.20-41  2020-04-02 [1] CRAN (R 4.0.2)                           
 latticeExtra       0.6-29   2019-12-19 [1] CRAN (R 4.0.3)                           
 lavaan             0.6-8    2021-03-10 [1] CRAN (R 4.0.5)                           
 LearnBayes         2.15.1   2018-03-18 [1] CRAN (R 4.0.3)                           
 lifecycle          1.0.0    2021-02-15 [1] CRAN (R 4.0.5)                           
 listenv            0.8.0    2019-12-05 [1] CRAN (R 4.0.3)                           
 magrittr           2.0.1    2020-11-17 [1] CRAN (R 4.0.3)                           
 MASS               7.3-53   2020-09-09 [2] CRAN (R 4.0.3)                           
 Matrix             1.2-18   2019-11-27 [1] CRAN (R 4.0.2)                           
 memoise            2.0.0    2021-01-26 [1] CRAN (R 4.0.3)                           
 mgcv               1.8-33   2020-08-27 [2] CRAN (R 4.0.3)                           
 mice             * 3.13.0   2021-01-27 [1] CRAN (R 4.0.3)                           
 mime               0.10     2021-02-13 [1] CRAN (R 4.0.4)                           
 mnormt             2.0.2    2020-09-01 [1] CRAN (R 4.0.3)                           
 munsell            0.5.0    2018-06-12 [1] CRAN (R 4.0.3)                           
 nlme               3.1-149  2020-08-23 [2] CRAN (R 4.0.3)                           
 nnet               7.3-14   2020-04-26 [2] CRAN (R 4.0.3)                           
 parallelly         1.24.0   2021-03-14 [1] CRAN (R 4.0.4)                           
 pbapply            1.4-3    2020-08-18 [1] CRAN (R 4.0.3)                           
 pbivnorm           0.6.0    2015-01-23 [1] CRAN (R 4.0.3)                           
 pegas            * 1.0      2021-04-08 [1] CRAN (R 4.0.5)                           
 permute            0.9-5    2019-03-12 [1] CRAN (R 4.0.3)                           
 pillar             1.6.0    2021-04-13 [1] CRAN (R 4.0.5)                           
 pkgbuild           1.2.0    2020-12-15 [1] CRAN (R 4.0.2)                           
 pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 4.0.3)                           
 pkgload            1.2.1    2021-04-06 [1] CRAN (R 4.0.5)                           
 plyr               1.8.6    2020-03-03 [1] CRAN (R 4.0.3)                           
 png                0.1-7    2013-12-03 [1] CRAN (R 4.0.3)                           
 prettyunits        1.1.1    2020-01-24 [1] CRAN (R 4.0.3)                           
 processx           3.5.1    2021-04-04 [1] CRAN (R 4.0.5)                           
 progress           1.2.2    2019-05-16 [1] CRAN (R 4.0.3)                           
 progressr          0.7.0    2020-12-11 [1] CRAN (R 4.0.5)                           
 promises           1.2.0.1  2021-02-11 [1] CRAN (R 4.0.5)                           
 proto              1.0.0    2016-10-29 [1] CRAN (R 4.0.3)                           
 proxy              0.4-25   2021-03-05 [1] CRAN (R 4.0.5)                           
 ps                 1.6.0    2021-02-28 [1] CRAN (R 4.0.5)                           
 psych              2.1.3    2021-03-27 [1] CRAN (R 4.0.5)                           
 purrr            * 0.3.4    2020-04-17 [1] CRAN (R 4.0.3)                           
 qgraph             1.6.9    2021-01-28 [1] CRAN (R 4.0.5)                           
 R6                 2.5.0    2020-10-28 [1] CRAN (R 4.0.3)                           
 radiator         * 1.2.0    2021-06-16 [1] Github (thierrygosselin/radiator@7c5f41a)
 raster             3.4-5    2020-11-14 [1] CRAN (R 4.0.3)                           
 RColorBrewer     * 1.1-2    2014-12-07 [1] CRAN (R 4.0.3)                           
 Rcpp               1.0.6    2021-01-15 [1] CRAN (R 4.0.3)                           
 RCurl              1.98-1.2 2020-04-18 [1] CRAN (R 4.0.3)                           
 readr              1.4.0    2020-10-05 [1] CRAN (R 4.0.3)                           
 remotes            2.3.0    2021-04-01 [1] CRAN (R 4.0.5)                           
 reshape2           1.4.4    2020-04-09 [1] CRAN (R 4.0.3)                           
 rlang              0.4.10   2020-12-30 [1] CRAN (R 4.0.3)                           
 robustbase       * 0.93-7   2021-01-04 [1] CRAN (R 4.0.3)                           
 rpart              4.1-15   2019-04-12 [1] CRAN (R 4.0.2)                           
 rprojroot          2.0.2    2020-11-15 [1] CRAN (R 4.0.3)                           
 Rsolnp           * 1.16     2015-12-28 [1] CRAN (R 4.0.3)                           
 rstudioapi         0.13     2020-11-12 [1] CRAN (R 4.0.3)                           
 S4Vectors          0.28.1   2020-12-09 [1] Bioconductor                             
 scales             1.1.1    2020-05-11 [1] CRAN (R 4.0.3)                           
 SeqArray         * 1.28.1   2020-06-16 [1] Bioconductor                             
 seqinr             4.2-5    2020-12-17 [1] CRAN (R 4.0.3)                           
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 4.0.3)                           
 sf                 0.9-8    2021-03-17 [1] CRAN (R 4.0.5)                           
 shiny              1.6.0    2021-01-25 [1] CRAN (R 4.0.3)                           
 SNPRelate          1.22.0   2020-04-27 [1] Bioconductor                             
 sp                 1.4-5    2021-01-10 [1] CRAN (R 4.0.3)                           
 spData             0.3.8    2020-07-03 [1] CRAN (R 4.0.3)                           
 spdep              1.1-7    2021-04-03 [1] CRAN (R 4.0.5)                           
 stringi            1.5.3    2020-09-09 [1] CRAN (R 4.0.3)                           
 stringr          * 1.4.0    2019-02-10 [1] CRAN (R 4.0.3)                           
 survival           3.2-7    2020-09-28 [2] CRAN (R 4.0.3)                           
 tensorA            0.36.2   2020-11-19 [1] CRAN (R 4.0.3)                           
 testthat           3.0.2    2021-02-14 [1] CRAN (R 4.0.5)                           
 tibble             3.0.6    2021-01-29 [1] CRAN (R 4.0.3)                           
 tidyr              1.1.3    2021-03-03 [1] CRAN (R 4.0.5)                           
 tidyselect         1.1.0    2020-05-11 [1] CRAN (R 4.0.3)                           
 tmvnsim            1.0-2    2016-12-15 [1] CRAN (R 4.0.3)                           
 truncnorm          1.0-8    2018-02-27 [1] CRAN (R 4.0.3)                           
 units              0.7-1    2021-03-16 [1] CRAN (R 4.0.5)                           
 UpSetR             1.4.0    2019-05-22 [1] CRAN (R 4.0.3)                           
 usethis          * 2.0.1    2021-02-10 [1] CRAN (R 4.0.5)                           
 utf8               1.2.1    2021-03-12 [1] CRAN (R 4.0.5)                           
 vctrs              0.3.6    2020-12-17 [1] CRAN (R 4.0.3)                           
 vegan              2.5-7    2020-11-28 [1] CRAN (R 4.0.3)                           
 viridisLite        0.4.0    2021-04-13 [1] CRAN (R 4.0.5)                           
 withr              2.4.1    2021-01-26 [1] CRAN (R 4.0.3)                           
 xfun               0.22     2021-03-11 [1] CRAN (R 4.0.5)                           
 xtable             1.8-4    2019-04-21 [1] CRAN (R 4.0.3)                           
 XVector            0.28.0   2020-04-27 [1] Bioconductor                             
 zlibbioc           1.34.0   2020-04-27 [1] Bioconductor                             

[1] C:/Users/WilliamsS/Documents/R/win-library/4.0
[2] C:/R-4.0.3/library
