### ISSUE TITLE
tidy.data error

### ISSUE THREAD

**Issue by mgavery** [thierrygosselin/radiator#142]
Hi, I am getting an error when trying to run tidy_genepop.  My ultimate goal is to convert the genepop to colony format, but I thought I'd take it one step at a time. Would you be able to help with this error?  I have 562 individuals and 10,256 loci

> tidy.data <- radiator::tidy_genepop(
+   data = "populations_GSR80removed.snps.gen",
+   strata = "Oly_strata.tsv",
+   tidy = TRUE)
Error: `x` and `y` must share the same src, set `copy` = TRUE (may be slow).

Backtrace:
 1. radiator::tidy_genepop(...)
 4. dplyr:::left_join.data.frame(., strata.df, by = "INDIVIDUALS")
 5. dplyr::auto_copy(x, y, copy = copy)
 6. dplyr:::glubort(...)
Run `rlang::last_trace()` to see the full context.

**Comment by thierrygosselin** [comment]
Dear Mackenzie, do you mind sending the dataset and strata by email so that I can replicate your problem

Best
Thierry

**Comment by thierrygosselin** [comment]
Hi Mackenzie, I tested your data with the same code and found no problem.

[Try re-installing radiator](https://thierrygosselin.github.io/radiator/index.html)

```
library(radiator)
setwd("PATH/TO/YOUR/FOLDER")
tidy.data <- radiator::tidy_genepop(
  data = "populations_GSR80removed.snps.gen",
  strata = "Oly_strata.tsv",
  tidy = TRUE)
colony.file <- radiator::write_colony(data = tidy.data)
``` 


If you are still getting an error, give me the output of this:`devtools::session_info()`

**Comment by mgavery** [comment]
Thanks so much for your assistance with this.  I really appreciate it.

I am still getting the same error.  From the session_info I can see that
SeqArray package I'm running is <1.28. I haven't figured out how to get
this updated yet. Do you see any other issues here that I have to solve -
other than getting an update SeqArray package?  Thanks again :)

Best,

Mackenzie

> devtools::session_info()
─ Session info
──────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 3.6.3 (2020-02-29)
 os       macOS Catalina 10.15.7
 system   x86_64, darwin15.6.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Los_Angeles
 date     2021-11-22

─ Packages
──────────────────────────────────────────────────────────────────────────────────────
 ! package          * version  date       lib source

   ade4             * 1.7-16   2020-10-28 [1] CRAN (R 3.6.2)

   adegenet         * 2.1.3    2020-05-10 [1] CRAN (R 3.6.2)

   ape              * 5.4-1    2020-08-13 [1] CRAN (R 3.6.2)

   assertthat         0.2.1    2019-03-21 [1] CRAN (R 3.6.0)

   backports          1.2.1    2020-12-09 [1] CRAN (R 3.6.2)

   Biobase            2.46.0   2019-10-29 [1] Bioconductor

   BiocGenerics       0.32.0   2019-10-29 [1] Bioconductor

   BiocManager        1.30.10  2019-11-16 [1] CRAN (R 3.6.0)

   Biostrings         2.54.0   2019-10-29 [1] Bioconductor

   bitops             1.0-6    2013-08-17 [1] CRAN (R 3.6.0)

   boot               1.3-24   2019-12-20 [2] CRAN (R 3.6.3)

   broom              0.7.3    2020-12-16 [1] CRAN (R 3.6.2)

   callr              3.5.1    2020-10-13 [1] CRAN (R 3.6.2)

   class              7.3-15   2019-01-01 [2] CRAN (R 3.6.3)

   classInt           0.4-3    2020-04-07 [1] CRAN (R 3.6.2)

 V cli                2.2.0    2021-10-27 [1] CRAN (R 3.6.2)

   cluster            2.1.0    2019-06-19 [2] CRAN (R 3.6.3)

   coda               0.19-4   2020-09-30 [1] CRAN (R 3.6.2)

   codetools          0.2-16   2018-12-24 [2] CRAN (R 3.6.3)

   colorspace         2.0-0    2020-11-11 [1] CRAN (R 3.6.2)

   crayon             1.3.4    2017-09-16 [1] CRAN (R 3.6.0)

   curl               4.3      2019-12-02 [1] CRAN (R 3.6.0)

   data.table       * 1.13.4   2020-12-08 [1] CRAN (R 3.6.2)

   DBI                1.1.0    2019-12-15 [1] CRAN (R 3.6.0)

   deldir             0.2-3    2020-11-09 [1] CRAN (R 3.6.2)

   desc               1.2.0    2018-05-01 [1] CRAN (R 3.6.0)

   devtools         * 2.3.2    2020-09-18 [1] CRAN (R 3.6.2)

   digest             0.6.27   2020-10-24 [1] CRAN (R 3.6.2)

   doParallel         1.0.16   2020-10-16 [1] CRAN (R 3.6.2)

 V dplyr            * 1.0.2    2021-06-18 [1] CRAN (R 3.6.2)

   e1071              1.7-4    2020-10-14 [1] CRAN (R 3.6.2)

 V ellipsis           0.3.1    2021-04-29 [1] CRAN (R 3.6.2)

   expm               0.999-5  2020-07-20 [1] CRAN (R 3.6.2)

   factoextra       * 1.0.7    2020-04-01 [1] CRAN (R 3.6.2)

   fansi              0.4.1    2020-01-08 [1] CRAN (R 3.6.0)

   farver             2.0.3    2020-01-16 [1] CRAN (R 3.6.0)

   fastmap            1.1.0    2021-01-25 [1] CRAN (R 3.6.2)

   foreach            1.5.1    2020-10-15 [1] CRAN (R 3.6.2)

   formula.tools      1.7.1    2018-03-01 [1] CRAN (R 3.6.0)

   fs                 1.5.0    2020-07-31 [1] CRAN (R 3.6.2)

   gdata              2.18.0   2017-06-06 [1] CRAN (R 3.6.0)

   gdsfmt             1.22.0   2019-10-29 [1] Bioconductor

   generics           0.1.0    2020-10-31 [1] CRAN (R 3.6.2)

   GenomeInfoDb       1.22.1   2020-03-27 [1] Bioconductor

   GenomeInfoDbData   1.2.2    2020-03-31 [1] Bioconductor

   GenomicRanges      1.38.0   2019-10-29 [1] Bioconductor

   ggplot2          * 3.3.3    2020-12-30 [1] CRAN (R 3.6.3)

   ggrepel          * 0.9.0    2020-12-16 [1] CRAN (R 3.6.2)

   glue               1.4.2    2020-08-27 [1] CRAN (R 3.6.2)

   gmodels            2.18.1   2018-06-25 [1] CRAN (R 3.6.0)

   gridExtra          2.3      2017-09-09 [1] CRAN (R 3.6.0)

   gtable             0.3.0    2019-03-25 [1] CRAN (R 3.6.0)

   gtools             3.8.2    2020-03-31 [1] CRAN (R 3.6.2)

   GWASExactHW        1.01     2013-01-05 [1] CRAN (R 3.6.0)

   hms                0.5.3    2020-01-08 [1] CRAN (R 3.6.0)

   htmltools          0.5.2    2021-08-25 [1] CRAN (R 3.6.2)

   httpuv             1.5.4    2020-06-06 [1] CRAN (R 3.6.2)

   igraph             1.2.6    2020-10-06 [1] CRAN (R 3.6.2)

   IRanges            2.20.2   2020-01-13 [1] Bioconductor

   iterators          1.0.13   2020-10-15 [1] CRAN (R 3.6.2)

   KernSmooth         2.23-16  2019-10-15 [2] CRAN (R 3.6.3)

   labeling           0.4.2    2020-10-20 [1] CRAN (R 3.6.2)

   later              1.1.0.1  2020-06-05 [1] CRAN (R 3.6.2)

   lattice            0.20-38  2018-11-04 [2] CRAN (R 3.6.3)

   LearnBayes         2.15.1   2018-03-18 [1] CRAN (R 3.6.0)

 V lifecycle          0.2.0    2021-09-24 [1] CRAN (R 3.6.2)

   logistf            1.24     2020-09-16 [1] CRAN (R 3.6.2)

   magrittr           2.0.1    2020-11-17 [1] CRAN (R 3.6.2)

   MASS               7.3-51.5 2019-12-20 [2] CRAN (R 3.6.3)

   Matrix             1.2-18   2019-11-27 [2] CRAN (R 3.6.3)

   memoise            1.1.0    2017-04-21 [1] CRAN (R 3.6.0)

   mgcv               1.8-31   2019-11-09 [2] CRAN (R 3.6.3)

   mice               3.12.0   2020-11-14 [1] CRAN (R 3.6.2)

   mime               0.9      2020-02-04 [1] CRAN (R 3.6.0)

   munsell            0.5.0    2018-06-12 [1] CRAN (R 3.6.0)

   nlme               3.1-144  2020-02-06 [2] CRAN (R 3.6.3)

   operator.tools     1.6.3    2017-02-28 [1] CRAN (R 3.6.0)

   pegas            * 0.14     2020-09-16 [1] CRAN (R 3.6.2)

   permute            0.9-5    2019-03-12 [1] CRAN (R 3.6.0)

   pheatmap         * 1.0.12   2019-01-04 [1] CRAN (R 3.6.0)

 V pillar             1.4.7    2021-10-18 [1] CRAN (R 3.6.2)

   pkgbuild           1.2.0    2020-12-15 [1] CRAN (R 3.6.2)

   pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 3.6.0)

   pkgload            1.1.0    2020-05-29 [1] CRAN (R 3.6.2)

   plyr             * 1.8.6    2020-03-03 [1] CRAN (R 3.6.0)

   prettyunits        1.1.1    2020-01-24 [1] CRAN (R 3.6.0)

   processx           3.4.5    2020-11-30 [1] CRAN (R 3.6.2)

   progress           1.2.2    2019-05-16 [1] CRAN (R 3.6.0)

   promises           1.1.1    2020-06-09 [1] CRAN (R 3.6.2)

   ps                 1.5.0    2020-12-05 [1] CRAN (R 3.6.2)

   purrr              0.3.4    2020-04-17 [1] CRAN (R 3.6.2)

   R6                 2.5.0    2020-10-28 [1] CRAN (R 3.6.2)

 V radiator         * 1.1.5    2021-11-22 [1] Github
***@***.***)
   raster             3.4-5    2020-11-14 [1] CRAN (R 3.6.2)

   RColorBrewer     * 1.1-2    2014-12-07 [1] CRAN (R 3.6.0)

   Rcpp               1.0.5    2020-07-06 [1] CRAN (R 3.6.2)

   RCurl              1.98-1.2 2020-04-18 [1] CRAN (R 3.6.2)

   readr              1.4.0    2020-10-05 [1] CRAN (R 3.6.2)

   remotes            2.4.1    2021-09-29 [1] CRAN (R 3.6.2)

   reshape2         * 1.4.4    2020-04-09 [1] CRAN (R 3.6.2)

   rlang              0.4.12   2021-10-18 [1] CRAN (R 3.6.2)

   rprojroot          2.0.2    2020-11-15 [1] CRAN (R 3.6.2)

   S4Vectors          0.24.3   2020-01-18 [1] Bioconductor

   scales             1.1.1    2020-05-11 [1] CRAN (R 3.6.2)

   SeqArray           1.26.2   2019-12-26 [1] Bioconductor

   seqinr             4.2-5    2020-12-17 [1] CRAN (R 3.6.2)

   SeqVarTools        1.24.1   2020-03-17 [1] Bioconductor

   sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 3.6.0)

   sf                 0.9-6    2020-09-13 [1] CRAN (R 3.6.2)

   shiny              1.5.0    2020-06-23 [1] CRAN (R 3.6.2)

   sp                 1.4-4    2020-10-07 [1] CRAN (R 3.6.2)

   spData             0.3.8    2020-07-03 [1] CRAN (R 3.6.2)

   spdep              1.1-5    2020-06-29 [1] CRAN (R 3.6.2)

   StAMPP           * 1.6.1    2020-03-20 [1] CRAN (R 3.6.0)

   stringi            1.5.3    2020-09-09 [1] CRAN (R 3.6.2)

   stringr            1.4.0    2019-02-10 [1] CRAN (R 3.6.0)

   testthat           3.0.1    2020-12-17 [1] CRAN (R 3.6.2)

   tibble           * 3.0.4    2020-10-12 [1] CRAN (R 3.6.2)

   tidyr            * 1.1.2    2020-08-27 [1] CRAN (R 3.6.2)

   tidyselect         1.1.0    2020-05-11 [1] CRAN (R 3.6.2)

   units              0.6-7    2020-06-13 [1] CRAN (R 3.6.2)

   UpSetR             1.4.0    2019-05-22 [1] CRAN (R 3.6.0)

   usethis          * 2.0.0    2020-12-10 [1] CRAN (R 3.6.2)

 V vctrs              0.3.6    2021-04-29 [1] CRAN (R 3.6.2)

   vegan              2.5-7    2020-11-28 [1] CRAN (R 3.6.2)

   withr              2.3.0    2020-09-22 [1] CRAN (R 3.6.2)

   xtable             1.8-4    2019-04-21 [1] CRAN (R 3.6.0)

   XVector            0.26.0   2019-10-29 [1] Bioconductor

   zlibbioc           1.32.0   2019-10-29 [1] Bioconductor


[1] /Users/mackenzie.gavery/Library/R/3.6/library
[2] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

 V ── Loaded and on-disk version mismatch.

**Comment by mgavery** [comment]
Apologies! I needed to restart RStudio.  I am back in action now and
radiator is working for me. Thanks again!!

Best,

Mackenzie
