### ISSUE TITLE
Error in SeqArray::seqOpen(gds.fn = data.safe$result, readonly = FALSE) :    is.character(gds.fn) is not TRUE

### ISSUE THREAD

**Issue by rspfau** [thierrygosselin/radiator#144]
First time using radiator...see below for details of error. 
Thanks, Russell

data <- radiator::filter_rad(
    data = "Final.recode.vcf",
    strata = "strata-frog.txt", 
    output = c("genind", "stockr")
    )

################################################################################
################################################################################
Execution date@time: 20211212@1743
Folder created: filter_rad_20211212@1743
Function call and arguments stored in: radiator_filter_rad_args_20211212@1743.tsv
File written: random.seed (255217)
Filters parameters file generated: filters_parameters_20211212@1743.tsv

Reading VCF... 
Error in SeqArray::seqOpen(gds.fn = data.safe$result, readonly = FALSE) : 
  is.character(gds.fn) is not TRUE

Computation time, overall: 11 sec
############################# completed filter_rad #############################

> devtools::session_info()
- Session info -----------------------------------------------------------------------------------------------------------------

- Packages ---------------------------------------------------------------------------------------------------------------------
 package          * version  date       lib source                                   
 ade4             * 1.7-17   2021-06-17 [1] CRAN (R 4.1.0)                           
 adegenet         * 2.1.4    2021-07-17 [1] CRAN (R 4.1.0)                           
 ape                5.5      2021-04-25 [1] CRAN (R 4.1.0)                           
 assertthat         0.2.1    2019-03-21 [1] CRAN (R 4.1.0)                           
 backports          1.4.0    2021-11-23 [1] CRAN (R 4.1.0)                           
 BiocGenerics       0.38.0   2021-05-19 [1] Bioconductor                             
 BiocManager        1.30.16  2021-06-15 [1] CRAN (R 4.1.0)                           
 Biostrings         2.60.2   2021-08-05 [1] Bioconductor                             
 bit                4.0.4    2020-08-04 [1] CRAN (R 4.1.0)                           
 bit64              4.0.5    2020-08-30 [1] CRAN (R 4.1.0)                           
 bitops             1.0-7    2021-04-24 [1] CRAN (R 4.1.0)                           
 boot               1.3-28   2021-05-03 [2] CRAN (R 4.1.0)                           
 broom              0.7.10   2021-10-31 [1] CRAN (R 4.1.2)                           
 cachem             1.0.5    2021-05-15 [1] CRAN (R 4.1.0)                           
 callr              3.7.0    2021-04-20 [1] CRAN (R 4.1.0)                           
 class              7.3-19   2021-05-03 [2] CRAN (R 4.1.0)                           
 classInt           0.4-3    2020-04-07 [1] CRAN (R 4.1.0)                           
 cli                3.0.0    2021-06-30 [1] CRAN (R 4.1.0)                           
 cluster            2.1.2    2021-04-17 [2] CRAN (R 4.1.0)                           
 coda               0.19-4   2020-09-30 [1] CRAN (R 4.1.0)                           
 codetools          0.2-18   2020-11-04 [2] CRAN (R 4.1.0)                           
 colorspace         2.0-2    2021-06-24 [1] CRAN (R 4.1.0)                           
 crayon             1.4.2    2021-10-29 [1] CRAN (R 4.1.2)                           
 DBI                1.1.1    2021-01-15 [1] CRAN (R 4.1.0)                           
 deldir             0.2-10   2021-02-16 [1] CRAN (R 4.1.0)                           
 desc               1.3.0    2021-03-05 [1] CRAN (R 4.1.0)                           
 devtools           2.4.2    2021-06-07 [1] CRAN (R 4.1.0)                           
 digest             0.6.27   2020-10-24 [1] CRAN (R 4.1.0)                           
 dplyr              1.0.7    2021-06-18 [1] CRAN (R 4.1.0)                           
 e1071              1.7-8    2021-07-28 [1] CRAN (R 4.1.0)                           
 ellipsis           0.3.2    2021-04-29 [1] CRAN (R 4.1.0)                           
 evaluate           0.14     2019-05-28 [1] CRAN (R 4.1.0)                           
 expm               0.999-6  2021-01-13 [1] CRAN (R 4.1.0)                           
 fansi              0.5.0    2021-05-25 [1] CRAN (R 4.1.0)                           
 fastmap            1.1.0    2021-01-25 [1] CRAN (R 4.1.0)                           
 fs                 1.5.0    2020-07-31 [1] CRAN (R 4.1.0)                           
 gdata              2.18.0   2017-06-06 [1] CRAN (R 4.1.0)                           
 gdsfmt             1.28.1   2021-09-16 [1] Bioconductor                             
 generics           0.1.1    2021-10-25 [1] CRAN (R 4.1.2)                           
 GenomeInfoDb       1.28.4   2021-09-09 [1] Bioconductor                             
 GenomeInfoDbData   1.2.6    2021-08-01 [1] Bioconductor                             
 GenomicRanges      1.44.0   2021-05-19 [1] Bioconductor                             
 ggplot2            3.3.5    2021-06-25 [1] CRAN (R 4.1.0)                           
 glue               1.4.2    2020-08-27 [1] CRAN (R 4.1.0)                           
 gmodels            2.18.1   2018-06-25 [1] CRAN (R 4.1.0)                           
 gridExtra          2.3      2017-09-09 [1] CRAN (R 4.1.0)                           
 gtable             0.3.0    2019-03-25 [1] CRAN (R 4.1.0)                           
 gtools             3.9.2    2021-06-06 [1] CRAN (R 4.1.0)                           
 HardyWeinberg      1.7.4    2021-11-26 [1] CRAN (R 4.1.2)                           
 hms                1.1.1    2021-09-26 [1] CRAN (R 4.1.2)                           
 htmltools          0.5.1.1  2021-01-22 [1] CRAN (R 4.1.0)                           
 httpuv             1.6.1    2021-05-07 [1] CRAN (R 4.1.0)                           
 igraph             1.2.6    2020-10-06 [1] CRAN (R 4.1.0)                           
 IRanges            2.26.0   2021-05-19 [1] Bioconductor                             
 KernSmooth         2.23-20  2021-05-03 [2] CRAN (R 4.1.0)                           
 knitr              1.36     2021-09-29 [1] CRAN (R 4.1.2)                           
 later              1.2.0    2021-04-23 [1] CRAN (R 4.1.0)                           
 lattice            0.20-44  2021-05-02 [2] CRAN (R 4.1.0)                           
 LearnBayes         2.15.1   2018-03-18 [1] CRAN (R 4.1.0)                           
 lifecycle          1.0.1    2021-09-24 [1] CRAN (R 4.1.2)                           
 magrittr           2.0.1    2020-11-17 [1] CRAN (R 4.1.0)                           
 MASS               7.3-54   2021-05-03 [2] CRAN (R 4.1.0)                           
 Matrix             1.3-3    2021-05-04 [2] CRAN (R 4.1.0)                           
 memoise            2.0.0    2021-01-26 [1] CRAN (R 4.1.0)                           
 mgcv               1.8-35   2021-04-18 [2] CRAN (R 4.1.0)                           
 mice               3.14.0   2021-11-24 [1] CRAN (R 4.1.2)                           
 mime               0.11     2021-06-23 [1] CRAN (R 4.1.0)                           
 munsell            0.5.0    2018-06-12 [1] CRAN (R 4.1.0)                           
 nlme               3.1-152  2021-02-04 [2] CRAN (R 4.1.0)                           
 nnet               7.3-16   2021-05-03 [2] CRAN (R 4.1.0)                           
 permute            0.9-5    2019-03-12 [1] CRAN (R 4.1.0)                           
 pillar             1.6.4    2021-10-18 [1] CRAN (R 4.1.2)                           
 pinfsc50           1.2.0    2020-06-03 [1] CRAN (R 4.1.0)                           
 pkgbuild           1.2.0    2020-12-15 [1] CRAN (R 4.1.0)                           
 pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 4.1.0)                           
 pkgload            1.2.1    2021-04-06 [1] CRAN (R 4.1.0)                           
 plyr               1.8.6    2020-03-03 [1] CRAN (R 4.1.0)                           
 prettyunits        1.1.1    2020-01-24 [1] CRAN (R 4.1.0)                           
 processx           3.5.2    2021-04-30 [1] CRAN (R 4.1.0)                           
 promises           1.2.0.1  2021-02-11 [1] CRAN (R 4.1.0)                           
 proxy              0.4-26   2021-06-07 [1] CRAN (R 4.1.0)                           
 ps                 1.6.0    2021-02-28 [1] CRAN (R 4.1.0)                           
 purrr              0.3.4    2020-04-17 [1] CRAN (R 4.1.0)                           
 R6                 2.5.1    2021-08-19 [1] CRAN (R 4.1.2)                           
 radiator           1.2.1    2021-12-12 [1] Github (thierrygosselin/radiator@9c92544)
 raster             3.4-13   2021-06-18 [1] CRAN (R 4.1.0)                           
 Rcpp               1.0.7    2021-07-07 [1] CRAN (R 4.1.0)                           
 RCurl              1.98-1.5 2021-09-17 [1] CRAN (R 4.1.1)                           
 readr              2.1.1    2021-11-30 [1] CRAN (R 4.1.2)                           
 remotes            2.4.0    2021-06-02 [1] CRAN (R 4.1.0)                           
 reshape2           1.4.4    2020-04-09 [1] CRAN (R 4.1.0)                           
 rlang              0.4.11   2021-04-30 [1] CRAN (R 4.1.0)                           
 rmarkdown          2.11     2021-09-14 [1] CRAN (R 4.1.2)                           
 rprojroot          2.0.2    2020-11-15 [1] CRAN (R 4.1.0)                           
 Rsolnp             1.16     2015-12-28 [1] CRAN (R 4.1.2)                           
 rstudioapi         0.13     2020-11-12 [1] CRAN (R 4.1.0)                           
 S4Vectors          0.30.2   2021-10-03 [1] Bioconductor                             
 scales             1.1.1    2020-05-11 [1] CRAN (R 4.1.0)                           
 SeqArray           1.32.0   2021-05-19 [1] Bioconductor                             
 seqinr             4.2-8    2021-06-09 [1] CRAN (R 4.1.0)                           
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 4.1.0)                           
 sf                 1.0-2    2021-07-26 [1] CRAN (R 4.1.0)                           
 shiny              1.6.0    2021-01-25 [1] CRAN (R 4.1.0)                           
 SNPRelate          1.26.0   2021-05-19 [1] Bioconductor                             
 sp                 1.4-5    2021-01-10 [1] CRAN (R 4.1.0)                           
 spData             0.3.10   2021-06-18 [1] CRAN (R 4.1.0)                           
 spdep              1.1-8    2021-05-23 [1] CRAN (R 4.1.0)                           
 stringi            1.7.3    2021-07-16 [1] CRAN (R 4.1.0)                           
 stringr            1.4.0    2019-02-10 [1] CRAN (R 4.1.0)                           
 testthat           3.0.4    2021-07-01 [1] CRAN (R 4.1.0)                           
 tibble             3.1.3    2021-07-23 [1] CRAN (R 4.1.0)                           
 tidyr              1.1.4    2021-09-27 [1] CRAN (R 4.1.2)                           
 tidyselect         1.1.1    2021-04-30 [1] CRAN (R 4.1.0)                           
 truncnorm          1.0-8    2018-02-27 [1] CRAN (R 4.1.2)                           
 tzdb               0.2.0    2021-10-27 [1] CRAN (R 4.1.2)                           
 units              0.7-2    2021-06-08 [1] CRAN (R 4.1.0)                           
 UpSetR             1.4.0    2019-05-22 [1] CRAN (R 4.1.2)                           
 usethis            2.0.1    2021-02-10 [1] CRAN (R 4.1.0)                           
 utf8               1.2.2    2021-07-24 [1] CRAN (R 4.1.0)                           
 vcfR             * 1.12.0   2020-09-01 [1] CRAN (R 4.1.0)                           
 vctrs              0.3.8    2021-04-29 [1] CRAN (R 4.1.0)                           
 vegan              2.5-7    2020-11-28 [1] CRAN (R 4.1.0)                           
 viridisLite        0.4.0    2021-04-13 [1] CRAN (R 4.1.0)                           
 vroom              1.5.7    2021-11-30 [1] CRAN (R 4.1.2)                           
 withr              2.4.3    2021-11-30 [1] CRAN (R 4.1.2)                           
 xfun               0.24     2021-06-15 [1] CRAN (R 4.1.0)                           
 xtable             1.8-4    2019-04-21 [1] CRAN (R 4.1.0)                           
 XVector            0.32.0   2021-05-19 [1] Bioconductor                             
 yaml               2.2.1    2020-02-01 [1] CRAN (R 4.1.0)                           
 zlibbioc           1.38.0   2021-05-19 [1] Bioconductor                             

[1] C:/Users/pfau/OneDrive/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.0/librar
[Final.recode.vcf.zip](https://github.com/thierrygosselin/radiator/files/7700170/Final.recode.vcf.zip)
[strata-frog.txt](https://github.com/thierrygosselin/radiator/files/7700194/strata-frog.txt)
y

**Comment by thierrygosselin** [comment]
Thanks Russel and sorry about the issue, I'll have a look at it less than a day.
Thierry

**Comment by thierrygosselin** [comment]
It's a problem reading the **freeBayes** VCF file, I'll see what I can do on my end.

**Comment by thierrygosselin** [comment]
@rspfau You have missing information on the last line of the VCF
Verify if it was generated in freeBayes (or by the name of the vcf, I'm assuming VCFTools)
Update radiator and re-open the issue if the problem persist

**Comment by thierrygosselin** [comment]
@rspfau You also have missing information for some samples (check the AD field of the VCF), I see this with VCF that are multi-allelic, with most of the VCF bi-allelic.

**Comment by rspfau** [comment]
This VCF file is the unedited output of the dDocent pipeline, which uses FreeBayes and VCFtools to call/filter SNPs. I'm not able to parse the complex VCF file to know what exactly is wrong with it, but are you saying that FreeBayes and/or VCFtools is outputting a faulty VCF file? 
https://www.ddocent.com/UserGuide/#snp-filtering

**Comment by rspfau** [comment]
Also, I'm on my work computer now and am unable to download radiator in RStudio, I think, because our university has really high security. Do you have suggestions?
https://support.rstudio.com/hc/en-us/articles/206827897-Secure-Package-Downloads-for-R

> devtools::install_github("thierrygosselin/radiator")
Downloading GitHub repo thierrygosselin/radiator@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  internet routines cannot be loaded
