### ISSUE TITLE
filter_rad error: Column `READ_DEPTH` is a `SeqVarDataList` object.

### ISSUE THREAD

**Issue by mruggeri55** [thierrygosselin/radiator#163]
Hi Thierry, I am trying to use the filter_rad function but I am getting an error when sourcing the read depth as it is stored as a SeqVarDatalist object. It seems like I could probably just coerce the read depth into a vector, but I am not sure at what point in the pipeline that I am getting this error. My code, errors, and session information are below.

data <- radiator::filter_rad(
  data = 'angsd/angsdput.vcf',
  strata = meta_all, 
  output = "genind"
)

################################################################################
################################################################################
Execution date@time: 20220921@0904
Folder created: filter_rad_20220921@0904
Function call and arguments stored in: radiator_filter_rad_args_20220921@0904.tsv
File written: random.seed (948719)                                  
Filters parameters file generated: filters_parameters_20220921@0904.tsv
                                                                    
Reading VCF... 

Data summary: 
    number of samples: 316
    number of markers: 7825
                                                                    
Generating individual stats...
Error:
! All columns in a tibble must be vectors.
✖ Column `READ_DEPTH` is a `SeqVarDataList` object.
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 17 sec
############################# completed filter_rad #############################

sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SeqArray_1.36.3  SNPRelate_1.30.1 gdsfmt_1.32.0    radiator_1.2.2   vcfR_1.13.0

**Comment by thierrygosselin** [comment]
Hi @ mruggeri55

This might be really specific to your angsd vcf. I don't have a lot of those. You might sharing the vcf or a subsample of it via email ? 

I'll re-open the issue if I have something to work with.
