### ISSUE TITLE
Genomic converter error 'no more individuals in your data'

### ISSUE THREAD

**Issue by esnielsen** [thierrygosselin/radiator#169]
Hi there, 

I am trying to convert a plink file to a bayescan file, using the following code:

radiator::detect_genomic_format(data = "ALL_2_.bin.bed")

radiator::summary_strata("ALL_2_strata.tsv")

lottia <- genomic_converter(
                   data = "ALL_2_bin.bed", strata = "ALL_2_strata.tsv",
                   output = c("bayescan"))

And I get the following error: "Error in `join_strata()`: ! No more individuals in your data, check data and strata ID names.."

This error looks like it can't join the strata and input data because they have unequal number of individuals, but the output below shows that they both have 553 individuals, so not sure what else it could be?

Output:

[1] "plink.bed.file"
Number of strata: 19
Number of individuals: 553

Number of ind/strata:
KR = 30
FR = 30
BB = 30
DB = 30
HP = 30
CR = 30
SB = 29
VN = 30
GP = 30
CA = 30
WA = 30
IP = 30
SH = 30
SC = 30
CB = 30
PB = 19
SR = 29
BT = 29
BA = 27

Number of duplicate id: 0
################################################################################
################################################################################
Execution date@time: 20221117@0638
Folder created: -3564_radiator_genomic_converter_20221117@0638
Function call and arguments stored in: radiator_genomic_converter_args_20221117@0638.tsv
Filters parameters file generated: filters_parameters_20221117@0638.tsv

Importing data: plink.bed.file
Reading PLINK bed file...

Data summary: 
    number of samples: 553
    number of markers: 908948
Error in `join_strata()`:
! No more individuals in your data, check data and strata ID names...
Backtrace:
     x
  1. +-radiator::genomic_converter(...)
  2. | \-radiator::tidy_genomic_data(...)
  3. |   \-radiator::tidy_plink(...)
  4. |     \-radiator::read_plink(...)
  5. |       \-... %>% ...
  6. +-dplyr::mutate(...)
  7. +-dplyr::left_join(...)
  8. +-dplyr:::left_join.data.frame(...)
  9. | \-dplyr::auto_copy(x, y, copy = copy)
 10. |   +-dplyr::same_src(x, y)
 11. |   \-dplyr:::same_src.data.frame(x, y)
 12. |     \-base::is.data.frame(y)
 13. +-join_strata(individuals, strata, verbose = verbose) %>% ...
 14. +-dplyr::mutate(., FILTERS = "whitelist")
 15. \-radiator::join_strata(individuals, strata, verbose = verbose)
 16.   \-rlang::abort("No more individuals in your data, check data and strata ID names...")

Computation time, overall: 55 sec

Computation time, overall: 56 sec
######################### completed genomic_converter ##########################
Execution halted

I would really appreciate any input you have- thanks in advance!

**Comment by thierrygosselin** [comment]
Hi Erica, 
It's likely a problem of individual naming inside the plink or the strata file, but I won't know for sure until I have the data to run the function and reproduce the error. You mind sharing relevant files over email ?

Best
Thierry

**Comment by thierrygosselin** [comment]
I don't see the strata file

**Comment by thierrygosselin** [comment]
Do you have the corresponding `fam` and `bim` files that goes with the `bed` file ?

**Comment by esnielsen** [comment]
Hi, yes all the files should be here: https://www.dropbox.com/scl/fo/dmh7l3ewfyr3wmvn1t78w/h?dl=0&rlkey=n913sdaqiskp57ahm0ivxjow6 <https://www.dropbox.com/scl/fo/dmh7l3ewfyr3wmvn1t78w/h?dl=0&rlkey=n913sdaqiskp57ahm0ivxjow6>

**Comment by thierrygosselin** [comment]
ok good I have that I need

**Comment by thierrygosselin** [comment]
I was able to reproduce the bug, will have a fix this afternoon

**Comment by thierrygosselin** [comment]
Found the problem

I don't know the origin of this plink file (how it was generated), but the names inside the `bed` and `fam` files don't match. Or it's `SeqArray::seqBED2GDS` use under the hood that's not working.

Same goes with the strata file which is completely different than the fam file naming scheme.

Some advice on naming strategy, [here](http://thierrygosselin.github.io/stackr/articles/stackr.html#the-art-of-naming-your-samples), but it doesn't have to be that way to work inside radiator.

once this is sorted out try:

```
test1 <- radiator::read_plink(data = "ALL_2.bin.bed")
```
if it's not working, don't bother trying `genomic_converter`, 
re-open the issue if you're still having problems
