### ISSUE TITLE
Error in file(con, "r") : cannot open the connection

### ISSUE THREAD

**Issue by Glaucidium** [thierrygosselin/radiator#170]
Hi Thierry
I´m having a problem while running radiator::filter_rad and radiator::genomic_converter (the same issue) 

################################################################################
################################################################################
Execution date@time: 20230111@1845
Folder created: filter_rad_20230111@1845
Function call and arguments stored in: radiator_filter_rad_args_20230111@1845.tsv
File written: random.seed (740211)
Filters parameters file generated: filters_parameters_20230111@1845.tsv
Error in file(con, "r") : cannot open the connection

Computation time, overall: 3 sec
############################# completed filter_rad #############################

I am using the "sunflower.vcf" you used in the FST comparisson

The script was: 
data <- radiator::genomic_converter(
    data = "sunflower.vcf",
  strata = "sunflower.strata.tsv", 
  output = c("genind", "stockr"),
  parallel.core = 1,
  filename = "a"
)

> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31 ucrt)
 os       Windows 10 x64 (build 22000)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  Spanish_Argentina.utf8
 ctype    Spanish_Argentina.utf8
 tz       America/Buenos_Aires
 date     2023-01-11
 rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────
 package          * version  date (UTC) lib source
 assertthat         0.2.1    2019-03-21 [1] CRAN (R 4.2.2)
 backports          1.4.1    2021-12-13 [1] CRAN (R 4.2.0)
 BiocGenerics       0.44.0   2022-11-01 [1] Bioconductor
 BiocManager        1.30.19  2022-10-25 [1] CRAN (R 4.2.2)
 Biostrings         2.66.0   2022-11-01 [1] Bioconductor
 bit                4.0.5    2022-11-15 [1] CRAN (R 4.2.2)
 bit64              4.0.5    2020-08-30 [1] CRAN (R 4.2.2)
 bitops             1.0-7    2021-04-24 [1] CRAN (R 4.2.0)
 broom              1.0.2    2022-12-15 [1] CRAN (R 4.2.2)
 cachem             1.0.6    2021-08-19 [1] CRAN (R 4.2.2)
 callr              3.7.3    2022-11-02 [1] CRAN (R 4.2.2)
 cli                3.5.0    2022-12-20 [1] CRAN (R 4.2.2)
 colorspace         2.0-3    2022-02-21 [1] CRAN (R 4.2.2)
 crayon             1.5.2    2022-09-29 [1] CRAN (R 4.2.2)
 DBI                1.1.3    2022-06-18 [1] CRAN (R 4.2.2)
 devtools           2.4.5    2022-10-11 [1] CRAN (R 4.2.2)
 digest             0.6.31   2022-12-11 [1] CRAN (R 4.2.2)
 dplyr              1.0.10   2022-09-01 [1] CRAN (R 4.2.2)
 ellipsis           0.3.2    2021-04-29 [1] CRAN (R 4.2.2)
 fansi              1.0.3    2022-03-24 [1] CRAN (R 4.2.2)
 fastmap            1.1.0    2021-01-25 [1] CRAN (R 4.2.2)
 fs                 1.5.2    2021-12-08 [1] CRAN (R 4.2.2)
 gdsfmt             1.34.0   2022-11-01 [1] Bioconductor
 generics           0.1.3    2022-07-05 [1] CRAN (R 4.2.2)
 GenomeInfoDb       1.34.6   2023-01-03 [1] Bioconductor
 GenomeInfoDbData   1.2.9    2023-01-05 [1] Bioconductor
 GenomicRanges      1.50.2   2022-12-27 [1] Bioconductor
 ggplot2            3.4.0    2022-11-04 [1] CRAN (R 4.2.2)
 glue               1.6.2    2022-02-24 [1] CRAN (R 4.2.2)
 gridExtra          2.3      2017-09-09 [1] CRAN (R 4.2.2)
 gtable             0.3.1    2022-09-01 [1] CRAN (R 4.2.2)
 HardyWeinberg      1.7.5    2022-05-07 [1] CRAN (R 4.2.2)
 hms                1.1.2    2022-08-19 [1] CRAN (R 4.2.2)
 htmltools          0.5.4    2022-12-07 [1] CRAN (R 4.2.2)
 htmlwidgets        1.6.1    2023-01-07 [1] CRAN (R 4.2.2)
 httpuv             1.6.7    2022-12-14 [1] CRAN (R 4.2.2)
 IRanges            2.32.0   2022-11-01 [1] Bioconductor
 later              1.3.0    2021-08-18 [1] CRAN (R 4.2.2)
 lattice            0.20-45  2021-09-22 [2] CRAN (R 4.2.2)
 lifecycle          1.0.3    2022-10-07 [1] CRAN (R 4.2.2)
 magrittr           2.0.3    2022-03-30 [1] CRAN (R 4.2.2)
 memoise            2.0.1    2021-11-26 [1] CRAN (R 4.2.2)
 mice               3.15.0   2022-11-19 [1] CRAN (R 4.2.2)
 mime               0.12     2021-09-28 [1] CRAN (R 4.2.0)
 miniUI             0.1.1.1  2018-05-18 [1] CRAN (R 4.2.2)
 munsell            0.5.0    2018-06-12 [1] CRAN (R 4.2.2)
 nnet               7.3-18   2022-09-28 [2] CRAN (R 4.2.2)
 pillar             1.8.1    2022-08-19 [1] CRAN (R 4.2.2)
 pkgbuild           1.4.0    2022-11-27 [1] CRAN (R 4.2.2)
 pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 4.2.2)
 pkgload            1.3.2    2022-11-16 [1] CRAN (R 4.2.2)
 plyr               1.8.8    2022-11-11 [1] CRAN (R 4.2.2)
 prettyunits        1.1.1    2020-01-24 [1] CRAN (R 4.2.2)
 processx           3.8.0    2022-10-26 [1] CRAN (R 4.2.2)
 profvis            0.3.7    2020-11-02 [1] CRAN (R 4.2.2)
 promises           1.2.0.1  2021-02-11 [1] CRAN (R 4.2.2)
 ps                 1.7.2    2022-10-26 [1] CRAN (R 4.2.2)
 purrr              1.0.0    2022-12-20 [1] CRAN (R 4.2.2)
 R6                 2.5.1    2021-08-19 [1] CRAN (R 4.2.2)
 radiator           1.2.4    2023-01-05 [1] Github (thierrygosselin/radiator@982b790)
 Rcpp               1.0.9    2022-07-08 [1] CRAN (R 4.2.2)
 RCurl              1.98-1.9 2022-10-03 [1] CRAN (R 4.2.2)
 readr              2.1.3    2022-10-01 [1] CRAN (R 4.2.2)
 remotes            2.4.2    2021-11-30 [1] CRAN (R 4.2.2)
 rlang              1.0.6    2022-09-24 [1] CRAN (R 4.2.2)
 Rsolnp             1.16     2015-12-28 [1] CRAN (R 4.2.2)
 rstudioapi         0.14     2022-08-22 [1] CRAN (R 4.2.2)
 S4Vectors          0.36.1   2022-12-05 [1] Bioconductor
 scales             1.2.1    2022-08-20 [1] CRAN (R 4.2.2)
 SeqArray           1.38.0   2022-11-01 [1] Bioconductor
 sessioninfo        1.2.2    2021-12-06 [1] CRAN (R 4.2.2)
 shiny              1.7.4    2022-12-15 [1] CRAN (R 4.2.2)
 SNPRelate          1.32.1   2022-12-14 [1] Bioconductor
 stringi            1.7.8    2022-07-11 [1] CRAN (R 4.2.1)
 stringr            1.5.0    2022-12-02 [1] CRAN (R 4.2.2)
 tibble             3.1.8    2022-07-22 [1] CRAN (R 4.2.2)
 tidyr              1.2.1    2022-09-08 [1] CRAN (R 4.2.2)
 tidyselect         1.2.0    2022-10-10 [1] CRAN (R 4.2.2)
 truncnorm          1.0-8    2018-02-27 [1] CRAN (R 4.2.2)
 tzdb               0.3.0    2022-03-28 [1] CRAN (R 4.2.2)
 UpSetR             1.4.0    2019-05-22 [1] CRAN (R 4.2.2)
 urlchecker         1.0.1    2021-11-30 [1] CRAN (R 4.2.2)
 usethis            2.1.6    2022-05-25 [1] CRAN (R 4.2.2)
 utf8               1.2.2    2021-07-24 [1] CRAN (R 4.2.2)
 vctrs              0.5.1    2022-11-16 [1] CRAN (R 4.2.2)
 vroom              1.6.0    2022-09-30 [1] CRAN (R 4.2.2)
 withr              2.5.0    2022-03-03 [1] CRAN (R 4.2.2)
 xtable             1.8-4    2019-04-21 [1] CRAN (R 4.2.2)
 XVector            0.38.0   2022-11-01 [1] Bioconductor
 zlibbioc           1.44.0   2022-11-01 [1] Bioconductor

 [1] C:/Users/mjrod/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.2/library

──

I also open RStudio as admin, same problem.

**Comment by thierrygosselin** [comment]
@Glaucidium I cannot reproduce the error you're experiencing with newer version I'm working on for the past month.

Try reinstalling radiator with latest version 1.2.5 (will be updated in a few hours)
Re-run the command and re-open issue if you are still having problem

Best
Thierry
