### ISSUE TITLE
genomic_converter object 'MARKERS' from genind

### ISSUE THREAD

**Issue by BrennaF** [thierrygosselin/radiator#18]
Hi Thierry,

I'm having a similar problem as that reported earlier by Tom Jenkins; namely that I get an "Evaluation error: object 'MARKERS' not found" when using genomic_converter.

In my case, my data (attached here as "foo2.csv") are brought in via df2genind. These are simulated SNP data (100 SNPs for 100 individuals) recoded from allele counts of 0/1/2 to 110110/100110/100100. The goal is to impute NAs using RF in radiator. Note that this code pasted below was working in radiator v. 0.0.6; I'm now running 0.0.10.

Based on the solutions for Tom's data, I tried changing the @loc.fac slot so each column was unique (e.g. 0.1 0.2 1.1 1.2...) but this didn't help. Any ideas? Thanks!! -Brenna

#################################

> foo.genind <- df2genind(foo2, ncode = 3, NA.char = NA, ploidy = 2)

> foo.genind@pop <- as.factor(rep("PO1", length(sets.length[x]))) 

> foo.genind

/// GENIND OBJECT /////////

 // 100 individuals; 100 loci; 200 alleles; size: 132.5 Kb

 // Basic content
   @tab:  100 x 200 matrix of allele counts
   @loc.n.all: number of alleles per locus (range: 2-2)
   @loc.fac: locus factor for the 200 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 2-2)
   @type:  codom
   @call: df2genind(X = foo2, ncode = 3, NA.char = NA, ploidy = 2)

 // Optional content
   @pop: population of each individual (group size range: 1-1)
> foo.genind@loc.fac
  [1] 0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9  10
 [22] 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 19 20 20
 [43] 21 21 22 22 23 23 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31
 [64] 31 32 32 33 33 34 34 35 35 36 36 37 37 38 38 39 39 40 40 41 41
 [85] 42 42 43 43 44 44 45 45 46 46 47 47 48 48 49 49 50 50 51 51 52
[106] 52 53 53 54 54 55 55 56 56 57 57 58 58 59 59 60 60 61 61 62 62
[127] 63 63 64 64 65 65 66 66 67 67 68 68 69 69 70 70 71 71 72 72 73
[148] 73 74 74 75 75 76 76 77 77 78 78 79 79 80 80 81 81 82 82 83 83
[169] 84 84 85 85 86 86 87 87 88 88 89 89 90 90 91 91 92 92 93 93 94
[190] 94 95 95 96 96 97 97 98 98 99 99
100 Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ... 99

> imp.rf.stackr <- genomic_converter(data=foo.genind, output="tidy", imputation.method="rf", hierarchical.levels="global", verbose = TRUE)
#######################################################################
#######################################################################
Function arguments and values:
Working directory: D:/6-NAproject/imputation/filter/temp/temp1
Input file: from global environment
Strata: no
Population levels: no
Population labels: no
Output format(s): tidy, tidy
Filename prefix: no
Filters: 
Blacklist of individuals: no
Blacklist of genotypes: no
Whitelist of markers: no
monomorphic.out: TRUE
snp.ld: no
common.markers: TRUE
max.marker: no
pop.select: no
maf.thresholds: no

Imputations options:
imputation.method: rf
hierarchical.levels: global

parallel.core: 7

#######################################################################

Importing data

Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'MARKERS' not found.

[foo2.zip](https://github.com/thierrygosselin/radiator/files/1900588/foo2.zip)

**Comment by thierrygosselin** [comment]
Hi Brenna, 

I was not able to run your code, I get this error:
`Error in is.factor(x) : object 'sets.length' not found`

Where is `sets.length` from ?
If you show me the fix, I'll try to read genind object differently (re-open the issue by replying):

Otherwise, you can do this:

**Import data and load radiator** 
```
library(radiator)
data <- suppressWarnings(readr::read_csv(
  file = "foo2.csv",
  col_names = TRUE, col_types = readr::cols(.default = readr::col_character()))) %>%
  dplyr::mutate(POP_ID = rep("POP1", n())) %>%
  dplyr::select(POP_ID, INDIVIDUALS = X1, dplyr::everything(.)) %>%
  dplyr::mutate_all(.tbl = ., .funs = tidyr::replace_na, replace = "000000")
```

**Generate the tidy data**
```
tidy.data <- radiator::tidy_genomic_data(data)
```

**test genind**
```
genind.data <- radiator::write_genind(tidy.data)
genind.data
```


**Or, do all this at the same time as testing the imputations**
2 ways: through radiator::genomic converter or grur::grur_imputations

```
imp.rf <- radiator::genomic_converter(
  data = data,
  output = "genind", 
  imputation.method = "rf",
  hierarchical.levels = "global", 
  verbose = TRUE)
```

```
names(imp.rf)
[1] "genind.no.imputation" "genind.imputed"      
[3] "tidy.data"            "tidy.data.imp"
```

So here you have both imputed and non imputed: tidy data and genind objects.

**Recover them separately:**
```
tidy.data <- imp.rf$tidy.data
tidy.data.imp <- imp.rf$tidy.data.imp
genind.no.imputation <- imp.rf$genind.no.imputation
genind.imputed <- imp.rf$genind.imputed
```

You have simulated data with NA's ? Simulated on what?

Early next week I have a grur update to evaluate imputation accuracy and other tools...
Cheers
Thierry

**Comment by thierrygosselin** [comment]
I'm actually reopening it ;)

1. To make the code fully reproducible, show how you import `foo2` in R ?

I used :

```
foo2 <- suppressWarnings(readr::read_csv(
  file = "foo2.csv",
  col_names = TRUE, col_types = readr::cols(.default = readr::col_character())))
```

2. `foo.genind@pop <- as.factor(rep("PO1", 100))` in your code fix the problem on my end.

But... when I run some checks, I get weird results:

```
foo.genind@tab # gives weird weird results
```

- You should have the marker/locus name then a `.` with the alleles you report using: `110` and `100`
- not the case on my end Which is not the case, the first columns of the matrix are `X1.1`, `X1.2`, `...`
- the columns at the end are fine

3. `foo.genind@loc.n.all` and `adegenet::nLoc(foo.genind)`
Shows that the individual column is considered as locus, which explains why the weird results above.

do your get the same results?

Best
Thierry

**Comment by BrennaF** [comment]
I'm sorry about that Thierry - I didn't check the data file after I wrote it out.

Read it in this way and it should recreate the problem:

foo2 <- read.csv("foo2.csv", check.names=F)
foo2 <- foo2 [,-1]
foo2 [, ] <- lapply(foo2 [, ], as.character)
foo.genind <- df2genind(foo2, ncode = 3, NA.char = NA, ploidy = 2)
foo.genind@pop <- as.factor(rep("PO1", length(sets.length[x]))) 

Let me know if it is still not working!

**Comment by thierrygosselin** [comment]
Hi Brenna, the latest commit `6f57bbc` fixes the issue (it was working properly with multi allelic datasets, but the all the colours of genind were not accounted for when using biallelic datasets..)

Thanks for reporting !
Thierry
