### ISSUE TITLE
Error with genomic_converter

### ISSUE THREAD

**Issue by zcebeci** [thierrygosselin/radiator#180]
Dear Thierry,

I am trying to convert a toy example data in PLINK bed format to VCF and genlight. It works, creates directories and then stops with Error in file(con, "r") . Below please find my R codes and the relevant bug report.

> radiator::genomic_converter(
+  data = " example1.bed",
+  strata = NULL, #"example_strata.tsv",
+  #output = c("vcf", "genlight", "gtypes"),
+  output = c("gds"),
+  filename = fn,
+  parallel.core = parallel::detectCores() - 1,
+  verbose = TRUE
+ ) 
################################################################################
################################################################################
Execution date@time: 20231016@1720
Folder created: 04_radiator_genomic_converter_20231016@1720

[1mwrote[0m [32m233.00B[0m in [36m 0s[0m, [32m6.30MB/s[0m
                                                                    
[1mwrote[0m [32m2.15GB[0m in [36m 0s[0m, [32m2.15GB/s[0m
                                                                    
Function call and arguments stored in: radiator_genomic_converter_args_20231016@1720.tsv
Filters parameters file generated: filters_parameters_20231016@1720.tsv
Error in file(con, "r") : bağlantı açılamadı

Computation time, overall: 0 sec
######################### completed genomic_converter ##########################
> rlang::last_error()
Hata: Can't show last error because no error was recorded yet

Thank you in advance for your reply.
All the best

**Comment by thierrygosselin** [comment]
re-open if you're still using
