### ISSUE TITLE
error Sexy_markers operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by kasmiyassin** [thierrygosselin/radiator#183]
I have a VCF file generate from Stacks2, and I prepared my STRAT fille as described but I recieve all time this error:
> Error  in SeqArray::seqGetData(data, "annotation/format/DP")$data :
>   $ operator is invalid for atomic vectors

> ################################### RESULTS ####################################
> 
> Filter short ld threshold: mac
> Number of individuals / strata / chrom / locus / SNP:
>     Before: 25 / 2 / 339 / 23310 / 51363
>     Blacklisted: 0 / 0 / 0 / 0 / 28053
>     After: 25 / 2 / 339 / 23310 / 23310
> 
> Do you want to continue filtering using long distance ld  ? (y/n):
> n
> 
> Computation time, overall: 345 sec
> ############################# completed filter_ld ##############################
> 
> 
> Sex-ratio (F/M): 0.56
> Error  in SeqArray::seqGetData(data, "annotation/format/DP")$data :
>   $ operator is invalid for atomic vectors
> 
> Computation time, overall: 497 sec
> ############################ completed sexy_markers ############################
> 

when I use the commands

> data  <- read_vcf(data = "/populations.snps.vcf", 
                  strata = "/info_sex.txt")
> strata <- read.delim("/info_sex.txt")
> radiator::summary_strata(strata)

Then the command 

> sex.markers <- radiator::sexy_markers(
    data = data,
    strata = strata)

I tested also the command

> data  <- read_vcf(data = "/populations.snps.vcf")
> strata <- read.delim("/info_sex.txt")
> radiator::summary_strata(strata)

Then the command 
> sex.markers <- radiator::sexy_markers(
>   data = data,
>    strata = strata)

but I got the same error.

 My strata looks like

> INDIVIDUALS	STRATA
> IND-1	POP_1
> IND-2	POP_2
> IND-3	POP_1
> IND-4	POP_2

Can anyone help me to solve this issue please?

**Comment by thierrygosselin** [comment]
Could you send by email the necessary files to reproduce the error please.
