### ISSUE TITLE
Error in "generate_id_stats"

### ISSUE THREAD

**Issue by pipehorse** [thierrygosselin/radiator#184]
Dear thierrygosselin,

I installed "grur" and "radiator" in R in my Ubuntu environment and I used filter_rad successfully same file before. But when i used "missing_visualization" to check my missing data visually, error was occured.

error message "Error: 'generate_id_stats' is not an exported object from 'namespace:radiator'"was shown again and again.

This error looks same issues which is not solved yet of issue at Grur "https://github.com/thierrygosselin/grur/issues/16"

I use 1.3.0 version of radiator and 0.1.4 version of grur

The entire output I got is below

> test4<-missing_visualization(data="populations.snps.vcf",strata="my.strata.tsv")
################################################################################
################################################################################
Execution date/time: 20240325@1426

missing_visualization function call arguments:
    data = populations.snps.vcf
    strata = my.strata.tsv
    strata.select = POP_ID
    distance.method = euclidean
    ind.missing.geno.threshold = 2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90
    filename = NULL
    parallel.core = 7
    write.plot = TRUE

Default "..." arguments assigned in missing_visualization:
    path.folder = NULL

Folder created: missing_visualization_20240325@1426
File written: grur_missing_visualization_data_args_20240325@1426.tsv

Importing data
✔ Reading VCF... you might have time for an espresso! [1m 1.4s]
                                                                                                         
Cleaning VCF
                                                                    
Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 4 / 25245 / 54184
                                                                    
Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 7 / 36175 / 83056
                                                                    
VCF info:
Number of chromosome/contig/scaffold: 105
Number of locus: 257576
Number of markers: 541867
Number of strata: 6
Number of individuals: 288

Number of ind/strata:
SEW = 48
GTL = 55
LEM = 47
STR = 41
FIN = 48
GEL = 49

Number of duplicate id: 0
radiator Genomic Data Structure (GDS) file: radiator_20240325@1426.gds
Error: 'generate_id_stats' is not an exported object from 'namespace:radiator'

Computation time, overall: 150 sec

**Comment by thierrygosselin** [comment]
That internal function is deprecated and no longer used, try uninstalling radiator and grur and reinstalling it.

Not that it matters but it was replaced by `generate_stats` that handle both individuals and markers stats.

Re-open the issue if you're still experiencing a problem.
