### ISSUE TITLE
Old version repository

### ISSUE THREAD

**Issue by miqueiasferrao** [thierrygosselin/radiator#19]
Dear Thierry,

four months ago I used radiator version 0.6 to filtered my dart data. In this version, the output (e.g estructure, genepop, arlequin) files had SNPs coded as 012. Now I have to refiltering my data but in the version 0.10 the SNPs are coded as 1234.
Is there a repository with old versions of Radiator? if not, is there any command/function to get output files coded as 012?

Thanks in advance

**Comment by thierrygosselin** [comment]
Hi,
the versions and different commits are found on GitHub.
the different versions are also found on Zenodo.

depending on the function used, navigate to it and you'll see a history button.

The change was documented:
The output with `1 and 2` in structure, genepop, arlequin was updated to make it easier to know what was the nucleotide used.

**Before with the 1 and 2**
* `1` and `2` was used for the 2 observed alleles in biallelic dataset...
* to know which nucleotide the`1` and `2` meant you had to check with the REF and ALT allele in the VCF

**Now with 1234**
* is for the nucleotide: `A, C, G, T` 
* for biallelic dataset, you will still have only 2 numbers.
* e.g. your genotype for biallelic marker A and id 1 is `001004`: you know that the 2 alleles are `A` and `T`. 

What's your input file ? A vcf ?
Do you still have the tidy data set?

Best
Thierry

**Comment by thierrygosselin** [comment]
reopen the issue if you're still having problems

**Comment by miqueiasferrao** [comment]
Hi Thierry,
Sorry for the answer delayed. Thank you so much for your support.
I was thinking about the 1234 format and I agree with you, and it's too much more informative.
I've worried about how some packages behavior with this format, but now I had the same results for both formats (it's not a surprise - but these genomic analyses are still brand new to me).

Thanks again,

Cheers,
Miquéias
