### ISSUE TITLE
detect_duplicate_genomes 

### ISSUE THREAD

**Issue by laiajulianamu** [thierrygosselin/radiator#192]
Dear Thierry,

I am running my dataset on a Mac, but for some reason, the process stops at the duplicate genome filter.

Execution date@time: 20240905@1842
File written: radiator_detect_mixed_genomes_args_20240905@1842.tsv  
Calculating heterozygosity statistics                              
Generating plots                                                    

The greatest value of a picture is when it forces us
to notice what we never expected to see.

John W. Tukey. Exploratory Data Analysis. 1977.

Inspect plots and tables in folder created...
    Do you want to exclude individuals based on heterozygosity ? (y/n):
y
    Enter the min value for ind.heterozygosity.threshold argument (0 turns off):
0.80
    Enter the max value for ind.heterozygosity.threshold argument (1 turns off):
0.98
Filter individual's heterozygosity: 649 individual(s) blacklisted
################################### RESULTS ####################################
Detect mixed genomes: 0.8 0.98
Number of individuals / strata / chrom / locus / SNP:
    Before: 649 / 6 / 1 / 21089 / 21089
    Blacklisted: 649 / 6 / 0 / 0 / 0
    After: 0 / 0 / 1 / 21089 / 21089
                                                                   
Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0

Computation time, overall: 22 sec
################################################################################
################################################################################
Execution date@time: 20240905@1842
Function call and arguments stored in a file
File written: radiator_detect_duplicate_genomes_args_20240905@1842.tsv
File written: random.seed (791874)                                  
Calculating manhattan distances between individuals...              
Error in .InitFile2(cmd = "Identity-By-State (IBS) analysis on genotypes:",  :
  There is no SNP!
In addition: Warning messages:
1: There was 1 warning in `dplyr::mutate()`.
ℹ In argument: `WHITELISTED_MARKERS = purrr::map_int(...)`.
Caused by warning:
! Using one column matrices in `filter()` was deprecated in dplyr
  1.1.0.
ℹ Please use one dimensional logical vectors instead.
ℹ The deprecated feature was likely used in the radiator package.
  Please report the issue at
  <https://github.com/thierrygosselin/radiator/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning
was generated.
2: Removed 2 rows containing missing values or values outside the scale
range (`geom_hline()`).
3: Removed 2 rows containing missing values or values outside the scale
range (`geom_hline()`).
4: In min(x, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
5: In max(x, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf

Computation time, overall: 0 sec
###################### completed detect_duplicate_genomes ######################

Computation time, overall: 567 sec
############################# completed filter_rad #############################

Session info ────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.1 (2024-06-14)
 os       macOS Sonoma 14.6.1
 system   x86_64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Guayaquil
 date     2024-09-05
 rstudio  2024.04.2+764 Chocolate Cosmos (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────
 package          * version    date (UTC) lib source
 backports          1.5.0      2024-05-23 [1] CRAN (R 4.4.0)
 BiocGenerics       0.50.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
 BiocManager        1.30.23    2024-05-04 [1] CRAN (R 4.4.0)
 Biostrings         2.72.1     2024-06-02 [1] Bioconductor 3.19 (R 4.4.0)
 bit                4.0.5      2022-11-15 [1] CRAN (R 4.4.0)
 bit64              4.0.5      2020-08-30 [1] CRAN (R 4.4.0)
 boot               1.3-30     2024-02-26 [1] CRAN (R 4.4.1)
 broom              1.0.6      2024-05-17 [1] CRAN (R 4.4.0)
 cachem             1.1.0      2024-05-16 [1] CRAN (R 4.4.0)
 cli                3.6.2      2023-12-11 [1] CRAN (R 4.4.0)
 codetools          0.2-20     2024-03-31 [1] CRAN (R 4.4.1)
 colorspace         2.1-0      2023-01-23 [1] CRAN (R 4.4.0)
 crayon             1.5.2      2022-09-29 [1] CRAN (R 4.4.0)
 curl               5.2.1      2024-03-01 [1] CRAN (R 4.4.0)
 data.table         1.15.4     2024-03-30 [1] CRAN (R 4.4.0)
 devtools         * 2.4.5.9000 2024-06-17 [1] Github (r-lib/devtools@c3fa3df)
 digest             0.6.35     2024-03-11 [1] CRAN (R 4.4.0)
 dplyr              1.1.4      2023-11-17 [1] CRAN (R 4.4.0)
 ellipsis           0.3.2      2021-04-29 [1] CRAN (R 4.4.0)
 fansi              1.0.6      2023-12-08 [1] CRAN (R 4.4.0)
 farver             2.1.2      2024-05-13 [1] CRAN (R 4.4.0)
 fastmap            1.2.0      2024-05-15 [1] CRAN (R 4.4.0)
 foreach            1.5.2      2022-02-02 [1] CRAN (R 4.4.0)
 fs                 1.6.4      2024-04-25 [1] CRAN (R 4.4.0)
 fst                0.9.8      2022-02-08 [1] CRAN (R 4.4.0)
 fstcore          * 0.9.18     2023-12-02 [1] CRAN (R 4.4.0)
 gdsfmt           * 1.40.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
 generics           0.1.3      2022-07-05 [1] CRAN (R 4.4.0)
 GenomeInfoDb       1.40.1     2024-05-24 [1] Bioconductor 3.19 (R 4.4.0)
 GenomeInfoDbData   1.2.12     2024-06-17 [1] Bioconductor
 GenomicRanges      1.56.1     2024-06-12 [1] Bioconductor 3.19 (R 4.4.1)
 ggplot2            3.5.1      2024-04-23 [1] CRAN (R 4.4.0)
 glmnet             4.1-8      2023-08-22 [1] CRAN (R 4.4.0)
 glue               1.7.0      2024-01-09 [1] CRAN (R 4.4.0)
 gridExtra          2.3        2017-09-09 [1] CRAN (R 4.4.0)
 gtable             0.3.5      2024-04-22 [1] CRAN (R 4.4.0)
 HardyWeinberg      1.7.8      2024-04-06 [1] CRAN (R 4.4.0)
 hms                1.1.3      2023-03-21 [1] CRAN (R 4.4.0)
 httr               1.4.7      2023-08-15 [1] CRAN (R 4.4.0)
 IRanges            2.38.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
 iterators          1.0.14     2022-02-05 [1] CRAN (R 4.4.0)
 jomo               2.7-6      2023-04-15 [1] CRAN (R 4.4.0)
 jsonlite           1.8.8      2023-12-04 [1] CRAN (R 4.4.0)
 labeling           0.4.3      2023-08-29 [1] CRAN (R 4.4.0)
 lattice            0.22-6     2024-03-20 [1] CRAN (R 4.4.1)
 lifecycle          1.0.4      2023-11-07 [1] CRAN (R 4.4.0)
 lme4               1.1-35.3   2024-04-16 [1] CRAN (R 4.4.0)
 magrittr           2.0.3      2022-03-30 [1] CRAN (R 4.4.0)
 MASS               7.3-61     2024-06-13 [1] CRAN (R 4.4.0)
 Matrix             1.7-0      2024-04-26 [1] CRAN (R 4.4.1)
 matrixStats      * 1.4.0      2024-09-04 [1] CRAN (R 4.4.1)
 memoise            2.0.1      2021-11-26 [1] CRAN (R 4.4.0)
 mice               3.16.0     2023-06-05 [1] CRAN (R 4.4.0)
 minqa              1.2.7      2024-05-20 [1] CRAN (R 4.4.0)
 mitml              0.4-5      2023-03-08 [1] CRAN (R 4.4.0)
 munsell            0.5.1      2024-04-01 [1] CRAN (R 4.4.0)
 nlme               3.1-165    2024-06-06 [1] CRAN (R 4.4.0)
 nloptr             2.0.3      2022-05-26 [1] CRAN (R 4.4.0)
 nnet               7.3-19     2023-05-03 [1] CRAN (R 4.4.1)
 pan                1.9        2023-12-07 [1] CRAN (R 4.4.0)
 pillar             1.9.0      2023-03-22 [1] CRAN (R 4.4.0)
 pkgbuild           1.4.4      2024-03-17 [1] CRAN (R 4.4.0)
 pkgconfig          2.0.3      2019-09-22 [1] CRAN (R 4.4.0)
 pkgload            1.3.4      2024-01-16 [1] CRAN (R 4.4.0)
 plyr               1.8.9      2023-10-02 [1] CRAN (R 4.4.0)
 purrr              1.0.2      2023-08-10 [1] CRAN (R 4.4.0)
 R6                 2.5.1      2021-08-19 [1] CRAN (R 4.4.0)
 radiator         * 1.3.4      2024-06-17 [1] Github (thierrygosselin/radiator@3a8cb4f)
 ragg               1.3.2      2024-05-15 [1] CRAN (R 4.4.0)
 Rcpp               1.0.12     2024-01-09 [1] CRAN (R 4.4.0)
 readr              2.1.5      2024-01-10 [1] CRAN (R 4.4.0)
 remotes            2.5.0      2024-03-17 [1] CRAN (R 4.4.0)
 rlang              1.1.4      2024-06-04 [1] CRAN (R 4.4.0)
 rpart              4.1.23     2023-12-05 [1] CRAN (R 4.4.1)
 Rsolnp             1.16       2015-12-28 [1] CRAN (R 4.4.0)
 rstudioapi         0.16.0     2024-03-24 [1] CRAN (R 4.4.0)
 S4Vectors          0.42.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
 scales             1.3.0      2023-11-28 [1] CRAN (R 4.4.0)
 SeqArray           1.44.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
 sessioninfo        1.2.2      2021-12-06 [1] CRAN (R 4.4.0)
 shape              1.4.6.1    2024-02-23 [1] CRAN (R 4.4.0)
 SNPRelate        * 1.38.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
 stringi            1.8.4      2024-05-06 [1] CRAN (R 4.4.0)
 survival           3.7-0      2024-06-05 [1] CRAN (R 4.4.0)
 systemfonts        1.1.0      2024-05-15 [1] CRAN (R 4.4.0)
 textshaping        0.4.0      2024-05-24 [1] CRAN (R 4.4.0)
 tibble             3.2.1      2023-03-20 [1] CRAN (R 4.4.0)
 tidyr              1.3.1      2024-01-24 [1] CRAN (R 4.4.0)
 tidyselect         1.2.1      2024-03-11 [1] CRAN (R 4.4.0)
 truncnorm          1.0-9      2023-03-20 [1] CRAN (R 4.4.0)
 tzdb               0.4.0      2023-05-12 [1] CRAN (R 4.4.0)
 UCSC.utils         1.0.0      2024-05-01 [1] Bioconductor 3.19 (R 4.4.0)
 UpSetR             1.4.0      2019-05-22 [1] CRAN (R 4.4.0)
 usethis          * 2.2.3      2024-02-19 [1] CRAN (R 4.4.0)
 utf8               1.2.4      2023-10-22 [1] CRAN (R 4.4.0)
 vctrs              0.6.5      2023-12-01 [1] CRAN (R 4.4.0)
 viridisLite        0.4.2      2023-05-02 [1] CRAN (R 4.4.0)
 vroom              1.6.5      2023-12-05 [1] CRAN (R 4.4.0)
 withr              3.0.0      2024-01-16 [1] CRAN (R 4.4.0)
 XVector            0.44.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
 zlibbioc           1.50.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)

 [1] /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library

**Comment by thierrygosselin** [comment]
Dear Laia,

- Read carefully the message you sent above.
- Look at the values you have chosen for the **radiator_detect_mixed_genomes**.
- It's normal that radiator stop at the next step, because you have filtered out all the samples... it cannot run the duplicate individuals analysis...

```
Detect mixed genomes: 0.8 0.98
Number of individuals / strata / chrom / locus / SNP:
Before: 649 / 6 / 1 / 21089 / 21089
Blacklisted: 649 / 6 / 0 / 0 / 0
After: 0 / 0 / 1 / 21089 / 21089
```

I highly doubt that you have lower and upper values requiring 0.80 and 0.98 respectively.

**Consequently, here are 2 advices:**
1. Read the documentation for these 2 functions here:

- [detect_duplicate_genomes](https://thierrygosselin.github.io/radiator/reference/detect_duplicate_genomes.html)

- [detect_mixed_genomes](https://thierrygosselin.github.io/radiator/reference/detect_mixed_genomes.html)

2. Carefully read what's written while radiator is running. It's usually printing useful information.

**Comment by laiajulianamu** [comment]
Dear Thierry,

  Thank you so much for everything. I learned a lot and ran it
successfully. You can’t imagine how much I appreciate it.
Best,
Laia
