### ISSUE TITLE
Indistict allele names from vcf2genind

### ISSUE THREAD

**Issue by ksil91** [thierrygosselin/radiator#21]
Hello,
Great package, and very useful! Just came across an error when trying to do a hierfstat function on a genind object created with vcf2genind.
`stop("alleles must be encoded as integers or nucleotides. Exiting")`
When I look at the allele names for my genind, I see that they are all A1, A2:
`head(stratted.filt@all.names)`   
`$locus_100026__41__41`   
`1. 'A1' `
`2. 'A2'`  
Is there a way to get allele names that reference the original genotype? I'm pretty sure radiator is reading in my vcf correctly, because it outputs genotype info with other file conversions.

**Comment by thierrygosselin** [comment]
Hi Katherine, 

1. you could use `radiator::genomic_converter` to go directly from your vcf to hierfstat file
2. check this closed issue, [allele order changes when using genomic_converter #20](https://github.com/thierrygosselin/radiator/issues/20) to learn how to keep allele names during genind conversion.

Best
Thierry
