### ISSUE TITLE
Install of gcc on Mac High-Sierra

### ISSUE THREAD

**Issue by pbpearman** [thierrygosselin/radiator#22]
I'm trying to follow your directions for system configuration for HPC on my Mac High-Sierra installation (ver. 10.13.6), in order to use it with radiator. I am following your vignette rad_genomics_computer_setup.nb.html.
There are some issues.

I get errors at this first step:

bgppermp$ sudo tar -zxvf gcc-8.1-bin.tar.gz -C/
x usr/local/: Can't set user=0/group=0 for usr/localFailed to set file flags
x usr/local/bin/
x usr/local/.com.apple.installer.keep
x usr/local/libexec/
x usr/local/include/
.
.
.
tar: Error exit delayed from previous errors.
The issue was access to /usr/local   The solution was to set /usr/local/bin first in the path.

I followed your directions for clang, by copy-pasting, here is what happens:
bgppermp$ sudo tar -xzvf clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz -C/usr/local –strip-components 1
Password:
tar: 1: Not found in archive
tar: –strip-components: Not found in archive
tar: Error exit delayed from previous errors.

The problem is that the --strip-components term is specified incorrectly.  The entire string should be: 
sudo tar -xzvf clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz -C/usr/local --strip-components=1

You might correct your instructions for HPC at the relevant places.

**Comment by thierrygosselin** [comment]
Sorry for the delay,
I will check problem and reported solution within the next 2 days
Thanks

**Comment by thierrygosselin** [comment]
Never got this error before, updated the vignette, thanks for reporting the issues
