### ISSUE TITLE
error while filtering a large VCF file radiator::filter_rad

### ISSUE THREAD

**Issue by Carol-Symbiomics** [thierrygosselin/radiator#26]
Hi Thierry,

Thanks for this excellent tool for RADseq data visualization

I've tried to use the function filter_rad (using the interactive filter) but I wasn't able to complete the filtering because of an Error:

**Error in getGlobalsAndPackages(expr, envir = envir, tweak = tweakExpression,  :     The total size of the 3 globals that need to be exported for the future expression (‘do.call(what = FUN, args = args)’) is 3.64 GiB. This exceeds the maximum allowed size of 1.00 GiB (option 'future.globals.maxSize'). There are three globals: ‘args’ (3.64 GiB of class ‘list’), ‘FUN’ (5.59 KiB of class ‘function’) and ‘progressFifo’ (584 bytes of class ‘numeric’).**

Could you please provide advice on how to proceed with a larg vcf file (29G)??

This is all it got to do:
Folder created: 
filter_rad_20180911@1225
Reading VCF...
Large vcf file may take several minutes...
Actually, you have time for a coffee...
conversion timing: 1556 sec

radiator is working on the file ...
VCF is biallelic
Updating markers metadata and stats
[==================================================] 100%, completed in 1s
[==================================================] 100%, completed in 1s
Generating SNP position on read stats
Generating coverage stats
Generating individual stats
[==================================================] 100%, completed in 5s

Missing data (averaged):
    markers: 0.07
    individuals: 0.07

Coverage info:
    individuals mean read depth: 40034180
    individuals mean genotype coverage: 14
    markers mean coverage: 14

Number of chromosome/contig/scaffold: 2699
Number of locus: 111019
Number of markers: 3022643
Number of individuals: 323

Working time: 2068 sec

############################# IMPORTANT ###############################
Tidying vcf with 3022643 SNPs is not optimal
use radiator::filter_rad to reduce to ~ 10 000 unlinked SNPs

**Comment by thierrygosselin** [comment]
Hey Carol, will fix this in the next release. I just got my new computer.
Try emailing me again and if you don't get an answer in the next 1/2 day right here again.
