### ISSUE TITLE
genomic converter is having problem with GT column 

### ISSUE THREAD

**Issue by Carol-Symbiomics** [thierrygosselin/radiator#27]
Hi Thierry,

Could you please check the code of the genomic converter? For some reason, it is failing to generate output files.

Please, find the code I used and the console output. Thanks

> radiator::genomic_converter(data = "tidy.data.snp.ld.rad", output = c("finestructure"))
#######################################################################
#######################################################################
Function arguments and values:
Working directory: /Users/buitracn/Documents/RADseq/RADseq-Big-project/VCF-files-poptest/stacks.v2/6pop_448samples/after.dDocent.filters.6pop_345samples/filter_rad_20180914@0156/07_filter_snp_number_20180914@0156
Input file: tidy.data.snp.ld.rad
Strata: no
Population levels: no
Population labels: no
Output format(s): tidy, finestructure
Filename prefix: no
Filters: 
Blacklist of individuals: no
Blacklist of genotypes: no
Whitelist of markers: no
monomorphic.out: TRUE
snp.ld: no
common.markers: TRUE
max.marker: no
pop.select: no
maf.thresholds: no

Imputations options:
imputation.method: no

parallel.core: 7

#######################################################################

Importing data

Using markers common in all populations:
    Number of markers before/blacklisted/after:24757/0/24757
Scanning for monomorphic markers...
    Number of markers before/blacklisted/after: 24757/0/24757

Tidy genomic data:
    Number of common markers: 24757
    Number of chromosome/contig/scaffold: 905
    Number of individuals: 309
    Number of populations: 6

Preparing data for output

Error in `$<-.data.frame`(`*tmp*`, "GT", value = character(0)) : 
  replacement has 0 rows, data has 7649913
In addition: Warning message:
Unknown or uninitialised column: 'GT'.

**Comment by thierrygosselin** [comment]
I think this one is easy, try using `fineradstructure` instead of _finestructure_
I don't have spell checking code, yet. But I'll have matching arguments rule soon.
