### ISSUE TITLE
Release tags for older versions

### ISSUE THREAD

**Issue by Astahlke** [thierrygosselin/radiator#31]
Hi Thierry, 

Is it possible to tag older versions of releases for reproducibility, as suggested in [https://github.com/r-lib/devtools/issues/1469](https://github.com/r-lib/devtools/issues/1469)? From the discussion in Issue #19 , it seems like we would have to source files explicitly by commit history rather than releases.  

Thanks!

Amanda

**Comment by thierrygosselin** [comment]
Hi Amanda, 

I usually have release and zenodo associated with older commit and version released. For some reasons they are all gone. Will investigate why...

Best
Thierry

**Comment by thierrygosselin** [comment]
Hi Amanda,

I haven’t find a way to get my release tags back and zenodo DOI disappeared and was off, very weird.
Will start reintroducing them. My other r packages are not impacted by this.

In the meantime, for reproducibility, you can navigate to this [link](https://github.com/thierrygosselin/radiator/commits/master) and use the appropriate commit.

To install:

`devtools::install_github(thierrygosselin/radiator@commit-number)`

Thanks for pointing out the problem
Thierry

**Comment by thierrygosselin** [comment]
Hi Amanda, I've re-instated the commits for the [6 latest releases](https://github.com/thierrygosselin/radiator/releases). 
If you need me to go back further in time, let me know

Best
Thierry

**Comment by Astahlke** [comment]
Hi Thierry, 

Awesome. The commit history worked too. Thanks for the quick response!

Amanda
