### ISSUE TITLE
RF imputation problem

### ISSUE THREAD

**Issue by BrennaF** [thierrygosselin/radiator#32]
Hi Thierry,

We are trying to use the RF imputation in radiator. I've emailed you the code and data set. I've tried this with both an older version of radiator (0.0.13) and the current release (0.0.18). In both cases I'm using R 3.5.1 and adegenet 2.1.1.

If you run the code, you'll see that the problem is that the non-imputed and imputed data do not match the original data set -- and they don't match in different ways. I've pasted in that content below (the first 10 rows and 6 columns of each data set). You'll see that while the SNP/column names match in the original (dat) and non-imputed (gc$genlight.no.imputation) data sets, the actual data do not. Then, in the imputed data (gc$genlight.imputed), neither the SNP names nor the data match. In all cases, the row names seem to be maintained. Any idea what is going on here?

Thank you,
Brenna

![screenshot 2018-11-02 12 49 11](https://user-images.githubusercontent.com/15349374/47934794-0121ee00-de9e-11e8-8508-131636db1b76.png)

**Comment by thierrygosselin** [comment]
Running this command generate the genlight and tidy data sets (not imputed and imputed):
```
gc <- radiator::genomic_converter(data = data, 
                                  output = "genlight", 
                                  imputation.method = "rf", 
                                  monomorphic.out = FALSE, 
                                  hierarchical.levels = "global",
                                  verbose = TRUE)
```

```
#######################################################################
##################### radiator::genomic_converter #####################
#######################################################################
Function arguments and values:
Working directory: /Users/thierry/Dropbox/r_packages/package_testing/brenna_forester/imputations_problem
Input file: from global environment
Strata: no
Population levels: no
Population labels: no
Output format(s): tidy, genlight
Filename prefix: no
Filters: 
Blacklist of individuals: no
Blacklist of genotypes: no
Whitelist of markers: no
monomorphic.out: FALSE
snp.ld: no
common.markers: TRUE
max.marker: no
pop.select: no
maf.thresholds: no

Imputations options:
imputation.method: rf
hierarchical.levels: global

parallel.core: 11

#######################################################################

Importing data


Tidy genomic data:
    Number of markers: 100
    Number of chromosome/contig/scaffold: 1
    Number of individuals: 94

Preparing data for output

    Data is bi-allelic


#######################################################################
####################### grur::grur_imputations ########################
#######################################################################
Imputation method: rf
Hierarchical levels: global
On-the-fly-imputations options:
    number of trees to grow: 50
    minimum terminal node size: 1
    non-negative integer value used to specify random splitting: 10
    number of iterations: 10
Number of CPUs: 11
Note: If you have speed issues: follow radiator's vignette on parallel computing


Number of populations: 1
Number of individuals: 94
Number of markers: 100

Proportion of missing genotypes before imputations: 0.310319
On-the-fly-imputations using Random Forests algorithm
Imputations computed globally, take a break...
Adjusting REF/ALT alleles to account for imputations...
    generating REF/ALT dictionary
    integrating new genotype codings...

Proportion of missing genotypes after imputations: 0

Computation time: 2 sec
################## grur::grur_imputations completed ###################
Generating adegenet genlight object without imputation
Generating adegenet genlight object WITH imputations

Writing tidy data set:
radiator_data_20181102@1608.rad

Writing tidy data set:
radiator_data_20181102@1608.rad
############################### RESULTS ###############################
Data format of input: genlight
Biallelic data
Number of common markers: 100
Number of chromosome/contig/scaffold: 1
Number of individuals 94

Computation time: 3 sec
################ radiator::genomic_converter completed ################
```

**Comment by thierrygosselin** [comment]
**Monomorphic markers tracking:**

Because you opted out for discarding monomorphic markers,
I'm going to keep track of this, because it's something I've never attempted 
(I usually remove those markers, for these kind of analysis).


```
monomorphic.markers <- radiator::discard_monomorphic_markers(
  data = check.genlight, verbose = TRUE) %$%
  blacklist.monomorphic.markers
```

```
Scanning for monomorphic markers...
    Number of markers before/blacklisted/after: 100/18/82
```

_Problem encountered before_ 
  I've seen creation of weird haplotypes chimeras... and it's usually associated with datasets with monomorphic markers and MAC/MAF not filtered out. For some reasons it's problematic for RF and Boosting algorithms, further test are required to validate all this.

**Comment by thierrygosselin** [comment]
# compare tidy data (non imputed and imputed) side-by-side
```
check.imp1 <- dplyr::select(gc$tidy.data, MARKERS, INDIVIDUALS, GT_MISSING = GT_BIN) %>% 
  dplyr::left_join(dplyr::select(gc$tidy.data.imp, MARKERS, INDIVIDUALS, GT_IMP = GT_BIN), by = c("MARKERS", "INDIVIDUALS")
  )

check.non.imputed.data <- dplyr::filter(check.imp1, !is.na(GT_MISSING))
anyNA(check.non.imputed.data$GT_MISSING)
```

```
FALSE # all good
```

```
identical(check.non.imputed.data$GT_MISSING, check.non.imputed.data$GT_IMP)
```
```
TRUE # all good
```


Check the imputed data for missing genotypes or something other than `0, 1, 2`:

```
check.imputed.data <- dplyr::filter(check.imp1, is.na(GT_MISSING))
anyNA(check.imputed.data$GT_IMP)
```

```
FALSE # all good
```

```
unique(check.imputed.data$GT_IMP)
```

```
0 1 2 # all good
```

**Comment by thierrygosselin** [comment]
Here to make sure we're using the same RF algorithm:
`packageVersion(pkg = "randomForestSRC")` = 2.7.0

**Comment by thierrygosselin** [comment]
**Problem 2**
I confirm that I'm getting the same weird results when comparing the original data with the genlight (with and without imputations)

**Comment by Astahlke** [comment]
Maybe this will help.... I found that if I arranged the locus columns of our original data set, all seems to go well for some reason.

> miss1.test <- miss[,1:100]
 > col.order <- sort(colnames(miss1.test))
 > miss1.test.arr <- miss1.test[,col.order]
 > x  <- as.genlight(miss1.test.arr)
  
 > x@pop <- as.factor(rep("PO1", dim(pred)[1]))
 > x@position <- as.integer(rep(1, 100)

> gc <- genomic_converter(data=x, 
                            imputation.method="rf", hierarchical.levels="global", 
                            verbose = TRUE, keep.allele.names=T, monomorphic.out = FALSE)

> as.matrix(gc$genlight.imputed)[1:6,1:10]
                    chr27.3062945 chr27.3684579 chr38.3800505
11226.CEL                       0             0             0
11228.CEL                       0             0             0
11232-CLU-NQUE-I                0             0             0
11234-CLU-NQUE-I                0             0             0
2042-CLU-CANADA-FBG             1             0             0
2043-CLU-CANADA-FG              1             0             0
                    chr27.3723753 chr27.3730837 chr27.3735952
11226.CEL                       0             0             0
11228.CEL                       1             0             0
11232-CLU-NQUE-I                1             0             0
11234-CLU-NQUE-I                0             0             0
2042-CLU-CANADA-FBG             2             0             0
2043-CLU-CANADA-FG              0             0             0
                    chr27.3814403 chr28.3242701 chr28.3242986
11226.CEL                       0             0             0
11228.CEL                       0             0             0
11232-CLU-NQUE-I                0             0             0
11234-CLU-NQUE-I                0             0             0
2042-CLU-CANADA-FBG             0             0             0
2043-CLU-CANADA-FG              0             1             0
                    chr28.3294732
11226.CEL                       0
11228.CEL                       1
11232-CLU-NQUE-I                0
11234-CLU-NQUE-I                0
2042-CLU-CANADA-FBG             0
2043-CLU-CANADA-FG              0

> as.matrix(x)[1:6,1:10]
                    chr27.3062945 chr27.3090185_0 chr27.3306005
11226.CEL                      NA               0             0
11228.CEL                      NA               0             0
11232_CLU_NQUE-I               NA               0             0
11234_CLU_NQUE-I                0               0             0
2042_CLU_CANADA-FBG             1               0             0
2043_CLU_CANADA-FG              1               0             0
                    chr27.3395304 chr27.3404247 chr27.3530217
11226.CEL                       0            NA             0
11228.CEL                       1            NA             0
11232_CLU_NQUE-I                1             0             0
11234_CLU_NQUE-I                0             0             0
2042_CLU_CANADA-FBG             2             0             0
2043_CLU_CANADA-FG              0             0             0
                    chr27.3602391 chr27.3645758 chr27.3661863_0
11226.CEL                       0            NA               0
11228.CEL                       0             0               0
11232_CLU_NQUE-I                0             0               0
11234_CLU_NQUE-I                0            NA               0
2042_CLU_CANADA-FBG             0             0               0
2043_CLU_CANADA-FG              0             1               0
                    chr27.3684579
11226.CEL                       0
11228.CEL                       1
11232_CLU_NQUE-I                0
11234_CLU_NQUE-I                0
2042_CLU_CANADA-FBG             0
2043_CLU_CANADA-FG              0`

**Comment by thierrygosselin** [comment]
because both tidy datasets (imputed or not) are ok, it's with radiator::write_genlight the problem... fixing it...

**Comment by thierrygosselin** [comment]
The imputed dataset leaves the factory ordered: MARKERS, POP_ID, INDIVIDUALS
The tidy dataset leaves the factory ordered: POP_ID, INDIVIDUALS, MARKERS

**Comment by thierrygosselin** [comment]
and during the genlight construction...
```
adegenet::indNames(genlight.object)   <- input$INDIVIDUALS
  adegenet::pop(genlight.object)        <- input$POP_ID
  adegenet::chromosome(genlight.object) <- marker.meta$CHROM
  adegenet::locNames(genlight.object)   <- marker.meta$LOCUS
  adegenet::position(genlight.object)   <- marker.meta$POS
```
the markers.meta object gets created before the data frame is _spread_ wide... using `tidyr::spread`
automatically reorder...


So we need:
```
marker.meta1 <- dplyr::distinct(.data = gc$tidy.data, MARKERS, CHROM, LOCUS, POS)
data.spread1 <- dplyr::select(.data = gc$tidy.data, MARKERS, POP_ID, INDIVIDUALS, GT_BIN) %>%
  dplyr::mutate(GT_BIN = as.integer(GT_BIN)) %>%
  dplyr::group_by(INDIVIDUALS, POP_ID) %>%
  tidyr::spread(data = ., key = MARKERS, value = GT_BIN)

marker.meta2 <- dplyr::distinct(.data = gc$tidy.data.imp, MARKERS, CHROM, LOCUS, POS)
data.spread2 <- dplyr::select(.data = gc$tidy.data.imp, MARKERS, POP_ID, INDIVIDUALS, GT_BIN) %>%
  dplyr::mutate(GT_BIN = as.integer(GT_BIN)) %>%
  dplyr::group_by(INDIVIDUALS, POP_ID) %>%
  tidyr::spread(data = ., key = MARKERS, value = GT_BIN)
```

We check:

```
identical(marker.meta1$MARKERS, marker.meta2$MARKERS) # FALSE... OK we know
```

```
identical(colnames(data.spread1), colnames(data.spread2)) # TRUE!!! expecting this
```


**SOLUTION: order the metadata by markers ...**
```
markers.meta2.ordered <- dplyr::arrange(marker.meta2, MARKERS)

identical(markers.meta2.ordered$MARKERS, marker.meta1$MARKERS)# yep
identical(colnames(data.spread2)[-c(1,2)], markers.meta2.ordered$MARKERS) #yep
```

ok so the good news, genind object are not impacted by this!

**Comment by thierrygosselin** [comment]
scary... 
it's always a problem when the values for these things are not imported directly from the data.
VCF files are a challenge because what people generating the vcf say you would have in the data (using header) is not always what you have IN the data (e.g. saying yo have GL or HQ, and the info is not there... creates parsing failure/problems ...)

**Comment by thierrygosselin** [comment]
latest commit (ddd7155) fix the issues highlighted above
reopen if problem
Thanks for highlighting the bug

**Comment by thierrygosselin** [comment]
I'm using a lot of imputed genind... fiou!
