### ISSUE TITLE
"Evaluation error" when executing radiator::tidy_genomic_data

### ISSUE THREAD

**Issue by fkatharina** [thierrygosselin/radiator#35]
Hi Thierry,

I wonder if you can help me with the following problem I have:
I would like to a) tranform my vcf data into a tidy data frame using "tidy_genomic_data", then b) fill NAs using the "radiator_imputations_module".
In the first step, this is my code:

mullus.imp <- radiator::tidy_genomic_data(
  data = "LD5000_WestMed.recode.vcf",
  vcf.metadata = TRUE,
  verbose = TRUE)

and this is the resulting output and error:

####################################################################### ##################### radiator::tidy_genomic_data ##################### ####################################################################### Importing and tidying the VCF...  Reading VCF... Generated a filters parameters file: filters_parameters_20190109@1517.tsv  Number of SNPs: 15990 Number of samples: 317  conversion timing: 13 sec  VCF: biallelic SNPs Cleaning VCF sample names Reads assembly: reference-assisted Filters parameters file: updated Generating individual stats Error in mutate_impl(.data, dots) :    Evaluation error: One of the nodes produced an error: Can not open file 'C:\Users\kfietz\Desktop\radiator_20190109@1517.gds'. Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (=the process cannot access the file because it is used by another process)
--

As I see it, the gds-file is being created at the very moment I execute the command, hence I do not understand how it can be used by another process and what I may do to overcome this error.
Any advice appreciated.

many thanks in advance,
Katharina

**Comment by thierrygosselin** [comment]
Try the latest release
Reopen issue if you still have a problem.
Provide a reproducible example.
