### ISSUE TITLE
deprecated function

### ISSUE THREAD

**Issue by Maschette** [thierrygosselin/radiator#36]
Hi , 
When running genomic_converter outputting to bayescan and running run_bayescan I get the warning: 
`Deprecated function, update your code to use: filter_monomorphic`

I am assuming it is this line which needs to be updated in write_bayescan? 
`  data <- radiator::discard_monomorphic_markers(data = data, verbose = TRUE)$input`

**Comment by thierrygosselin** [comment]
please try the latest release.
