### ISSUE TITLE
radiator::filter_rad has problem with strata recognition

### ISSUE THREAD

**Issue by Carol-Symbiomics** [thierrygosselin/radiator#39]
Hi Thierry,

I've been unable to filter my RADseq data set using the interactive filter of radiator::filter_rad. This is because for some reason the strata file is not being recognized 

> Error in radiator::tidy_genomic_data(data = data, strata = strata, vcf.metadata = TRUE,  : 
  Non-matching INDIVIDUALS between data and strata.

if I only used a tidy.data (supposedly with the strata information already on it) 

> data.filtered <- radiator::filter_rad(data = prep.vcf$tidy.data, output = "genind", filename = "spis.test")

Then the interactive filter runs, yet when it gets to the 4th filtering step "04: Filtering individuals poorly genotyped" the graph only shows "overall" and "NA" boxplots, and no matter the filtering threshold you set, not a single individual gets blacklisted.

This is a recurrent problem. I tried to reproduce the filtering with a dataset it had worked perfectly in the past but it doesn't work any longer.

**Comment by thierrygosselin** [comment]
latest release should have fix this problem
