### ISSUE TITLE
"Error: object 'ALLELE_REF_DEPTH' not found" when converting from VCF

### ISSUE THREAD

**Issue by kevinmneal** [thierrygosselin/radiator#43]
Hi,

Running radiator, updated package and tested just a few minutes ago (and was getting it the past week on radiator 1.0.0), using R 3.5.1 on Windows.

I have been unable to convert a VCF output from ipyrad 0.7.28, and the same after being filtered in vcftools, whether using filter_rad(), tidy_vcf(), or tidy_genomic_data(). It looks like it still completes the conversion to a gds, but I get no tidy .rad data frame out, and no saved object in R.

(One issue I'd first like to note to ipyrad users is: for radiator to read your vcf at all, you need to change the NUMBER=1 in ##FORMAT=<ID=CATG,Number=1,Type=String,Description="Base Counts (CATG)"> to NUMBER=4)

Header on ipyrad VCF with first line for first sample is:
```
##fileformat=VCFv4.0
##fileDate=2019/01/13
##source=ipyrad_v.0.7.28
##reference=genomeassembly.fasta
##phasing=unphased
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=CATG,Number=4,Type=String,Description="Base Counts (CATG)"> 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1 
locus_100006	5	.	G	A	13	PASS	NS=120;DP=2002	GT:DP:CATG	0/0:250:0,0,0,250
```

The attempted functions I stall out when extracting DP information:
```
Reading VCF...you have time for a espresso...
Data summary: 
    number of samples: 267
    number of markers: 44310
done! timing: 33 sec


Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 25 / 31 / 31
Only 1 strata...returning data
[==================================================] 100%, completed in 1s
Extracting DP information...
Error: object 'ALLELE_REF_DEPTH' not found

Computation time, overall: 47 sec

```
I'm assuming ALLELE_REF_DEPTH means radiator wants two depth values, one for the REF allele and one for the ALT, but my VCF only has the total depth (though shows number of CATG reads), and the VCF 4.1 format also has no mention of REF vs ALT-specific depth. Any idea what's going on? Possibly an issue with the seemingly ipyrad-specific CATG format ID?

(also unrelated: if I try to run functions with parallel.core > 1, I get this error:
```
Error in .DynamicClusterCall(cl, length(cl), .fun = function(.proc_idx,  : 
  One of the nodes produced an error: Can not open file 'G:\My Drive\Illumina Sequencing Data\20181212_rangewide\sphaOCclust85\tidy_vcf_20190318@1356\sphasouth267.commonmarkers.tidy.rad_20190318@1356.gds'. The process cannot access the file because it is being used by another process.
```

And one other miscellaneous error I get when I install/update radiator, in case it helps: "Warning: unable to re-encode 'filter_monomorphic.R' line 7"

Thanks

**Comment by thierrygosselin** [comment]
Hi Kevin
Thanks for highlighting the bugs

Ideally, you really don’t want to start changing things in you’re vcf file...

Please, send me the first 200-300 lines of the vcf by email along the strata file you used above. It’s been a while I used ipyrad, I don’t have a vcf to use.

**Comment by kevinmneal** [comment]
Sent, thanks for looking

**Comment by thierrygosselin** [comment]
The problem was in the interpretation of `CHROM`, `POS` and `ID` field using SeqArray as import engine. Now it should work, with or without the change in the header, but I suggest you don't change it.

The way I parsed the markers metadata info:
From the VCF header, I'm guesing it's reference-assisted...
If that is correct, you have in the `CHROM` column the scaffolds starting with `locus_` and this info is also the locus info. So I'm trimming the `locus_` for the locus id.

The `POS` with [ipyrad](https://ipyrad.readthedocs.io/tutorial_intro_cli.html) seems to be also the position of the SNP on the read (`COL`, in here).


By default the function keeps only common markers.
it can be turned off using `filter.common.markers = FALSE`.

With your dataset:
```
radiator::summary_strata("OCall208_85clust_75pctmsng_oneSNPmac2_20190205_radiator_strata.txt")
# Number of populations: 26
# Number of individuals: 208
#
# Number of ind/pop:
# FREM = 2
# SADDLE = 1
# IM03 = 7
# IM07 = 10
# IM09 = 10
# IM12 = 6
# IM02 = 8
# IM01 = 10
# IM06 = 10
# IM14 = 8
# BBEND = 10
# LAGUN = 10
# MORO = 10
# THOM = 9
# LOMA = 10
# SHOE = 10
# LAUR = 9
# LIME = 9
# STARR = 10
# CCSP1 = 10
# CCSP2 = 3
# CCSP3 = 5
# GREAT = 10
# TORO = 1
# TENA = 10
# SANCAN = 10
# Number of duplicate id: 0
```

The populations/groups with just 1 sample were causing problems in the common markers module. More precisely during the creation of the figure with `UpSetR` package. He doesn't like that. So I added an argument that you can use inside `radiator::filter_rad` and `radiator::read_vcf` : `fig.upsetr = FALSE`.


To run:

```
data <- radiator::read_vcf(
    data = "OCall208_75pctmsng.recode.vcf",
    strata = "OCall208_85clust_75pctmsng_oneSNPmac2_20190205_radiator_strata.txt",
    fig.upsetr = FALSE, 
    verbose = TRUE)
```

This should take ~ 15 sec

**Comment by kevinmneal** [comment]
Hi Thierry,

Unfortunately I'm still getting the errors using read_vcf and filter_rad after installing radiator with the updates (I've checked the functions to ensure they match the latest commits), whether I remove the offending populations, set fig.upsetr=FALSE, keep Number=1 or change it to Number=4, etc. Was I too impatient and the full fix hasn't been committed yet?
