### ISSUE TITLE
Work on sexy_function

### ISSUE THREAD

**Issue by thierrygosselin** [thierrygosselin/radiator#47]
`sexy_markers` works on:
- [x] DArT Silico genotypes
- [x] DArT Silico counts
- [x] DArT counts
- [x] DArT genotypes 1row
- [x] DArT genotypes 2rows
- [x] DArT VCF
- [x] VCF with read and allele depth

To do:
- [x] UpSetR plot of common sex markers

**Comment by FloriaanDD** [comment]
Current issue persists with "read_vcf" function. The 'genotypes.meta' node is not written to the GDS object. This causes and error with the "extract_genotypes_metadata' function.

**Comment by FloriaanDD** [comment]
Fixed the "extract_genotypes_metadata" issue by directly extracting the GT_BIN and READ_DEPTH information from the "$dosage" and "annotation/format/DP" nodes in the gds object
