### ISSUE TITLE
ibdg_fh() FH calculation and summary_rad() calculations

### ISSUE THREAD

**Issue by kevinmneal** [thierrygosselin/radiator#49]
Hi Thierry,

I'm trying out ibdg_fh, but I'm not sure I understand your modification to the way it's calculated in PLINK. It looks like I can recreate the radiator-calculated FH by dividing the difference of the observed and expected homozygous _proportions_ by the _count_ of loci, while PLINK uses all counts as described at https://www.cog-genomics.org/plink/1.9/basic_stats#ibc (same result if use all proportions; issue just seems to be mixing proportions with counts in the calculation). Attaching a spreadsheet with radiator values and manually-calculated PLINK values to make it clearer.

The description of the radiator ibdg_fh function sounds like you did modify it intentionally to differ from PLINK, but the current calculation seems like a bug. Also, is the population-level FH calculated by averaging the individual FH values?

And relatedly, could you explain how the calculations for summary_rad() are produced (in comparison to, say, basic.stats() from hierfstat? FIS values in particular are vastly different. Spreadsheet comparing those also attached.

[sphanorth124spatial.fh.individuals.xlsx](https://github.com/thierrygosselin/radiator/files/3143446/sphanorth124spatial.fh.individuals.xlsx)

[hierfstatbasicstats.radiatorsummarystats.sphanorth124spatial.radiator.50pctmsng.xlsx](https://github.com/thierrygosselin/radiator/files/3143453/hierfstatbasicstats.radiatorsummarystats.sphanorth124spatial.radiator.50pctmsng.xlsx)

**Comment by thierrygosselin** [comment]
Thanks Kevin
Will answer those today
Will first run my tests again to make sure it's okay

**Comment by thierrygosselin** [comment]
The big difference, I think, is (i) when common markers are used or not and (ii) when sample missingness deviates from the mean (population or overall, here). Because the reported values account for that, i.e. it's based on what was measured for the particular sample.

Obviously one would prefer samples to be very similar and have as few missing genotypes. But that's not the reality of most RADseq projects...

**Comment by thierrygosselin** [comment]
Since the calculations are fast, I could also output the calculations based on the total number of markers (dataset wide, genotyped or not for the sample).

**Comment by kevinmneal** [comment]
Hi Thierry,

Would you be able to update the documentation with the calculations for pi() as well? Also, in general, I'm wondering if pi is an appropriate statistic when using only the variable loci from RADseq. Your function is derived from the way Stacks calculates it across haplotypes (both variant and invariant), right? In which case, I am probably getting misleading results if I'm using data derived from a VCF and should instead calculate them directly from the sequence data (the loci files from ipyrad, for example)

**Comment by thierrygosselin** [comment]
Hi Kevin, sorry for the delay in response

I'm following Nei's equation for Pi and I've never got the result to be the same as stacks. 
Using the read length (all reads must be the same length to be accurate) accounts for the invariant sites

https://thierrygosselin.github.io/radiator/reference/pi.html
