### ISSUE TITLE
Keep all SNPs per locus

### ISSUE THREAD

**Issue by aimzvdr** [thierrygosselin/radiator#52]
Hi there

I am wanting to keep all the SNPs present in the loci for the comparison. 

Is this possible?

Cheers
Aimee

Execution date@time: 20190716@1551
Function call and arguments stored in: radiator_filter_snp_position_read_args_20190716@1551.tsv
2 steps to visualize and filter the data based on the number of SNP on the read/locus:
Step 1. Visualization (boxplot, distribution
Step 2. Threshold selection
Filters parameters file: initiated
Generating SNP position on read stats
Generating helper table...
Files written: helper tables and plots

Step 2. Filtering markers based on the SNPs position on the read

Choice of stats are: 
1: all (filter off)
2: outliers
3: q75
4: iqr
5: choose your own min and max values
1
File written: whitelist.markers.snp.position.read.tsv
File written: blacklist.markers.snp.position.read.tsv
Filters parameters file: updated
################################### RESULTS ####################################

Filter SNP position on the read : all
Number of individuals / strata / chrom / locus / SNP:
    Before: 84 / 5 / 1 / 514 / 957
    Blacklisted: 0 / 0 / 0 / 0 / 0
    After: 84 / 5 / 1 / 514 / 957

Computation time, overall: 18 sec
################################################################################
################################################################################
Execution date@time: 20190716@1551
Function call and arguments stored in: radiator_filter_snp_number_args_20190716@1551.tsv
Interactive mode: on
2 steps to visualize and filter the data based on the number of SNP on the read/locus:
Step 1. Impact of SNP number per read/locus (on individual genotypes and locus/snp number potentially filtered)
Step 2. Choose the filtering thresholds
Filters parameters file: initiated
Generating statistics

With max read length taken from data: 83
    The max number of SNP per locus correspond to:
    1 SNP per 12 bp

Generating helper table...
Files written: helper tables and plots

Step 2. Filtering markers based on the maximum of SNPs per locus

Do you still want to blacklist markers? (y/n):
**n**
File written: whitelist.markers.genotyping.tsv
File written: blacklist.markers.genotyping.tsv
Filters parameters file: updated
################################### RESULTS ####################################

Filter SNPs per locus threshold: 1e+12
Number of individuals / strata / chrom / locus / SNP:
    Before: 84 / 5 / 1 / 514 / 957
    Blacklisted: 0 / 0 / 0 / 0 / 0
    After: 84 / 5 / 1 / 514 / 957

Computation time, overall: 95 sec
################################################################################
################################################################################
Execution date@time: 20190716@1552
Function call and arguments stored in: radiator_filter_ld_args_20190716@1552.tsv

Interactive mode: on

Step 1. Short distance LD threshold selection
Step 2. Filtering markers based on short distance LD
Step 3. Long distance LD pruning selection
Step 4. Threshold selection
Step 5. Filtering markers based on long distance LD

Filters parameters file: initiated
Minimizing short distance LD...
    The range in the number of SNP/locus is: 1-7

Step 1. Short distance LD threshold selection
the goal is to keep only 1 SNP per read/locus
Choose the filter.short.ld threshold
Options include:
1: mac (Not sure ? use mac...)
2: random
3: first
4: middle
5: last
1

**Comment by thierrygosselin** [comment]
Hi Aimee
Sorry about the delay in responding to your question.
It's difficult for me to understand correctly, could you specify where you want to keep all SNPs on the locus? Is it at the short LD pruning step ?

**Comment by thierrygosselin** [comment]
reopen the issue if you're still having problems
