### ISSUE TITLE
calculations for missing prop and heterozygosity

### ISSUE THREAD

**Issue by DPrada04** [thierrygosselin/radiator#53]
Hi Thierry,

I'm learning to use radiator, what it does and how it works. I've been using a dummy data set (DarT) of 19 individuals, two populations and 53 loci to run the package.

However, my "by hand" calculations do not match the missing proportion and heterozygosity values generated by the "filter_individuals" function. I had a look at the function and couldn't figure out how radiator calculates these values. So for example, the "missing_prop" for a particular individual is 0.32, however it only has 4 missing data points out of the 53 loci (4/53= 0.075, missing prop). Likewise, an additional sample has a heterozygosity value of "0" but that individual is heterozygote for two loci.

Do you mind shedding some light on how these values are derived or pointing me to where this is explained?

I have attached the dummy data set  and the individuals qc. stats.tvs output in case you need them
[Dummy_dataset_and_output_qc_indv.zip](https://github.com/thierrygosselin/radiator/files/3400186/Dummy_dataset_and_output_qc_indv.zip)

the code i've used is:

infile1 <- "./Dummy_Data_subset.csv"
infile3 <- "./strata.txt"

tmp=read_dart(infile1, infile3)
tmp2= filter_individuals(tmp)

Thank you,

Diana

**Comment by thierrygosselin** [comment]
Hi Diana,

sorry for the delay in responding to the problem you're facing with radiator. I'll download the dummy dataset and will try to reproduce the differences mentioned above.
Best
Thierry

**Comment by DPrada04** [comment]
Hi Thierry,

Thank you for taking the time to look into this. I greatly appreciate it.

Diana

Sent from my iPhone

On 9 Aug 2019, at 3:10 am, Thierry Gosselin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Diana,

sorry for the delay in responding to the problem you're facing with radiator. I'll download the dummy dataset and will try to reproduce the differences mentioned above.
Best
Thierry

**Comment by thierrygosselin** [comment]
Hi Diana, 

The reason it's not working properly is that it's not an original DArT SNP format file where genotypes are coded in 1 Row.

In your file, the missing data as nothing, whereas in an original DArT file for this particular format, the missing data is coded as `-`.

Please try with an original, untouched, dataset.
Re-open the issue if you still have a problem

Thanks
Thierry
