### ISSUE TITLE
filter_hwe

### ISSUE THREAD

**Issue by rcastil** [thierrygosselin/radiator#55]
Hi Thierry,
Thank you for a terrific package!
My problem is that after filter_hwe, I do not get a working file, and therefore, I cannot proceed with my analysis. I am sending an RData zip file hopefully with what you need. I understand the function should produce a .rad file, but I cannot find it. Also, if it would save a file, what type of file would it be, genind, genepop, etc?
Many thanks,
Rita

**Describe the bug**
filter_hwe does not save the resulting file without markers that have a certain number of pops in Hardy-Weinberg disequilibrium. 

**To Reproduce**
radiator::filter_hwe(radiator.gen, 
           interactive.filter = TRUE, 
           filter.hwe = TRUE,
           strata = NULL, 
           hw.pop.threshold = TRUE, 
           midp.threshold = "***",
           filename = NULL, 
           parallel.core = parallel::detectCores() - 1,
           verbose = TRUE)
* the complete error message you're getting
Content of folder:02_filter_hwe_20190812@2233
filters_parameters_20190812@2233.tsv
genotypes.summary.tsv
hw.pop.sum.tsv
hwd.helper.table.tsv
hwd.plot.blacklist.markers.pdf
radiator_filter_hwe_args_20190812@2233.tsv

* the output of `devtools::session_info()`
> devtools::session_info()
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Mojave 10.14.5        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Lisbon               
 date     2019-08-12                  

─ Packages ─────────────────────────────────────────────────────────────
 package          * version    date       lib
 abind              1.4-5      2016-07-21 [1]
 acepack            1.4.1      2016-10-29 [1]
 ade4             * 1.7-13     2018-08-31 [1]
 adegenet         * 2.1.1      2018-02-02 [1]
 ape              * 5.3        2019-03-17 [1]
 assertthat         0.2.1      2019-03-21 [1]
 backports          1.1.4      2019-04-10 [1]
 base64enc          0.1-3      2015-07-28 [1]
 bayesm             3.1-3      2019-07-29 [1]
 BDgraph            2.60       2019-08-08 [1]
 bitops             1.0-6      2013-08-17 [1]
 boot               1.3-23     2019-07-05 [1]
 broom              0.5.2      2019-04-07 [1]
 calibrate          1.7.2      2013-09-10 [1]
 callr              3.3.1      2019-07-18 [1]
 caTools            1.17.1.2   2019-03-06 [1]
 checkmate          1.9.4      2019-07-04 [1]
 class              7.3-15     2019-01-01 [1]
 classInt           0.4-1      2019-08-06 [1]
 cli                1.1.0      2019-03-19 [1]
 cluster            2.1.0      2019-06-19 [1]
 coda               0.19-3     2019-07-05 [1]
 codetools          0.2-16     2018-12-24 [1]
 colorspace         1.4-1      2019-03-18 [1]
 combinat           0.0-8      2012-10-29 [1]
 compositions       1.40-2     2018-06-14 [1]
 corpcor            1.6.9      2017-04-01 [1]
 crayon             1.3.4      2017-09-16 [1]
 crosstalk          1.0.0      2016-12-21 [1]
 curl               4.0        2019-07-22 [1]
 d3Network          0.5.2.1    2015-01-31 [1]
 dartR            * 1.3.4      2019-08-11 [1]
 data.table         1.12.2     2019-04-07 [1]
 DBI                1.0.0      2018-05-02 [1]
 deldir             0.1-23     2019-07-31 [1]
 DEoptimR           1.0-8      2016-11-19 [1]
 desc               1.2.0      2018-05-01 [1]
 devtools         * 2.1.0      2019-07-06 [1]
 digest             0.6.20     2019-07-04 [1]
 directlabels       2018.05.22 2018-05-25 [1]
 dismo              1.1-4      2017-01-09 [1]
 diveRsity        * 1.9.90     2017-04-04 [1]
 doParallel       * 1.0.15     2019-08-02 [1]
 dplyr              0.8.3      2019-07-04 [1]
 e1071              1.7-2      2019-06-05 [1]
 ellipse            0.4.1      2018-01-05 [1]
 energy             1.7-6      2019-07-06 [1]
 expm               0.999-4    2019-03-21 [1]
 fansi              0.4.0      2018-10-05 [1]
 fastmatch          1.1-0      2017-01-28 [1]
 fdrtool            1.2.15     2015-07-08 [1]
 foreach          * 1.4.7      2019-07-27 [1]
 foreign            0.8-72     2019-08-02 [1]
 Formula            1.2-3      2018-05-03 [1]
 fs                 1.3.1      2019-05-06 [1]
 fst                0.9.0      2019-04-09 [1]
 gap                1.2.1      2019-06-05 [1]
 gdata              2.18.0     2017-06-06 [1]
 gdistance          1.2-2      2018-05-07 [1]
 gdsfmt             1.20.0     2019-05-02 [1]
 generics           0.0.2      2018-11-29 [1]
 genetics           1.3.8.1.2  2019-04-22 [1]
 GGally             1.4.0      2018-05-17 [1]
 ggm                2.3        2015-01-21 [1]
 ggplot2          * 3.2.1      2019-08-10 [1]
 ggpubr           * 0.2.2      2019-08-07 [1]
 ggsignif           0.6.0      2019-08-08 [1]
 ggtern             3.1.0      2018-12-19 [1]
 glasso             1.10       2018-07-13 [1]
 glue               1.3.1      2019-03-12 [1]
 gmodels            2.18.1     2018-06-25 [1]
 gplots           * 3.0.1.1    2019-01-27 [1]
 gridExtra          2.3        2017-09-09 [1]
 gtable             0.3.0      2019-03-25 [1]
 gtools             3.8.1      2018-06-26 [1]
 HardyWeinberg      1.6.3      2019-06-29 [1]
 hierfstat        * 0.04-22    2015-12-04 [1]
 Hmisc              4.2-0      2019-01-26 [1]
 hms                0.5.0      2019-07-09 [1]
 htmlTable          1.13.1     2019-01-07 [1]
 htmltools          0.3.6      2017-04-28 [1]
 htmlwidgets        1.3        2018-09-30 [1]
 httpuv             1.5.1      2019-04-05 [1]
 huge               1.3.2      2019-04-08 [1]
 HWxtest          * 1.1.9      2019-05-31 [1]
 igraph             1.2.4.1    2019-04-22 [1]
 iterators        * 1.0.12     2019-07-26 [1]
 jomo               2.6-9      2019-07-29 [1]
 jpeg               0.1-8      2014-01-23 [1]
 jsonlite           1.6        2018-12-07 [1]
 KernSmooth         2.23-15    2015-06-29 [1]
 knitr              1.24       2019-08-08 [1]
 labeling           0.3        2014-08-23 [1]
 later              0.8.0      2019-02-11 [1]
 latex2exp          0.4.0      2015-11-30 [1]
 lattice            0.20-38    2018-11-04 [1]
 latticeExtra       0.6-28     2016-02-09 [1]
 lavaan             0.6-4      2019-07-03 [1]
 lazyeval           0.2.2      2019-03-15 [1]
 leaflet            2.0.2      2018-08-27 [1]
 LearnBayes         2.15.1     2018-03-18 [1]
 lme4               1.1-21     2019-03-05 [1]
 magrittr         * 1.5        2014-11-22 [1]
 manipulateWidget   0.10.0     2018-06-11 [1]
 MASS               7.3-51.4   2019-03-31 [1]
 Matrix             1.2-17     2019-03-22 [1]
 memoise            1.1.0      2017-04-21 [1]
 mgcv               1.8-28     2019-03-21 [1]
 mice               3.6.0      2019-07-10 [1]
 mime               0.7        2019-06-11 [1]
 miniUI             0.1.1.1    2018-05-18 [1]
 minqa              1.2.4      2014-10-09 [1]
 mitml              0.3-7      2019-01-07 [1]
 mmod             * 1.3.3      2017-04-06 [1]
 mnormt             1.5-5      2016-10-15 [1]
 munsell            0.5.0      2018-06-12 [1]
 mvtnorm            1.0-11     2019-06-19 [1]
 nlme               3.1-141    2019-08-01 [1]
 nloptr             1.2.1      2018-10-03 [1]
 nnet               7.3-12     2016-02-02 [1]
 pan                1.6        2018-06-29 [1]
 pander           * 0.6.3      2018-11-06 [1]
 pbapply            1.4-1      2019-07-15 [1]
 pbivnorm           0.6.0      2015-01-23 [1]
 pbmcapply          1.5.0      2019-07-10 [1]
 pca3d              0.10       2017-02-17 [1]
 pegas            * 0.11       2018-07-09 [1]
 permute            0.9-5      2019-03-12 [1]
 phangorn           2.5.5      2019-06-19 [1]
 pillar             1.4.2      2019-06-29 [1]
 pinfsc50           1.1.0      2016-12-02 [1]
 pixmap           * 0.4-11     2011-07-19 [1]
 pkgbuild           1.0.4      2019-08-05 [1]
 pkgconfig          2.0.2      2018-08-16 [1]
 pkgload            1.0.2      2018-10-29 [1]
 plyr               1.8.4      2016-06-08 [1]
 png                0.1-7      2013-12-03 [1]
 polysat            1.7-4      2019-03-06 [1]
 PopGenReport       3.0.4      2019-02-04 [1]
 poppr            * 2.8.3      2019-06-18 [1]
 prettyunits        1.0.2      2015-07-13 [1]
 processx           3.4.1      2019-07-18 [1]
 promises           1.0.1      2018-04-13 [1]
 proto              1.0.0      2016-10-29 [1]
 ps                 1.3.0      2018-12-21 [1]
 psych              1.8.12     2019-01-12 [1]
 purrr              0.3.2      2019-03-15 [1]
 qgraph             1.6.3      2019-06-19 [1]
 quadprog           1.5-7      2019-05-06 [1]
 qvalue             2.16.0     2019-05-02 [1]
 R.methodsS3        1.7.1      2016-02-16 [1]
 R.oo               1.22.0     2018-04-22 [1]
 R.utils            2.9.0      2019-06-13 [1]
 R6                 2.4.0      2019-02-14 [1]
 radiator         * 1.1.1      2019-08-12 [1]
 raster             2.9-23     2019-07-11 [1]
 RColorBrewer     * 1.1-2      2014-12-07 [1]
 Rcpp               1.0.2      2019-07-25 [1]
 readr              1.3.1      2018-12-21 [1]
 remotes            2.1.0      2019-06-24 [1]
 reshape            0.8.8      2018-10-23 [1]
 reshape2         * 1.4.3      2017-12-11 [1]
 rgdal              1.4-4      2019-05-29 [1]
 rgeos              0.5-1      2019-08-05 [1]
 rgl                0.100.26   2019-07-08 [1]
 RgoogleMaps        1.4.3      2018-11-07 [1]
 rJava            * 0.9-11     2019-03-29 [1]
 rjson              0.2.20     2018-06-08 [1]
 rlang              0.4.0      2019-06-25 [1]
 robustbase         0.93-5     2019-05-12 [1]
 rpart              4.1-15     2019-04-12 [1]
 rprojroot          1.3-2      2018-01-03 [1]
 rrBLUP             4.6        2018-01-28 [1]
 Rsolnp             1.16       2015-12-28 [1]
 rstudioapi         0.10       2019-03-19 [1]
 rtiff            * 1.4.6      2019-03-21 [1]
 scales             1.0.0      2018-08-09 [1]
 sendplot         * 4.0.0      2013-04-25 [1]
 seqinr             3.4-5      2017-08-01 [1]
 sessioninfo        1.1.1      2018-11-05 [1]
 sf                 0.7-7      2019-07-24 [1]
 shiny              1.3.2      2019-04-22 [1]
 SNPRelate          1.18.1     2019-07-03 [1]
 sp                 1.3-1      2018-06-05 [1]
 spData             0.3.0      2019-01-07 [1]
 spdep              1.1-2      2019-04-05 [1]
 StAMPP           * 1.5.1      2017-11-10 [1]
 stringi            1.4.3      2019-03-12 [1]
 stringr            1.4.0      2019-02-10 [1]
 survival           2.44-1.1   2019-04-01 [1]
 tensorA            0.36.1     2018-07-29 [1]
 testthat           2.2.1      2019-07-25 [1]
 tibble             2.1.3      2019-06-06 [1]
 tidyr              0.8.3      2019-03-01 [1]
 tidyselect         0.2.5      2018-10-11 [1]
 truncnorm          1.0-8      2018-02-27 [1]
 units              0.6-3      2019-05-03 [1]
 usethis          * 1.5.1      2019-07-04 [1]
 utf8               1.1.4      2018-05-24 [1]
 vcfR               1.8.0      2018-04-17 [1]
 vctrs              0.2.0      2019-07-05 [1]
 vegan              2.5-5      2019-05-12 [1]
 viridisLite        0.3.0      2018-02-01 [1]
 webshot            0.5.1      2018-09-28 [1]
 whisker            0.3-2      2013-04-28 [1]
 withr              2.1.2      2018-03-15 [1]
 xfun               0.8        2019-06-25 [1]
 xlsx             * 0.6.1      2018-06-11 [1]
 xlsxjars         * 0.6.1      2014-08-22 [1]
 xtable             1.8-4      2019-04-21 [1]
 zeallot            0.1.0      2018-01-28 [1]
 zvau             * 0.27       2019-08-06 [1]
 source                                    
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 Github (green-striped-gecko/dartR@3f9eebd)
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 Bioconductor                              
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 Bioconductor                              
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 Github (thierrygosselin/radiator@c9804ca) 
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 Bioconductor                              
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.1)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 CRAN (R 3.6.0)                            
 Github (romunov/zvau@72f403b)             

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

[whelk.RData.zip](https://github.com/thierrygosselin/radiator/files/3494433/whelk.RData.zip)

* complete data required to reproduce the problem, a subset of it. The data remains confidential.

**Screenshots**

**Comment by thierrygosselin** [comment]
Hi Rita, 
I'll have a look at your problem today
Thanks for reporting.
Thierry

**Comment by thierrygosselin** [comment]
Hi Rita,

try updating radiator and try 2 tests with the files you provided:

1. test1
```
test1 <- radiator::filter_hwe(data = radiator.gen, interactive.filter = TRUE)
```

This is the interactive version, you will have to enter things

- y
- 4
- try 3 but you likely have to use 2 or 1 (it will ask until it found a dataset with the values)

For the function documentation:
```
?radiator::filter_hwe
```

These are the files and folders generated:

```
blacklist.markers.hwd.0.001.mid.p.value.4.hw.pop.threshold.tsv
blacklist.markers.hwd.0.05.mid.p.value.4.hw.pop.threshold.tsv
filters_parameters_20190815@1440.tsv
genotypes.summary.tsv
hw.pop.sum.tsv
hwd.helper.table.tsv
hwd.plot.blacklist.markers.pdf
hwe.manhattan.plot.pdf
hwe.ternary.plots.missing.data.pdf
radiator_filter_hwe_args_20190815@1440.tsv
tidy.filtered.hwe.0.001.mid.p.value.4.hw.pop.threshold.rad
tidy.filtered.hwe.0.05.mid.p.value.4.hw.pop.threshold.rad
whitelist.markers.hwe.0.001.mid.p.value.4.hw.pop.threshold.tsv
whitelist.markers.hwe.0.05.mid.p.value.4.hw.pop.threshold.tsv
```

2. test2 (no interaction)

```
test2 <- radiator::filter_hwe(data = radiator.gen, interactive.filter = FALSE, hw.pop.threshold = 4, midp.threshold = 1)
```


These are the files and folders generated:

```
blacklist.markers.hwd.0.001.mid.p.value.4.hw.pop.threshold.tsv
blacklist.markers.hwd.0.05.mid.p.value.4.hw.pop.threshold.tsv
filters_parameters_20190815@1441.tsv
genotypes.summary.tsv
hw.pop.sum.tsv
hwd.helper.table.tsv
hwd.plot.blacklist.markers.pdf
hwe.manhattan.plot.pdf
hwe.ternary.plots.missing.data.pdf
radiator_filter_hwe_args_20190815@1441.tsv
tidy.filtered.hwe.0.001.mid.p.value.4.hw.pop.threshold.rad
tidy.filtered.hwe.0.05.mid.p.value.4.hw.pop.threshold.rad
whitelist.markers.hwe.0.001.mid.p.value.4.hw.pop.threshold.tsv
whitelist.markers.hwe.0.05.mid.p.value.4.hw.pop.threshold.tsv
```

Please re-open the issue if your still experiencing problems
Thierry

**Comment by rcastil** [comment]
Dear Thierry,
No problems now!
Many thanks,
R
