### ISSUE TITLE
run_bayescan

### ISSUE THREAD

**Issue by rcastil** [thierrygosselin/radiator#57]
[whelk_filter.gen.zip](https://github.com/thierrygosselin/radiator/files/3512166/whelk_filter.gen.zip)

Dear Thierry,
I want to use the run_bayescan function. Apparently done everything as instructed, but I get an error... would you be able to see what went wrong?
Many thanks,
Rita

# convert genepop to genind
data.genind <- adegenet::import2genind("whelk_fitered.gen"),ncode = 2)
# convert genind to radiator
data.genind.rad <- tidy_genomic_data(data.genind,
                                  keep.allele.names = TRUE, 
                                  tidy = TRUE, 
                                  gds = TRUE,
                                  write = FALSE, verbose = TRUE)
# place bayescan in /usr/local/bin/ folder

# convert tidy into bayescan 
write_bayescan(data.genind.rad, 
               pop.select = NULL, 
               filename = "file.bayescan",
               parallel.core = parallel::detectCores() - 1
               )
run_bayescan("file.bayescan", 
             n = 5000, 
             thin = 10, 
             nbp = 20, 
             pilot = 5000,
             burn = 50000,
             pr_odds=1000,
             subsample = NULL, 
             iteration.subsample = 1,
             parallel.core = parallel::detectCores() - 1,
             bayescan.path = "/usr/local/bin/bayescan")

#######################################################################
#######################################################################

Folder created: 
radiator_bayescan_20190817@1608
For progress, look in the log file: radiator_bayescan_20190817@1608.log
Copying input BayeScan file in folder
sh: line 1: 75707 Abort trap: 6           '/usr/local/bin/bayescan' /Users/rita/Desktop/declan/radiator_bayescan_20190817@1608/file.bayescan -od /Users/rita/Desktop/declan/radiator_bayescan_20190817@1608 -all_trace -threads 3 -n 5000 -thin 10 -nbp 20 -pilot 5000 -burn 50000 -pr_odds 1000 > '/Users/rita/Desktop/declan/radiator_bayescan_20190817@1608/radiator_bayescan_20190817@1608.log' 2>&1
Importing BayeScan results
Error in if (length(x) > 1 || grepl("\n", x)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
2: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two.

**Comment by thierrygosselin** [comment]
Hi Rita,

Try this instead:

```
test1 <- radiator::run_bayescan(
  data = "file.bayescan.txt",
  n = 5000,
  thin = 10,
  nbp = 20,
  pilot = 5000,
  burn = 50000,
  pr_odds=1000,
  subsample = NULL,
  iteration.subsample = 1,
  parallel.core = parallel::detectCores() - 1,
  bayescan.path = "/usr/local/bin/bayescan"
  )
```

**Comment by rcastil** [comment]
Hi, Thierry,
Thanks, but still not working:
#######################################################################
###################### radiator::run_bayescan #########################
#######################################################################

Folder created: 
radiator_bayescan_20190819@1950
For progress, look in the log file: radiator_bayescan_20190819@1950.log
Copying input BayeScan file in folder
sh: line 1: 83870 Abort trap: 6           '/usr/local/bin/bayescan' /Users/rita/Desktop/bayes/radiator_bayescan_20190819@1950/file.bayescan.txt -od /Users/rita/Desktop/bayes/radiator_bayescan_20190819@1950 -all_trace -threads 3 -n 5000 -thin 10 -nbp 20 -pilot 5000 -burn 50000 -pr_odds 1000 > '/Users/rita/Desktop/bayes/radiator_bayescan_20190819@1950/radiator_bayescan_20190819@1950.log' 2>&1
Importing BayeScan results
Error in if (length(x) > 1 || grepl("\n", x)) { : 
  missing value where TRUE/FALSE needed

Rita

**Comment by thierrygosselin** [comment]
Have you tried in your terminal to use BayeScan to check that you installed it correctly ?

**Comment by rcastil** [comment]
🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️
Thanks,
R
