### ISSUE TITLE
detect_genomic_converter doesn't work for .tped

### ISSUE THREAD

**Issue by helgebjerck** [thierrygosselin/radiator#59]
detect_genomic_format outputs the first line of the data as the data.type if data is a plink file. This is because
file.ending <- stringi::stri_sub(str = data, from = -4, to = -1) outputs "tped" and the function expects ".tped".

This is easily fixed by making the function expect "tped"
This goes on to break both tidy_genomic_data and genomic_converter if you're working with plink files.

**Comment by thierrygosselin** [comment]
ok I'll have a look
thanks Helge

**Comment by thierrygosselin** [comment]
The new commit should fix that.
Cheers
Thierry
