### ISSUE TITLE
tidy_plink tries to merge a list and a table

### ISSUE THREAD

**Issue by helgebjerck** [thierrygosselin/radiator#60]
input %<>% dplyr::left_join(strata.df, by = "INDIVIDUALS") in the function tidy_plink produces an error as strata.df is the output of read_strata, i.e. a list. left_join can't join a list and a table. This is fixed by replacing strata.df with strata.df$strata, like so:
input %<>% dplyr::left_join(strata.df$strata, by = "INDIVIDUALS")

**Comment by thierrygosselin** [comment]
thanks for the bug detection
I'll have a look today

**Comment by thierrygosselin** [comment]
This should be fixed with the new commit
Cheers
Thierry
