### ISSUE TITLE
genomic_converter function: genlight format (originally from DART) to HapMap

### ISSUE THREAD

**Issue by LaserKate** [thierrygosselin/radiator#61]
Hi Thierry, 
Great job creating the radiator package. I only discovered it recently and still going through the functionality, but it is looking like a great resource for the community.

I was wondering if it is possible (or maybe you have already done this), to add the conversion from a genlight object as input (which you have already) to output as a Hapmap format? I realize you already have 28 output options, so maybe you don't want to add more but just a suggestion.

The reason I would like the Hapmap output is to feed this into GAPIT (package GAPIT3) to run GWAS on DART SNP data. 

I found this R script for conversion of Hapmap - - > genlight if this is helpful at all...
https://www.ideals.illinois.edu/bitstream/handle/2142/49963/hapMap2genlight.R?sequence=10&isAllowed=y

# Lindsay V. Clark, 18 March 2013
# R function to import data from TASSEL's HapMap format to adegenet's
# genlight format.
# On my computer (64 bit OS, 8Gb RAM, 2.7 GHz processor) the function takes
# approximately 8e-06 seconds per individual per locus to run.
# (Big datasets could take a few minutes.)
# At this time it does not import chromosome position information, but it could
# be modified to do so fairly easily.

# Example use:
# mydata <- hapMap2genlight("HapMap.hmp.txt")

hapMap2genlight <- function(file){
    require(adegenet)
    hapmap <- read.table(file, header=TRUE, row.names=1, sep="\t",
                     stringsAsFactors=FALSE)[,-(2:10)]
    samples <- names(hapmap)[-1]
    loci <- row.names(hapmap)

    # set up conversion table
    s <- as.integer(c(0,1,2,NA))
    ac <- s
    ag <- s
    at <- s
    cg <- s
    ct <- s
    gt <- s
    names(ac) <- c("A","M","C","N")
    names(ag) <- c("A","R","G","N")
    names(at) <- c("A","W","T","N")
    names(cg) <- c("C","S","G","N")
    names(ct) <- c("C","Y","T","N")
    names(gt) <- c("G","K","T","N")
    conv <- list(ac,ac,ag,ag,at,at,cg,cg,ct,ct,gt,gt)
    names(conv) <- c("A/C","C/A","A/G","G/A","A/T","T/A","C/G","G/C",
                     "C/T","T/C","G/T","T/G")

    # Pull out and convert genotypes
    S <- length(samples)
    SBlist <- vector(mode="list",S)   # set up list of SNPbin objects
    for(i in 1:S){
        mygen <- mapply(function(type,gen) unname(conv[[type]][gen]),
                        type=hapmap[[1]], gen=hapmap[[i+1]],
                        SIMPLIFY=TRUE, USE.NAMES=FALSE)
        # create SNPbin object for this individual
        SBlist[[i]] <- new("SNPbin", mygen)
    }

    # make genlight object
    x <- new("genlight", SBlist)
    locNames(x) <- loci
    indNames(x) <- samples

    return(x)
}

**Comment by thierrygosselin** [comment]
Hi Kate,

Having HapMap as an output shouldn't be a problem.

**Comment by LaserKate** [comment]
Hi Thierry, That sounds great, thank you! Looking forward to it as I am currently working in Numeric Genotype Format and it is not optimal :)
cheers,
Kate

**Comment by thierrygosselin** [comment]
Hi Kate, the latest radiator commit/version as a new `hapmap` output format ([ref here](https://thierrygosselin.github.io/radiator/reference/write_hapmap.html)).

Look carefully at the output and re-open the issue if you think something is wrong. Currently, the missing genotypes are coded `NA`, not sure if it's ok, NCBI as [retired](https://www.ncbi.nlm.nih.gov/variation/news/NCBI_retiring_HapMap/) the project/format so it's difficult to find reliable info on it.


Also, just as side note comments: if your `genlight` data comes from DArT file converted through *dartR package*, you might want to run [filter_rad](https://thierrygosselin.github.io/radiator/reference/filter_rad.html) on it using dart original file or this genlight of yours if it's not possible.

Cheers
Thierry

**Comment by LaserKate** [comment]
Hi Thierry, 
Thank you for adding this functionality!! I have tested it with DArT format files and the output appears to be correct. I will continue to test it through the full statistical pipeline and re-open if something comes up. Thanks again for your work on this!!
