### ISSUE TITLE
filter_genotyping can not handle a large number of populations - limitsize defaults to FALSE in ggsave

### ISSUE THREAD

**Issue by zjons** [thierrygosselin/radiator#62]
When running the filter_rad pipeline with a large number of populations (in my case 34) everything runs smoothly until the radiator::filter_genotyping function is called.  Then radiator quits with an error:

>   Step 1. Missing visualization and helper table
>   
>   Generating statistics
>   Generating missingness/genotyping helper table...
>   File written: markers.pop.missing.helper.table.tsv
>   Error: Dimensions exceed 50 inches (height and width are specified in 'cm' not pixels). If you're sure you want a plot that big, use `limitsize = FALSE`.
>   
>   Computation time, overall: 76 sec
>   ######################## completed filter_genotyping ###########################
>   
>   Computation time, overall: 3519 sec
>   ############################# completed filter_rad #############################

I tracked this down to a call to ggsave in filter_genotyping() and fixed it by setting the limitsize flag to FALSE.

`    # save
    ggplot2::ggsave(
      filename = file.path(path.folder, "markers.genotyping.helper.plot.pdf"),
      plot = markers.plot,
      width = 20 + 3 * n.pop,
      height = 15,
      dpi = 300,
      units = "cm",
      limitsize = FALSE,
      useDingbats = FALSE)
    helper.table <- markers.plot <- NULL
    if (verbose) message("Files written: helper tables and plots")
    `

It would be nice to fix this since others are bound to run into this sooner or later.

Another small suggestion while I'm at it.  It would be nice to check whether SNPRelate is installed/loaded right at the start in case one intends to filter by long distance LD.

And finally.  Thanks for a very user friendly and useful package !

**Comment by thierrygosselin** [comment]
Dear Zophonías, thanks for reporting the bug. It was tested with 20 populations or so and this one escaped me when I changed the rules for the output. Let me know if the rendering is ok or if it need to be optimized.

The current rule is:
```
width = 20 + 3 * n.pop
height = 15
```

we could adjust the `3` here. For 1 pop the minimum is thus 23 (to account for a number of things beyond the scope of this issue.

It produce very large PDF, but it's nice to zoom or look for general patterns.

As for the SNPRelate dependency, it's a good point and I added a check.

Best,
Thierry

p.s. I love Iceland!
I did the west fjord and the entire island by bike and last week end I was telling my climbing partner that I would gladly go back to do a second time the Landmannalaugar trek
