### ISSUE TITLE
Error with genomic_converter for VCF to Bayescan

### ISSUE THREAD

**Issue by ksil91** [thierrygosselin/radiator#63]
I am trying to convert a VCF file to bayescan format using R 3.5.2 on Ubuntu. The VCF was generated using QCTOOL by converting a GEN file to VCF. The conversion works up until right after "Scanning for monomorphic markers", when I get:  
`Error in .f(.x[[i]], ...): object 'GT' not found`

Here is my command:  
`rad.filt <- genomic_converter(data="HCSS_Afilt32m70_01_pp90_m75B.recode.vcf", strata="SSHCfiltNreps.strata", output= "bayescan", filename= "test", parallel.core = 2)`

The output:
```
Execution date@time: 20190909@1044
Folder created: 07_radiator_genomic_converter_20190909@1044
Function call and arguments stored in: radiator_genomic_converter_args_20190909@1044.tsv
Filters parameters file generated: filters_parameters_20190909@1044.tsv

Importing data

Reading VCF
Data summary: 
    number of samples: 114
    number of markers: 5017
done! timing: 0 sec

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 5 / 16

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0
Generating individual stats...
Generating markers stats...

Number of chromosome/contig/scaffold: 1
Number of locus: 3276
Number of markers: 5001
Number of populations: 2
Number of individuals: 114

Number of ind/pop:
HC = 57
SS = 57

Number of duplicate id: 0
radiator Genomic Data Structure (GDS) file: radiator_20190909@1044.gds

Genotypes formats generated with 5001 SNPs: 
    GT_BIN (the dosage of ALT allele: 0, 1, 2 NA): TRUE
    GT_VCF (the genotype coding VCFs: 0/0, 0/1, 1/1, ./.): TRUE
    GT_VCF_NUC (the genotype coding in VCFs, but with nucleotides: A/C, ./.): TRUE
    GT (the genotype coding 'a la genepop': 001002, 001001, 000000): TRUE
Synchronizing data and strata...
    Number of strata: 2
    Number of individuals: 114

Tidy data file written: radiator_20190909@1044.rad

Writing tidy data set:
test.rad

Preparing data for output

Data is bi-allelic
Generating BayeScan object
Generating BayeScan file...
################################################################################
######################## radiator::filter_common_markers #######################
################################################################################
Execution date@time: 20190909@1044
Scanning for common markers...

Computation time, overall: 1 sec
####################### filter_common_markers completed ########################
################################################################################
########################### radiator::filter_monomorphic #######################
################################################################################
Execution date@time: 20190909@1044
Scanning for monomorphic markers...

Computation time, overall: 0 sec
######################## filter_monomorphic completed ##########################
Error in .f(.x[[i]], ...): object 'GT' not found
Traceback:

1. genomic_converter(data = "HCSS_Afilt32m70_01_pp90_m75B.recode.vcf", 
 .     strata = "SSHCfiltNreps.strata", output = "bayescan", filename = "test", 
 .     parallel.core = 2)
2. radiator::write_bayescan(data = input, pop.select = pop.select, 
 .     snp.ld = snp.ld, filename = filename)
3. dplyr::select(data, MARKERS, INDIVIDUALS, POP_ID, GT)
4. select.data.frame(data, MARKERS, INDIVIDUALS, POP_ID, GT)
5. tidyselect::vars_select(tbl_vars(.data), !!!enquos(...))
6. vars_select_eval(.vars, quos)
7. map_if(quos, !is_helper, eval_tidy, mask)
8. map(.x[sel], .f, ...)
9. .f(.x[[i]], ...)
Computation time, overall: 9 sec  
```

My VCF file header and 1st line:
##fileformat=VCFv4.2
##FORMAT=<ID=GP,Type=Float,Number=G,Description="Genotype call probabilities">
##FORMAT=<ID=GT,Type=String,Number=1,Description="Genotype call probabilities, threshholded at 0.90">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HC1_11	HC1_12	HC1_13	HC1_14_L5	HC1_15	HC1_18	HC1_19	HC1_2B_L5	HC1_3	HC1_4	HC1_9	HC2_1	HC2_10	HC2_11_L5	HC2_12	HC2_13	HC2_14	HC2_15A_L5	HC2_16	HC2_17B	HC2_18	HC2_19	HC2_2	HC2_20	HC2_3	HC2_4	HC2_5_L5	HC2_7	HC2_9	HC3_1	HC3_10	HC3_11	HC3_12	HC3_13	HC3_14_L5	HC3_16	HC3_18	HC3_2	HC3_3	HC3_4	HC3_5_L5B	HC3_6	HC3_7	HC3_8	HC3_9	HC4_17_L5	HC4_1A	HC4_2	HC4_4B	HC4_5	HC4_6	HC5_10	HC5_11	HC5_14	HC5_15	HC5_16	HC5_3_L5	SS1_1	SS1_10_L5	SS1_12	SS1_14	SS1_17_L5	SS1_19	SS1_2	SS1_20_L5	SS1_5	SS1_6_L5	SS1_7_L5	SS1_8	SS2_10_L5	SS2_12A	SS2_13_L5	SS2_14_L5	SS2_15	SS2_16	SS2_17	SS2_18_L5	SS2_19	SS2_4B	SS2_5B_L5	SS2_9_L5	SS3_1	SS3_11	SS3_13	SS3_14	SS3_15	SS3_16	SS3_17	SS3_19	SS3_2	SS3_20	SS3_3	SS3_4_L5	SS3_5D	SS3_6	SS3_7	SS3_8	SS3_9	SS4_1	SS4_4	SS5_10_L5	SS5_11	SS5_12	SS5_13B	SS5_15	SS5_18	SS5_19	SS5_3_L5	SS5_4	SS5_5	SS5_6	SS5_7	SS5_8_L5	SS5_9
Contig0	109103	Contig0:109103	C	G	.	.	.	GT:GP	0/1:0,1,0	0/0:1,0,0	1/1:0,0,1	0/0:1,0,0	0/1:0,0.99948,0.00052	0/1:0,1,0	0/0:0.999999,1e-06,0	0/1:4e-06,0.999996,0	0/0:1,0,0	0/1:0,1,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999995,5e-06,0	0/1:0,1,0	0/0:1,0,0	0/1:0,1,0	0/0:1,0,0	0/1:0,1,0	0/1:0,1,0	0/0:1,0,0	0/0:1,0,0	./.:0.854604,0.145386,1e-05	0/1:1.2e-05,0.999988,0	0/0:0.99821,0.00179,0	0/0:1,0,0	0/0:0.999945,5.5e-05,0	0/1:1e-06,0.999999,0	0/0:0.999999,1e-06,0	1/1:0,9e-05,0.99991	0/1:1.2e-05,0.999988,0	0/1:0,1,0	0/0:1,0,0	0/0:0.99999,1e-05,0	0/0:0.998673,0.001327,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	./.:0.698975,0.301025,0	0/0:0.999958,4.2e-05,0	0/0:0.999917,8.3e-05,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999999,1e-06,0	0/1:0,1,0	0/0:1,0,0	0/0:1,0,0	0/1:7e-06,0.999993,0	0/1:0,1,0	0/0:0.999979,2.1e-05,0	0/0:0.999917,8.3e-05,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/1:0.000226,0.999774,0	1/1:0,0.011349,0.988651	0/0:1,0,0	0/1:5e-06,0.999995,0	0/0:1,0,0	0/1:0.000696,0.999304,0	0/1:0.000211,0.999789,0	0/1:0,1,0	0/0:0.99319,0.00681,0	./.:0.013648,0.735946,0.250406	0/1:0,0.998312,0.001688	./.:0.013648,0.735946,0.250406	0/0:1,0,0	0/1:4e-06,0.999996,0	0/1:6e-06,0.999994,0	./.:0.556711,0.378839,0.064449	0/0:0.997349,0.002651,0	0/0:1,0,0	0/0:1,0,0	0/0:0.986514,0.013486,0	0/0:1,0,0	0/1:0,1,0	0/0:0.999999,1e-06,0	0/1:0,1,0	./.:0.556711,0.378839,0.064449	0/0:1,0,0	./.:0.745726,0.253729,0.000545	0/1:0,1,0	1/1:0,1e-06,0.999999	0/0:0.99766,0.00234,0	0/1:0,0.999957,4.3e-05	0/0:0.959206,0.040794,0	./.:0.490905,0.509095,0	0/0:1,0,0	0/0:0.999834,0.000166,0	0/0:0.99999,1e-05,0	0/0:0.999136,0.000864,0	1/1:0,0.000359,0.999641	0/1:0,1,0	./.:0.013648,0.735946,0.250406	0/1:0,1,0	0/0:0.979178,0.020822,0	0/1:1.4e-05,0.999986,0	0/1:0.000112,0.999888,0	0/0:1,0,0	./.:0,0.155178,0.844822	0/1:0,1,0	0/1:0,1,0	0/0:1,0,0	1/1:0,6e-06,0.999994	0/0:1,0,0	0/1:0,1,0	0/0:1,0,0	1/1:0,9e-05,0.99991	0/0:1,0,0	0/1:0,1,0	0/0:0.979178,0.020822,0	0/0:1,0,0
Contig0	109119	Contig0:109119	T	C	.	.	.	GT:GP	0/1:0,1,0	0/0:1,0,0	1/1:0,0,1	0/0:1,0,0	0/1:0,1,0	0/0:0.999974,2.6e-05,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999999,1e-06,0	0/0:0.900787,0.099213,0	0/0:1,0,0	0/1:0,1,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.97402,0.02598,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	1/1:0,0.000572,0.999428	0/0:1,0,0	0/1:0,1,0	0/0:1,0,0	0/0:0.999998,2e-06,0	0/0:0.999792,0.000208,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999583,0.000417,0	0/0:0.999987,1.3e-05,0	0/0:0.999987,1.3e-05,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/1:0,1,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/1:0,1,0	0/0:0.999997,3e-06,0	0/0:0.999987,1.3e-05,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/1:0.00144,0.99856,0	0/0:0.999792,0.000208,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999993,7e-06,0	0/0:0.949339,0.050644,1.7e-05	0/0:0.999583,0.000417,0	0/0:0.949339,0.050644,1.7e-05	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.901275,0.09616,0.002565	0/0:0.999583,0.000417,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999987,1.3e-05,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999993,7e-06,0	0/0:0.901275,0.09616,0.002565	0/0:1,0,0	0/0:0.949339,0.050644,1.7e-05	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999792,0.000208,0	0/0:0.993376,0.006624,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999974,2.6e-05,0	0/0:0.999998,2e-06,0	0/0:0.999999,1e-06,0	0/0:0.999993,7e-06,0	0/0:1,0,0	0/0:0.949339,0.050644,1.7e-05	0/0:1,0,0	0/0:0.996677,0.003323,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.996677,0.003323,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:1,0,0	0/0:0.999974,2.6e-05,0	0/0:1,0,0	0/0:0.999998,2e-06,0	0/0:1,0,0	0/0:1,0,0	0/0:0.996677,0.003323,0	0/0:1,0,0

**Comment by thierrygosselin** [comment]
Hi Katherine,

Thanks for reporting the issue.
Could you try re-installing radiator and re-running your code above?

**Comment by thierrygosselin** [comment]
And if it still doesn’t work, send me the recoded vcf and strata file, I’ll try to reproduce the bug on my end

**Comment by thierrygosselin** [comment]
Dear Katherine, feel free to re-open this issue if you're still experiencing problems.

**Comment by ksil91** [comment]
Hello, sorry for the delay. I reinstalled and still had the same issue. Emailing you the VCF and Strata file now!

**Comment by thierrygosselin** [comment]
Hi Katherine,

I tried with the data you sent and on my end everything is working correctly.

1. Re-install radiator by following instructions [here](https://thierrygosselin.github.io/radiator/#installation)

**You have to re-start R**


2. 2 Tests:


With your data check that this command gives you something similar to what's below

```
test1 <- radiator::read_vcf(data = "HCSS_Afilt32m70_01_pp90_m75B.recode.vcf", strata = "SSHCfiltNreps.strata")
```

```
Execution date@time: 20190916@1315
Folder created: read_vcf_20190916@1315
Function call and arguments stored in: radiator_read_vcf_args_20190916@1315.tsv
File written: random.seed (849848)

Reading VCF
Data summary: 
    number of samples: 114
    number of markers: 5017
done! timing: 2 sec


File written: radiator_20190916@1315.gds

Analyzing the data...
VCF source: unknown
Data is bi-allelic
Cleaning VCF's sample names
Synchronizing data and strata...
    Number of strata: 2
    Number of individuals: 114
Reads assembly: de novo
Filters parameters file generated: filters_parameters_20190916@1315.tsv
Filters parameters file: initiated and updated
################################################################################
########################### radiator::filter_monomorphic #######################
################################################################################
Execution date@time: 20190916@1315
Function call and arguments stored in: radiator_filter_monomorphic_args_20190916@1315.tsv
Filters parameters file: initiated
File written: blacklist.monomorphic.markers_20190916@1315.tsv
Synchronizing markers.meta
File written: whitelist.polymorphic.markers_20190916@1315.tsv
Filters parameters file: updated
################################### RESULTS ####################################

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Before: 114 / 2 / 1 / 3281 / 5017
    Blacklisted: 0 / 0 / 0 / 5 / 16
    After: 114 / 2 / 1 / 3276 / 5001

Computation time, overall: 0 sec
######################## filter_monomorphic completed ##########################
################################################################################
######################## radiator::filter_common_markers #######################
################################################################################
Execution date@time: 20190916@1315
Function call and arguments stored in: radiator_filter_common_markers_args_20190916@1315.tsv
Filters parameters file: initiated
Scanning for common markers...
Generating UpSet plot to visualize markers in common
File written: whitelist.common.markers_20190916@1315.tsv
Filters parameters file: updated
################################### RESULTS ####################################

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Before: 114 / 2 / 1 / 3276 / 5001
    Blacklisted: 0 / 0 / 0 / 0 / 0
    After: 114 / 2 / 1 / 3276 / 5001

Computation time, overall: 1 sec
####################### filter_common_markers completed ########################

Preparing output files...
File written: whitelist.markers.tsv
File written: blacklist.markers.tsv
Writing the filtered strata: strata.filtered.tsvstrata.filtered.tsv

Generating statistics after filtering
Generating individual stats...
File written: individuals qc info and stats summary
File written: individuals qc plot
Generating markers stats...
################################### SUMMARY ####################################


Summary (AFTER filtering):
Missing data: 
    markers: 0.04
    individuals: 0.04


Number of chromosome/contig/scaffold: 1
Number of locus: 3276
Number of markers: 5001
Number of populations: 2
Number of individuals: 114

Number of ind/pop:
HC = 57
SS = 57

Number of duplicate id: 0
radiator Genomic Data Structure (GDS) file: radiator_20190916@1315.gds

Computation time, overall: 8 sec
############################## completed read_vcf ##############################
```


```
test2 <- radiator::genomic_converter(
    data = "HCSS_Afilt32m70_01_pp90_m75B.recode.vcf",
    strata = "SSHCfiltNreps.strata",
    output = "bayescan"
  )
```

This should result in 3 files related to bayescan:

```
1. radiator_data_20190916@1318.txt
2. radiator_data_20190916@1318_pop_dictionary.tsv
3. radiator_data_20190916@1318_markers_dictionary.tsv
```

The first one is the one required by bayescan, the 2 others are to help you translated your pop id and marker id names.


Run these 2 commands and copy/paste the results here if you're still having a problem

**Comment by ksil91** [comment]
Thank you so much for checking this, I got it to work and the problem was on my end. The issue was with installation locations for my computer's version of R and IRKernal in Jupyter Lab (which I thought I had solved but got wonky again after a recent update). Great package, thanks for all your hard work on it!
