### ISSUE TITLE
issue with genomic_converter : "Error: Wrong genotype format: nucleotide information is required"

### ISSUE THREAD

**Issue by BiodivGenomic** [thierrygosselin/radiator#64]
Hello,
I'm trying to use the genomic_converter function, and I got an error I cannot fix... I want to convert a vcf file to finestructure, and I tried different input format (I don't  have only vcf, but I cannot generate new results file as I didn't perform the RAD assembly myself), only the vcf went far enough in the process. Anyway, I got this error:
"Error: Wrong genotype format: nucleotide information is required
try running the function radiator::tidy_genomic_data
Call `rlang::last_error()` to see a backtrace"

As nucleotides were not coded in the structure-like format I have, that's why I decided to go with the vcf. Obviously I tried to run radiator::tidy_genomic_data that worked well and gave me no errors. However, even after running tidy_genomic, I still got the same error...
I have nucleotides (reference and alternative) in my vcf, so I don't understand what could be wrong... 
Thanks in advance for any help !
Damien

**Comment by thierrygosselin** [comment]
Hi Damien, I’ll have a look with some of my VCFs but if I cannot reproduce your error, I might need yours.
Cheers
Thierry

**Comment by BiodivGenomic** [comment]
Hi, thank you for your quick reply. I sent you my vcf file through wetransfer.
Thanks in advance !
Damien

**Comment by thierrygosselin** [comment]
Hi Damien
Try the latest commit/version of radiator (re-install is necessary). It should now work. Re-open the issue if you're still having a problem.
Thanks
thierry
