### ISSUE TITLE
Unable to complete the function filter_genotyping

### ISSUE THREAD

**Issue by marclagu** [thierrygosselin/radiator#66]
Dear Thierry,
first of all, I would like to thank you for developing such a great tool. I started using it a few weeks ago and never encountered any problems.
However, after updating several R packages now the command "filter_rad" is unable to complete the "filter_genotyping" step.
Using data that I filtered successfully a few weeks ago now I get the error message:

**Generating statistics
Generating missingness/genotyping helper table...
Error in is_missing(.key) : object 'id.select' not found**

The output of devtools::session_info() is:
>─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Ubuntu 18.04.3 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Atlantic/Reykjavik          
 date     2019-09-18                  

>─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package          * version   date       lib source                                   
 assertthat         0.2.1     2019-03-21 [1] CRAN (R 3.6.0)                           
 backports          1.1.4     2019-04-10 [1] CRAN (R 3.6.0)                           
 Biobase            2.44.0    2019-05-02 [1] Bioconductor                             
 BiocGenerics       0.30.0    2019-05-02 [1] Bioconductor                             
 Biostrings         2.52.0    2019-05-02 [1] Bioconductor                             
 bitops             1.0-6     2013-08-17 [1] CRAN (R 3.6.0)                           
 boot               1.3-23    2019-07-05 [4] CRAN (R 3.6.1)                           
 broom              0.5.2     2019-04-07 [1] CRAN (R 3.6.0)                           
 callr              3.3.1     2019-07-18 [1] CRAN (R 3.6.1)                           
 cli                1.1.0     2019-03-19 [1] CRAN (R 3.6.0)                           
 colorspace         1.4-1     2019-03-18 [1] CRAN (R 3.6.1)                           
 crayon             1.3.4     2017-09-16 [1] CRAN (R 3.6.0)                           
 data.table         1.12.2    2019-04-07 [1] CRAN (R 3.6.0)                           
 desc               1.2.0     2018-05-01 [1] CRAN (R 3.6.0)                           
 devtools           2.2.0     2019-09-07 [1] CRAN (R 3.6.1)                           
 digest             0.6.20    2019-07-04 [1] CRAN (R 3.6.1)                           
 dplyr              0.8.3     2019-07-04 [1] CRAN (R 3.6.1)                           
 DT                 0.9       2019-09-17 [1] CRAN (R 3.6.1)                           
 ellipsis           0.2.0.1   2019-07-02 [1] CRAN (R 3.6.1)                           
 fs                 1.3.1     2019-05-06 [1] CRAN (R 3.6.0)                           
 gdsfmt             1.21.1    2019-09-18 [1] Github (zhengxwen/gdsfmt@e906a2b)        
 generics           0.0.2     2018-11-29 [1] CRAN (R 3.6.0)                           
 GenomeInfoDb       1.20.0    2019-05-02 [1] Bioconductor                             
 GenomeInfoDbData   1.2.1     2019-07-16 [1] Bioconductor                             
 GenomicRanges      1.36.1    2019-09-06 [1] Bioconductor                             
 ggplot2            3.2.1     2019-08-10 [1] CRAN (R 3.6.1)                           
 glue               1.3.1     2019-03-12 [1] CRAN (R 3.6.0)                           
 gridExtra          2.3       2017-09-09 [1] CRAN (R 3.6.1)                           
 gtable             0.3.0     2019-03-25 [1] CRAN (R 3.6.1)                           
 GWASExactHW        1.01      2013-01-05 [1] CRAN (R 3.6.0)                           
 hms                0.5.1     2019-08-23 [1] CRAN (R 3.6.1)                           
 htmltools          0.3.6     2017-04-28 [1] CRAN (R 3.6.0)                           
 htmlwidgets        1.3       2018-09-30 [1] CRAN (R 3.6.0)                           
 IRanges            2.18.2    2019-08-24 [1] Bioconductor                             
 jomo               2.6-9     2019-07-29 [1] CRAN (R 3.6.1)                           
 labeling           0.3       2014-08-23 [1] CRAN (R 3.6.0)                           
 lattice            0.20-38   2018-11-04 [1] CRAN (R 3.6.1)                           
 lazyeval           0.2.2     2019-03-15 [1] CRAN (R 3.6.0)                           
 lifecycle          0.1.0     2019-08-01 [1] CRAN (R 3.6.1)                           
 lme4               1.1-21    2019-03-05 [1] CRAN (R 3.6.0)                           
 logistf            1.23      2018-07-19 [1] CRAN (R 3.6.0)                           
 magrittr           1.5       2014-11-22 [1] CRAN (R 3.6.0)                           
 MASS               7.3-51.4  2019-04-26 [1] CRAN (R 3.6.1)                           
 Matrix             1.2-17    2019-03-22 [4] CRAN (R 3.6.1)                           
 memoise            1.1.0     2017-04-21 [1] CRAN (R 3.6.0)                           
 mgcv               1.8-28    2019-03-21 [4] CRAN (R 3.6.1)                           
 mice               3.6.0     2019-07-10 [1] CRAN (R 3.6.1)                           
 minqa              1.2.4     2014-10-09 [1] CRAN (R 3.6.0)                           
 mitml              0.3-7     2019-01-07 [1] CRAN (R 3.6.0)                           
 munsell            0.5.0     2018-06-12 [1] CRAN (R 3.6.0)                           
 nlme               3.1-141   2019-08-01 [4] CRAN (R 3.6.1)                           
 nloptr             1.2.1     2018-10-03 [1] CRAN (R 3.6.0)                           
 nnet               7.3-12    2016-02-02 [4] CRAN (R 3.5.0)                           
 pan                1.6       2018-06-29 [1] CRAN (R 3.6.0)                           
 pillar             1.4.2     2019-06-29 [1] CRAN (R 3.6.1)                           
 pkgbuild           1.0.5     2019-08-26 [1] CRAN (R 3.6.1)                           
 pkgconfig          2.0.2     2018-08-16 [1] CRAN (R 3.6.0)                           
 pkgload            1.0.2     2018-10-29 [1] CRAN (R 3.6.0)                           
 plyr               1.8.4     2016-06-08 [1] CRAN (R 3.6.0)                           
 prettyunits        1.0.2     2015-07-13 [1] CRAN (R 3.6.0)                           
 processx           3.4.1     2019-07-18 [1] CRAN (R 3.6.1)                           
 ps                 1.3.0     2018-12-21 [1] CRAN (R 3.6.0)                           
 purrr              0.3.2     2019-03-15 [1] CRAN (R 3.6.0)                           
 R6                 2.4.0     2019-02-14 [1] CRAN (R 3.6.0)                           
 radiator         * 1.1.2     2019-09-18 [1] Github (thierrygosselin/radiator@672d48f)
 Rcpp               1.0.2     2019-07-25 [1] CRAN (R 3.6.1)                           
 RCurl              1.95-4.12 2019-03-04 [1] CRAN (R 3.6.0)                           
 readr              1.3.1     2018-12-21 [1] CRAN (R 3.6.0)                           
 remotes            2.1.0     2019-06-24 [1] CRAN (R 3.6.1)                           
 reshape2           1.4.3     2017-12-11 [1] CRAN (R 3.6.0)                           
 rlang              0.4.0     2019-06-25 [1] CRAN (R 3.6.1)                           
 rpart              4.1-15    2019-04-12 [4] CRAN (R 3.6.1)                           
 rprojroot          1.3-2     2018-01-03 [1] CRAN (R 3.6.0)                           
 rstudioapi         0.10      2019-03-19 [1] CRAN (R 3.6.0)                           
 S4Vectors          0.22.1    2019-09-09 [1] Bioconductor                             
 scales             1.0.0     2018-08-09 [1] CRAN (R 3.6.0)                           
 SeqArray           1.24.2    2019-07-12 [1] Bioconductor                             
 SeqVarTools        1.22.0    2019-05-02 [1] Bioconductor                             
 sessioninfo        1.1.1     2018-11-05 [1] CRAN (R 3.6.0)                           
 stringi            1.4.3     2019-03-12 [1] CRAN (R 3.6.0)                           
 stringr            1.4.0     2019-02-10 [1] CRAN (R 3.6.0)                           
 survival           2.44-1.1  2019-04-01 [4] CRAN (R 3.6.1)                           
 testthat           2.2.1     2019-07-25 [1] CRAN (R 3.6.1)                           
 tibble             2.1.3     2019-06-06 [1] CRAN (R 3.6.0)                           
 tidyr              1.0.0     2019-09-11 [1] CRAN (R 3.6.1)                           
 tidyselect         0.2.5     2018-10-11 [1] CRAN (R 3.6.0)                           
 UpSetR             1.4.0     2019-05-22 [1] CRAN (R 3.6.1)                           
 usethis            1.5.1     2019-07-04 [1] CRAN (R 3.6.1)                           
 vctrs              0.2.0     2019-07-05 [1] CRAN (R 3.6.1)                           
 withr              2.1.2     2018-03-15 [1] CRAN (R 3.6.0)                           
 XVector            0.24.0    2019-05-02 [1] Bioconductor                             
 zeallot            0.1.0     2018-01-28 [1] CRAN (R 3.6.0)                           
 zlibbioc           1.30.0    2019-05-02 [1] Bioconductor                             

>[1] /home/marcos/R/x86_64-pc-linux-gnu-library/3.6
>[2] /usr/local/lib/R/site-library
>[3] /usr/lib/R/site-library
>[4] /usr/lib/R/library

The command I use:
data <- radiator::filter_rad(
  data = "populations.snps.vcf",
  strata = "popmap.strata.tsv",
  output = c("vcf", "genind", "colony", "hierfstat", "SNPrelate", "pcadapt", "related", "genepop", "plink")
)

I am attaching the first 5000 lines of the vcf file generated by STACKS that I used as well as the strata file so that you can check their format. Again, I used these data last week and everything worked perfectly.
Thank you very much for your help in advance!
Kind regards,

Marcos
[subset_data.zip](https://github.com/thierrygosselin/radiator/files/3628480/subset_data.zip)

**Comment by thierrygosselin** [comment]
Hi Marcos
Thanks for reporting the problem
I’ll have a look in a few hours
Best
Thierry

**Comment by thierrygosselin** [comment]
Hi Marcos,

I was unable to reproduce the error with your dataset (it complete all the way to the end).
Try re-installing radiator and start a new fresh R session.
Let me know how this goes.
Thierry

**Comment by marclagu** [comment]
Hi Thierry,
thank you for your response. I removed 'radiator' and re-installed it but I keep getting the same error. This is very odd. Could the installation of other R packages have messed something up? I will ask around to see if any colleagues have encountered similar problems. I will keep you posted.
Cheers,
Marcos

**Comment by thierrygosselin** [comment]
Did you re-start R ? otherwise your session will always keep the previous version.

**Comment by marclagu** [comment]
Yes, I did re-start R. I also tried uninstalling not only 'radiator' but also all its dependencies, re-starting the session, and installing everything again. Still, the program filter_rad manages to run smoothly until after it is done with filter_coverage and then it stops when trying to initiate filter_genotyping with the same error message:

>Step 1. Missing visualization and helper table

>Generating statistics
>Generating missingness/genotyping helper table...
>Error in is_missing(.key) : object 'id.select' not found

I also tried running filter_genotyping on its own but I end up in the same error.
I'll keep on trying.
-Marcos

**Comment by ksil91** [comment]
[Silliman_subset.zip](https://github.com/thierrygosselin/radiator/files/3659014/Silliman_subset.zip)
I am getting the same error with this command (I also reinstalled and reopened R) :
`data = read_vcf("../populations.snps.vcf", strata = "../../NFLDB.strata",
        vcf.stats = TRUE, parallel.core = 4, filter.common.markers = F, filter.genotyping = 15, filename= "filtered")`
Output: 
`Reading VCF
Data summary: 
    number of samples: 144
    number of markers: 30942
done! timing: 5 sec


File written: filtered_20190926@1143.gds

Analyzing the data...
VCF source: Stacks v2.4
Data is bi-allelic
Cleaning VCF's sample names
Synchronizing data and strata...
    Number of strata: 4
    Number of individuals: 144
Reads assembly: de novo
Filters parameters file generated: filters_parameters_20190926@1143.tsv
Filters parameters file: initiated and updated
################################################################################
########################### radiator::filter_monomorphic #######################
################################################################################
Execution date@time: 20190926@1143
Function call and arguments stored in: radiator_filter_monomorphic_args_20190926@1143.tsv
Filters parameters file: initiated
File written: whitelist.polymorphic.markers_20190926@1143.tsv
Filters parameters file: updated
################################### RESULTS ####################################

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Before: 144 / 4 / 1 / 14398 / 30942
    Blacklisted: 0 / 0 / 0 / 0 / 0
    After: 144 / 4 / 1 / 14398 / 30942

Computation time, overall: 0 sec
######################## filter_monomorphic completed ##########################
################################################################################
######################### radiator::filter_genotyping ##########################
################################################################################
Execution date@time: 20190926@1143
Function call and arguments stored in: radiator_filter_genotyping_args_20190926@1143.tsv
Importing data ...
Filters parameters file: initiated
Generating statistics
Generating missingness/genotyping helper table...
Error in is_missing(.key): object 'id.select' not found
Traceback:

1. read_vcf("../populations.snps.vcf", strata = "../../NFLDB.strata", 
 .     vcf.stats = TRUE, parallel.core = 4, filter.common.markers = F, 
 .     filter.genotyping = 15, filename = "filtered")
2. filter_genotyping(data = gds, interactive.filter = FALSE, filter.genotyping = filter.genotyping, 
 .     filename = NULL, parallel.core = parallel.core, verbose = verbose, 
 .     parameters = filters.parameters, path.folder = wf, internal = FALSE)
3. missing_per_pop(gds = data, strata = strata, parallel.core = parallel.core)
4. strata %>% dplyr::group_by(STRATA) %>% tidyr::nest(data = ., 
 .     .key = id.select) %>% dplyr::mutate(MISSING_POP = purrr::map(.x = .$id.select, 
 .     .f = missing_pop, gds = gds, markers.meta = markers.meta, 
 .     parallel.core = parallel.core)) %>% tidyr::unnest(data = ., 
 .     MISSING_POP) %>% dplyr::mutate(BLACKLISTED_MARKERS = n.markers - 
 .     WHITELISTED_MARKERS)
5. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
6. eval(quote(`_fseq`(`_lhs`)), env, env)
7. eval(quote(`_fseq`(`_lhs`)), env, env)
8. `_fseq`(`_lhs`)
9. freduce(value, `_function_list`)
10. function_list[[i]](value)
11. tidyr::nest(data = ., .key = id.select)
12. nest.grouped_df(data = ., .key = id.select)
13. NextMethod()
14. nest.tbl_df(data = ., .key = id.select)
15. check_key(.key)
16. is_missing(.key)
`
This is a VCF generated by reference-aligned Stacks v2.4. Oddly, radiator seems to be interpreting the VCF as coming from a de novo assembly.
Attached are my input files (first 5000 snps in vcf).

**Comment by thierrygosselin** [comment]
Sorry for the long delay in response,
I'll have a look.
radiator should have no problem differentiating _de novo_ or reference assisted stacks data...

**Comment by thierrygosselin** [comment]
I'm not able to reproduce the error with Katherine's dataset...weird. 

But I do get the _de novo_ detection problem: will fix this
And including the filtering inside `read_vcf` doesn't seem to be filtering anything: will look into it

**Comment by thierrygosselin** [comment]
After updating all `tidyverse` packages I'm now getting the same error about `id.select not found`

**Comment by thierrygosselin** [comment]
The latest commit should fix issues mentioned above.

Note that there was a documentation error in `read_vcf` describing in the [advance-mode](https://thierrygosselin.github.io/radiator/reference/read_vcf.html#advance-mode) section the use of `filter.genotyping` argument. It's a double and not an integer that is required. Consequently, for the code above to be used correctly, use this:

```
test <- radiator::read_vcf(
  data = "sub_populations.snps.vcf",
  strata = "NFLDB.strata",
  vcf.stats = TRUE,
  filter.common.markers = FALSE,
  filter.genotyping = 0.15 # not 15
)
```
