### ISSUE TITLE
Functions save their defaults parameters to the global environment

### ISSUE THREAD

**Issue by IdoBar** [thierrygosselin/radiator#69]
`radiator` functions seem to save their default parameters to the global environment, completely cluttering it.
The screenshot below is an example after running `read_dart()`, followed by `genomic_converter()`.
![image](https://user-images.githubusercontent.com/16175388/72863368-1fcb0980-3d1c-11ea-8dd2-f2b7acd56e0b.png)

It gets much worse if I add `filter_rad()`.

![image](https://user-images.githubusercontent.com/16175388/72863339-01650e00-3d1c-11ea-89da-d536a0177e0d.png)

If you're saving the function parameters in a file they can be re-used from there, but I don't see a reason why they should be saved in the environment.

Thanks, Ido

**Comment by thierrygosselin** [comment]
You're right, 
it's currently collateral damage from using another features, 
They are all very light or NULL, but they could certainly be removed.
I'll put that in the todo list for the next release.
Thanks!

**Comment by thierrygosselin** [comment]
The latest GitHub version removes objects generated during `radiator::filter_rad`, only.
Other radiator functions will continue to generate the objects, for now until further testing.
