### ISSUE TITLE
problem reading VCF after update to 1.1.4

### ISSUE THREAD

**Issue by siberianhigh** [thierrygosselin/radiator#71]
Hi!

the problem is: 

> my.vcf <- tidy_vcf(data = "./my.vcf", strata = "./popmap", verbose = TRUE)

> Reading VCF
> Error in if (stringi::stri_detect_fixed(str = check.source, pattern = "freeBayes") &&  : 
>   missing value where TRUE/FALSE needed
> 
> Computation time, overall: 0 sec
> 
> Computation time, overall: 0 sec

Same for 'read_vcf'. I have used exactly the same code and input files as I did with radiator * 1.1.2 2019-12-08 (and had no problems).

The VCF file was generated by bcftools. Below are several lines from it:

##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##bcftoolsVersion=1.9+htslib-1.9
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	N11	N3	N57	N66	N16	N45	N59	N69	N1	N51	N60	N6	N28	N53	N63	N9	N32	N55	N64	N37	N56	N65	N26	N62
AXRT01028202.1	28639	.	G	A	611	PASS	DP=676;ADF=40,31;ADR=276,329;AD=316,360;VDB=0;SGB=227.121;RPB=9.04763e-32;MQB=0.935918;MQSB=0.777834;BQB=0.198823;MQ0F=0;ICB=0.000240369;HOB=0.416667;AC=24;AN=48;DP4=40,276,31,329;MQ=10	GT:PL:DP:SP:ADF:ADR:AD	1/1:53,19,0:21:8:2,2:2,15:4,17	1/1:72,101,0:56:12:2,3:3,48:5,51	0/0:0,42,75:14:0:2,0:12,0:14,0	1/1:55,64,0:26:0:0,1:1,24:1,25	1/1:60,20,0:11:0:1,2:0,8:1,10	1/1:101,160,0:53:0:0,4:0,49:0,53	0/0:0,138,95:46:0:4,0:42,0:46,0	1/1:62,57,0:19:0:0,1:0,18:0,19	1/1:37,18,0:10:0:0,0:1,9:1,9	0/0:0,54,76:18:0:2,0:16,0:18,0	0/0:0,51,86:17:0:3,0:14,0:17,0	1/1:36,52,0:22:0:0,0:1,21:1,21	1/1:81,94,0:68:0:0,5:9,54:9,59	0/0:0,36,67:12:0:2,0:10,0:12,0	0/0:0,30,43:10:0:0,0:10,0:10,0	1/1:57,44,0:19:0:0,1:1,17:1,18	0/1:26,0,30:25:9:4,1:7,13:11,14	0/0:0,93,103:31:0:5,0:26,0:31,0	0/0:0,66,61:22:0:1,0:21,0:22,0	0/1:38,0,1:62:0:3,6:17,36:20,42	0/0:0,48,62:16:0:1,0:15,0:16,0	0/0:0,120,98:40:0:4,0:36,0:40,0	1/1:93,55,0:23:0:0,5:1,17:1,22	0/0:0,105,98:35:0:4,0:31,0:35,0
AXRT01170093.1	280	.	A	G	322	PASS	DP=1683;ADF=211,85;ADR=852,200;AD=1063,285;VDB=0;SGB=-559.316;RPB=0.331597;MQB=0.192005;MQSB=0.010774;BQB=0;MQ0F=0;ICB=0.294855;HOB=0.163194;AC=14;AN=48;DP4=211,852,87,237;MQ=12	GT:PL:DP:SP:ADF:ADR:AD	0/1:41,0,11:18:10:2,1:2,11:4,12	0/0:0,57,86:69:13:18,1:35,10:53,11	1/1:69,9,0:21:3:2,4:2,13:4,17	0/1:3,0,64:36:6:6,5:19,5:25,10	0/1:8,0,68:15:0:4,2:5,2:9,4	0/0:0,61,103:70:6:10,4:47,7:57,11	0/0:0,239,152:172:1:28,3:122,18:150,21	0/0:0,4,74:54:3:12,3:27,11:39,14	0/0:0,7,72:29:2:8,2:11,4:19,6	0/0:0,248,128:115:7:11,2:97,4:108,6	0/0:0,255,134:184:4:18,3:151,8:169,11	0/1:49,0,27:17:10:4,2:1,9:5,11	0/0:0,45,89:56:4:10,4:35,6:45,10	0/0:0,31,92:32:0:7,1:20,4:27,5	0/0:0,2,42:19:0:1,0:13,5:14,5	0/1:20,0,71:42:3:7,5:21,9:28,14	0/0:0,79,87:107:1:21,7:61,12:82,19	1/1:93,35,0:16:0:0,5:1,10:1,15	1/1:82,36,0:18:0:1,7:0,8:1,15	0/0:0,31,74:61:3:14,3:31,9:45,12	0/0:0,119,81:97:21:6,5:77,9:83,14	1/1:63,10,0:12:0:1,5:1,5:2,10	0/0:0,40,103:60:0:14,3:34,8:48,11	0/1:16,0,57:67:13:6,8:39,13:45,21
AXRT01342916.1	122	.	G	A	990	PASS	DP=4303;ADF=256,201;ADR=2652,1193;AD=2908,1394;VDB=0;SGB=639.552;RPB=0.0960443;MQB=0.897709;MQSB=0.251277;BQB=0.0285114;MQ0F=0;ICB=0.0996708;HOB=0.21875;AC=18;AN=48;DP4=256,2652,201,1193;MQ=10	GT:PL:DP:SP:ADF:ADR:AD	1/1:164,255,0:177:0:0,27:0,150:0,177	0/1:28,0,53:145:11:12,15:74,44:86,59	0/0:0,255,178:259:0:10,0:249,0:259,0	0/0:0,255,185:251:0:15,0:236,0:251,0	0/1:49,0,37:172:1:6,8:75,83:81,91	0/1:57,0,50:237:1:16,16:97,108:113,124	0/0:0,255,191:251:0:19,0:232,0:251,0	0/1:52,0,46:139:3:12,10:54,63:66,73	1/1:93,129,0:43:0:0,5:0,38:0,43	0/0:0,255,187:251:0:27,0:224,0:251,0	0/0:0,255,180:251:0:40,0:211,0:251,0	0/1:28,0,43:130:3:7,4:61,58:68,62	1/1:138,255,0:144:0:0,29:0,115:0,144	0/0:0,255,113:95:0:7,0:88,0:95,0	0/0:0,102,92:34:0:4,0:30,0:34,0	0/1:40,0,40:89:1:7,6:37,39:44,45	1/1:166,255,0:198:0:0,27:1,170:1,197	0/0:0,255,170:217:0:30,0:187,0:217,0	0/0:0,255,181:257:0:9,0:248,0:257,0	1/1:156,255,0:178:3:1,22:4,151:5,173	0/0:0,217,112:72:0:7,0:65,0:72,0	0/0:0,255,139:255:0:3,0:251,1:254,1	1/1:162,255,0:206:0:0,32:1,173:1,205	0/0:0,255,192:251:0:24,0:227,0:251,0
AXRT01400552.1	109	.	C	T	647	PASS	DP=5315;ADF=2873,194;ADR=2070,102;AD=4943,296;VDB=0;SGB=-1176.67;RPB=0.382591;MQB=0.319014;MQSB=1.03602e-13;BQB=0.970161;MQ0F=0;ICB=0.0343482;HOB=0.0138889;AC=4;AN=48;DP4=2873,2070,197,104;MQ=43	GT:PL:DP:SP:ADF:ADR:AD	0/0:0,255,255:165:0:131,0:34,0:165,0	0/1:126,0,255:253:14:120,42:78,13:198,55	0/0:0,255,255:251:0:59,0:192,0:251,0	0/1:203,0,255:261:19:41,24:155,41:196,65	0/0:0,255,255:254:0:128,0:126,0:254,0	0/0:0,255,255:258:0:120,0:138,0:258,0	0/0:0,255,255:253:0:167,0:86,0:253,0	0/1:255,0,255:255:30:70,59:94,32:164,91	0/0:0,9,255:189:0:139,23:23,4:162,27	0/0:0,255,255:246:0:197,0:49,0:246,0	0/0:0,255,255:140:0:113,0:27,0:140,0	0/0:0,255,255:253:0:145,0:106,0:251,0	0/1:136,0,255:253:56:86,45:110,12:196,57	0/0:0,255,255:251:4:192,0:57,0:249,0	0/0:0,63,255:21:0:18,0:3,0:21,0	0/0:0,255,255:252:0:170,1:80,0:250,1	0/0:0,255,255:256:0:134,0:122,0:256,0

**Comment by thierrygosselin** [comment]
I did modify the VCF screening part to highlight problem with some version of dDocent/freeBayes...
I must have broke something.

I'll try with the lines you have above

**Comment by thierrygosselin** [comment]
Hi Evgeniy,

Try re-installing radiator (don't forget to restart R as well if you're using RStudio).

If this doesn't work, could you send me by email your VCF and strata file please.

Best
Thierry

**Comment by siberianhigh** [comment]
Hi Thierry, 

now it works, thanks!
