### ISSUE TITLE
clarity on how to load output from genomic_converter

### ISSUE THREAD

**Issue by lkomoro** [thierrygosselin/radiator#74]
I cannot help you if I cannot reproduce the problem.
Consequently, when reporting an issue, make sure to include:

**Describe the bug**
Can you provide clarity on loading output from the genomic_converter? I have a RAD/SNP dataset that I would like to filter using radiator, then conduct analyses in strataG and adegenet. The filter_rad() function produces genlight and gtypes .Rdata files, but I get an error when I try to open them this using the load() function. Perhaps there is a different function for this? I looked at the documentation if there is a better way to accomplish what I am trying to do, my apologies if I missed it (if so, please direct me there, thanks!). All packages should be up to date.

**To Reproduce**
Include the steps to reproduce the behavior:
* the exact command (function, arguments, values) used
radiator_filtered_M <- filter_rad(
  data = input_vcf, #previously defined file
  filter.short.ld = NULL,
  filter.long.ld = 0.9,
  filter.hwe = FALSE,
  output = c("vcf","genind","genlight","plink","genepop","gtypes"),
  strata = input_strata, #previously defined file
  filename = "radiator_filtered_M",
  interactive.filter = FALSE,
  verbose = TRUE) 
g<-load("./filter_rad_20200226@1355/05_filtered/radiator_gtypes_20200226@1355.Rdata")#currently produces error

* the complete error message you're getting
file ‘radiator_gtypes_20200226@1355.Rdata’ has magic number 'X'
  Use of save versions prior to 2 is deprecatedError in load("./filter_rad_20200226@1355/05_filtered/radiator_gtypes_20200226@1355.Rdata") : 
  bad restore file magic number (file may be corrupted) -- no data loaded

* the output of `devtools::session_info()`
> devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-02-26                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package          * version  date       lib source                                   
 ade4             * 1.7-15   2020-02-13 [1] CRAN (R 3.6.0)                           
 adegenet         * 2.1.3    2020-02-24 [1] Github (thibautjombart/adegenet@95e1d68) 
 ape                5.3      2019-03-17 [1] CRAN (R 3.6.0)                           
 apex               1.0.3    2017-09-23 [1] CRAN (R 3.6.0)                           
 assertthat         0.2.1    2019-03-21 [1] CRAN (R 3.6.0)                           
 backports          1.1.5    2019-10-02 [1] CRAN (R 3.6.0)                           
 Biobase            2.46.0   2019-10-29 [1] Bioconductor                             
 BiocGenerics       0.32.0   2019-10-29 [1] Bioconductor                             
 BiocManager        1.30.10  2019-11-16 [1] CRAN (R 3.6.0)                           
 Biostrings         2.54.0   2019-10-29 [1] Bioconductor                             
 bitops             1.0-6    2013-08-17 [1] CRAN (R 3.6.0)                           
 boot               1.3-24   2019-12-20 [1] CRAN (R 3.6.0)                           
 broom              0.5.4    2020-01-27 [1] CRAN (R 3.6.0)                           
 callr              3.4.2    2020-02-12 [1] CRAN (R 3.6.0)                           
 class              7.3-15   2019-01-01 [1] CRAN (R 3.6.2)                           
 classInt           0.4-2    2019-10-17 [1] CRAN (R 3.6.0)                           
 cli                2.0.1    2020-01-08 [1] CRAN (R 3.6.0)                           
 cluster            2.1.0    2019-06-19 [1] CRAN (R 3.6.2)                           
 coda               0.19-3   2019-07-05 [1] CRAN (R 3.6.0)                           
 codetools          0.2-16   2018-12-24 [1] CRAN (R 3.6.2)                           
 colorspace         1.4-1    2019-03-18 [1] CRAN (R 3.6.0)                           
 crayon             1.3.4    2017-09-16 [1] CRAN (R 3.6.0)                           
 curl               4.3      2019-12-02 [1] CRAN (R 3.6.0)                           
 data.table         1.12.8   2019-12-09 [1] CRAN (R 3.6.0)                           
 DBI                1.1.0    2019-12-15 [1] CRAN (R 3.6.0)                           
 deldir             0.1-25   2020-02-03 [1] CRAN (R 3.6.0)                           
 desc               1.2.0    2018-05-01 [1] CRAN (R 3.6.0)                           
 devtools         * 2.2.2    2020-02-17 [1] CRAN (R 3.6.0)                           
 digest             0.6.25   2020-02-23 [1] CRAN (R 3.6.0)                           
 dplyr              0.8.4    2020-01-31 [1] CRAN (R 3.6.0)                           
 e1071              1.7-3    2019-11-26 [1] CRAN (R 3.6.0)                           
 ellipsis           0.3.0    2019-09-20 [1] CRAN (R 3.6.0)                           
 expm               0.999-4  2019-03-21 [1] CRAN (R 3.6.0)                           
 fansi              0.4.1    2020-01-08 [1] CRAN (R 3.6.0)                           
 farver             2.0.3    2020-01-16 [1] CRAN (R 3.6.0)                           
 fastmap            1.0.1    2019-10-08 [1] CRAN (R 3.6.0)                           
 fastmatch          1.1-0    2017-01-28 [1] CRAN (R 3.6.0)                           
 fs                 1.3.1    2019-05-06 [1] CRAN (R 3.6.0)                           
 fst                0.9.0    2019-04-09 [1] CRAN (R 3.6.0)                           
 gdata            * 2.18.0   2017-06-06 [1] CRAN (R 3.6.0)                           
 gdsfmt           * 1.22.0   2019-10-29 [1] Bioconductor                             
 generics           0.0.2    2018-11-29 [1] CRAN (R 3.6.0)                           
 GenomeInfoDb       1.22.0   2019-10-29 [1] Bioconductor                             
 GenomeInfoDbData   1.2.2    2020-02-24 [1] Bioconductor                             
 GenomicRanges      1.38.0   2019-10-29 [1] Bioconductor                             
 ggplot2            3.2.1    2019-08-10 [1] CRAN (R 3.6.0)                           
 glue               1.3.1    2019-03-12 [1] CRAN (R 3.6.0)                           
 gmodels            2.18.1   2018-06-25 [1] CRAN (R 3.6.0)                           
 gridExtra          2.3      2017-09-09 [1] CRAN (R 3.6.0)                           
 gtable             0.3.0    2019-03-25 [1] CRAN (R 3.6.0)                           
 gtools             3.8.1    2018-06-26 [1] CRAN (R 3.6.0)                           
 GWASExactHW        1.01     2013-01-05 [1] CRAN (R 3.6.0)                           
 hms                0.5.3    2020-01-08 [1] CRAN (R 3.6.0)                           
 htmltools          0.4.0    2019-10-04 [1] CRAN (R 3.6.0)                           
 httpuv             1.5.2    2019-09-11 [1] CRAN (R 3.6.0)                           
 igraph             1.2.4.2  2019-11-27 [1] CRAN (R 3.6.0)                           
 IRanges            2.20.2   2020-01-13 [1] Bioconductor                             
 KernSmooth         2.23-16  2019-10-15 [1] CRAN (R 3.6.2)                           
 knitr              1.28     2020-02-06 [1] CRAN (R 3.6.0)                           
 labeling           0.3      2014-08-23 [1] CRAN (R 3.6.0)                           
 later              1.0.0    2019-10-04 [1] CRAN (R 3.6.0)                           
 lattice            0.20-40  2020-02-19 [1] CRAN (R 3.6.0)                           
 lazyeval           0.2.2    2019-03-15 [1] CRAN (R 3.6.0)                           
 LearnBayes         2.15.1   2018-03-18 [1] CRAN (R 3.6.0)                           
 lifecycle          0.1.0    2019-08-01 [1] CRAN (R 3.6.0)                           
 logistf            1.23     2018-07-19 [1] CRAN (R 3.6.0)                           
 magrittr           1.5      2014-11-22 [1] CRAN (R 3.6.0)                           
 MASS               7.3-51.5 2019-12-20 [1] CRAN (R 3.6.0)                           
 Matrix             1.2-18   2019-11-27 [1] CRAN (R 3.6.2)                           
 memoise            1.1.0    2017-04-21 [1] CRAN (R 3.6.0)                           
 memuse             4.1-0    2020-02-17 [1] CRAN (R 3.6.0)                           
 mgcv               1.8-31   2019-11-09 [1] CRAN (R 3.6.2)                           
 mice               3.8.0    2020-02-21 [1] CRAN (R 3.6.0)                           
 mime               0.9      2020-02-04 [1] CRAN (R 3.6.0)                           
 munsell            0.5.0    2018-06-12 [1] CRAN (R 3.6.0)                           
 nlme               3.1-144  2020-02-06 [1] CRAN (R 3.6.0)                           
 pbmcapply          1.5.0    2019-07-10 [1] CRAN (R 3.6.0)                           
 permute            0.9-5    2019-03-12 [1] CRAN (R 3.6.0)                           
 phangorn           2.5.5    2019-06-19 [1] CRAN (R 3.6.0)                           
 pillar             1.4.3    2019-12-20 [1] CRAN (R 3.6.0)                           
 pinfsc50           1.1.0    2016-12-02 [1] CRAN (R 3.6.0)                           
 pkgbuild           1.0.6    2019-10-09 [1] CRAN (R 3.6.0)                           
 pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 3.6.0)                           
 pkgload            1.0.2    2018-10-29 [1] CRAN (R 3.6.0)                           
 plyr               1.8.5    2019-12-10 [1] CRAN (R 3.6.0)                           
 prettyunits        1.1.1    2020-01-24 [1] CRAN (R 3.6.0)                           
 processx           3.4.2    2020-02-09 [1] CRAN (R 3.6.0)                           
 promises           1.1.0    2019-10-04 [1] CRAN (R 3.6.0)                           
 ps                 1.3.2    2020-02-13 [1] CRAN (R 3.6.0)                           
 purrr              0.3.3    2019-10-18 [1] CRAN (R 3.6.0)                           
 quadprog           1.5-8    2019-11-20 [1] CRAN (R 3.6.0)                           
 R6                 2.4.1    2019-11-12 [1] CRAN (R 3.6.0)                           
 radiator         * 1.1.4    2020-02-26 [1] Github (thierrygosselin/radiator@4fd4f65)
 raster             3.0-12   2020-01-30 [1] CRAN (R 3.6.0)                           
 Rcpp               1.0.3    2019-11-08 [1] CRAN (R 3.6.0)                           
 RCurl              1.98-1.1 2020-01-19 [1] CRAN (R 3.6.0)                           
 readr              1.3.1    2018-12-21 [1] CRAN (R 3.6.0)                           
 remotes            2.1.1    2020-02-15 [1] CRAN (R 3.6.0)                           
 reshape2           1.4.3    2017-12-11 [1] CRAN (R 3.6.0)                           
 rlang              0.4.4    2020-01-28 [1] CRAN (R 3.6.0)                           
 rprojroot          1.3-2    2018-01-03 [1] CRAN (R 3.6.0)                           
 rstudioapi         0.11     2020-02-07 [1] CRAN (R 3.6.0)                           
 S4Vectors          0.24.3   2020-01-18 [1] Bioconductor                             
 scales             1.1.0    2019-11-18 [1] CRAN (R 3.6.0)                           
 SeqArray           1.26.2   2019-12-26 [1] Bioconductor                             
 seqinr             3.6-1    2019-09-07 [1] CRAN (R 3.6.0)                           
 SeqVarTools        1.24.0   2019-10-29 [1] Bioconductor                             
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 3.6.0)                           
 sf                 0.8-1    2020-01-28 [1] CRAN (R 3.6.0)                           
 shiny              1.4.0    2019-10-10 [1] CRAN (R 3.6.0)                           
 SNPRelate        * 1.20.1   2019-11-22 [1] Bioconductor                             
 sp                 1.4-0    2020-02-21 [1] CRAN (R 3.6.0)                           
 spData             0.3.3    2020-02-11 [1] CRAN (R 3.6.0)                           
 spdep              1.1-3    2019-09-18 [1] CRAN (R 3.6.0)                           
 strataG          * 2.4.904  2020-02-24 [1] Github (ericarcher/strataG@5c65efe)      
 stringi            1.4.6    2020-02-17 [1] CRAN (R 3.6.0)                           
 stringr            1.4.0    2019-02-10 [1] CRAN (R 3.6.0)                           
 testthat           2.3.1    2019-12-01 [1] CRAN (R 3.6.0)                           
 tibble             2.1.3    2019-06-06 [1] CRAN (R 3.6.0)                           
 tidyr              1.0.2    2020-01-24 [1] CRAN (R 3.6.0)                           
 tidyselect         1.0.0    2020-01-27 [1] CRAN (R 3.6.0)                           
 units              0.6-5    2019-10-08 [1] CRAN (R 3.6.0)                           
 UpSetR             1.4.0    2019-05-22 [1] CRAN (R 3.6.0)                           
 usethis          * 1.5.1    2019-07-04 [1] CRAN (R 3.6.0)                           
 vcfR             * 1.10.0   2020-02-06 [1] CRAN (R 3.6.0)                           
 vctrs              0.2.3    2020-02-20 [1] CRAN (R 3.6.0)                           
 vegan              2.5-6    2019-09-01 [1] CRAN (R 3.6.0)                           
 viridisLite        0.3.0    2018-02-01 [1] CRAN (R 3.6.0)                           
 withr              2.1.2    2018-03-15 [1] CRAN (R 3.6.0)                           
 xfun               0.12     2020-01-13 [1] CRAN (R 3.6.0)                           
 xtable             1.8-4    2019-04-21 [1] CRAN (R 3.6.0)                           
 XVector            0.26.0   2019-10-29 [1] Bioconductor                             
 zlibbioc           1.32.0   2019-10-29 [1] Bioconductor                             

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
* complete data required to reproduce the problem, a subset of it. The data remains confidential.
[input_files.zip](https://github.com/thierrygosselin/radiator/files/4257732/input_files.zip)

**Screenshots**

**Comment by thierrygosselin** [comment]
try `readRDS` instead of load, it's already in the documentation for the specified output, I'll make sure it's there for every object written this way.
https://thierrygosselin.github.io/radiator/reference/write_gtypes.html

**Comment by thierrygosselin** [comment]
the object is written in the working directory but you should also find it in the environment inside the list there is an `$output` inside that is the gtypes and genlight.
