### ISSUE TITLE
error in merging two dartfiles

### ISSUE THREAD

**Issue by Farhad63** [thierrygosselin/radiator#77]
Hi Thiery
I try to merge two different dart data-file  together and I get error as below. Any comment please?
radiator::merge_dart(dart1 ="DArT_SNP1.csv", strata1 = "strata1.tsv", dart2 = ""DArT_SNP2.csv", strata2 = "strata1.tsv")

error: "Error in radiator::merge_dart(dart1 = "DArT_SNP.csv", strata1 = "strata1.tsv",  : 
  object 'pop.select' not found"
I have included INDIVIDUAL and POP IDs in strata files. 
As the data size are more than 100 megabytes and to large to update here even a subset, I can send a subset of each dart file via email (or share it and send the link) if needed.

Please accept my apology if this is irrelevant since I am new to population genomics analysis using R.

**Comment by thierrygosselin** [comment]
Dear Farhad, I'll have a look at this function with my test datasets. I think I'm the inly one who had to use that function so far ;)

Cheers
Thierry

**Comment by thierrygosselin** [comment]
should work now !
Thanks for highlighting the bug
