### ISSUE TITLE
Error: 'vec_as_subscript' with filter_rad()

### ISSUE THREAD

**Issue by qhelleu** [thierrygosselin/radiator#79]
Hi,
I would like to use radiator to convert and filter a bunch of vcf files, but I get the following error:
"Error: 'vec_as_subscript' is not an exported object from 'namespace:vctrs'"

Here is what I did in the session:
`
> library("radiator",lib="~/R/3.6.1")

shark <-filter_rad(
+       "autosomes_SNP.filt.vcf.gz",
+        strata = NULL,
+        interactive.filter = FALSE,
+        output = "genind",
+        filename = NULL,
+        verbose = TRUE,
+        parallel.core = 8)
################################################################################
################################################################################
The function arguments names have changed: please read documentation

Execution date@time: 20200317@1110
Folder created: filter_rad_20200317@1110
Function call and arguments stored in: radiator_filter_rad_args_20200317@1110.tsv
File written: random.seed (54130)
Filters parameters file generated: filters_parameters_20200317@1110.tsv

Reading a large VCF...you actually have time for coffee or tea!

Loading required package: gdsfmt
Loading required package: gdsfmt
Loading required package: gdsfmt
Loading required package: gdsfmt
Loading required package: gdsfmt
Loading required package: gdsfmt
Loading required package: gdsfmt
Loading required package: gdsfmt
Data summary: 
    number of samples: 185
    number of markers: 5290118
done! timing: 1062 sec

Error: 'vec_as_subscript' is not an exported object from 'namespace:vctrs'
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 1070 sec
############################# completed filter_rad #############################
`

Rlang last error and last trace:
`
> rlang::last_error()
<error/rlang_error>
'vec_as_subscript' is not an exported object from 'namespace:vctrs'
Backtrace:
 1. radiator::filter_rad(...)
 2. radiator::read_vcf(...)
 4. dplyr:::select.data.frame(individuals.vcf, INDIVIDUALS = INDIVIDUALS_CLEAN)
 5. tidyselect::vars_select(tbl_vars(.data), !!!enquos(...))
 6. tidyselect:::eval_select_impl(...)
 7. tidyselect:::with_subscript_errors(...)
Run `rlang::last_trace()` to see the full context.
> 
> rlang::last_trace()
<error/rlang_error>
'vec_as_subscript' is not an exported object from 'namespace:vctrs'
Backtrace:
    █
 1. └─radiator::filter_rad(...)
 2.   └─radiator::read_vcf(...)
 3.     ├─dplyr::select(individuals.vcf, INDIVIDUALS = INDIVIDUALS_CLEAN)
 4.     └─dplyr:::select.data.frame(individuals.vcf, INDIVIDUALS = INDIVIDUALS_CLEAN)
 5.       └─tidyselect::vars_select(tbl_vars(.data), !!!enquos(...))
 6.         └─tidyselect:::eval_select_impl(...)
 7.           └─tidyselect:::with_subscript_errors(...)
<parent: error/simpleError>
'vec_as_subscript' is not an exported object from 'namespace:vctrs'
`

And here is the session_info() output:

─ Session info ─────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       CentOS Linux 7 (Core)       
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Zurich               
 date     2020-03-17                  

─ Packages ─────────────────────────────────────────────────────────

 !  package          * version   date       lib source
assertthat         0.2.1     2019-03-21 [1] CRAN (R 3.6.1)
backports          1.1.5     2019-10-02 [1] CRAN (R 3.6.1)
Biobase            2.46.0    2019-10-29 [1] Bioconductor
BiocGenerics       0.32.0    2019-10-29 [1] Bioconductor  
Biostrings         2.54.0    2019-10-29 [1] Bioconductor  
bitops             1.0-6     2013-08-17 [1] CRAN (R 3.6.1)
boot               1.3-23    2019-07-05 [1] CRAN (R 3.6.1)
broom              0.5.2     2019-04-07 [1] CRAN (R 3.6.1)
callr              3.3.2     2019-09-22 [1] CRAN (R 3.6.1)
cli                1.1.0     2019-03-19 [1] CRAN (R 3.6.1)
crayon             1.3.4     2017-09-16 [1] CRAN (R 3.6.1)
desc               1.2.0     2018-05-01 [1] CRAN (R 3.6.1)
devtools         * 2.2.1     2019-09-24 [1] CRAN (R 3.6.1)
digest             0.6.22    2019-10-21 [1] CRAN (R 3.6.1)
VP dplyr              0.8.5     2019-07-04 [?] CRAN (R 3.6.1)
ellipsis           0.3.0     2019-09-20 [1] CRAN (R 3.6.1)
fs                 1.3.1     2019-05-06 [1] CRAN (R 3.6.1)
gdsfmt             1.22.0    2019-10-29 [1] Bioconductor  
generics           0.0.2     2018-11-29 [1] CRAN (R 3.6.1)
GenomeInfoDb       1.22.0    2019-10-29 [1] Bioconductor  
GenomeInfoDbData   1.2.2     2019-11-10 [1] Bioconductor  
GenomicRanges      1.38.0    2019-10-29 [1] Bioconductor  
VP glue               1.3.2     2019-03-12 [?] CRAN (R 3.6.1)
GWASExactHW        1.01      2013-01-05 [1] CRAN (R 3.6.1)
hms                0.5.2     2019-10-30 [1] CRAN (R 3.6.1)
IRanges            2.20.0    2019-10-29 [1] Bioconductor  
jomo               2.6-10    2019-10-22 [1] CRAN (R 3.6.1)
lattice            0.20-38   2018-11-04 [1] CRAN (R 3.6.1)
lifecycle          0.1.0     2019-08-01 [1] CRAN (R 3.6.1)
lme4               1.1-21    2019-03-05 [1] CRAN (R 3.6.1)
logistf            1.23      2018-07-19 [1] CRAN (R 3.6.1)
magrittr           1.5       2014-11-22 [1] CRAN (R 3.6.1)
MASS               7.3-51.4  2019-03-31 [1] CRAN (R 3.6.1)
Matrix             1.2-17    2019-03-22 [1] CRAN (R 3.6.1)
memoise            1.1.0     2017-04-21 [1] CRAN (R 3.6.1)
mgcv               1.8-30    2019-10-24 [1] CRAN (R 3.6.1)
mice               3.6.0     2019-07-10 [1] CRAN (R 3.6.1)
minqa              1.2.4     2014-10-09 [1] CRAN (R 3.6.1)
mitml              0.3-7     2019-01-07 [1] CRAN (R 3.6.1)
nlme               3.1-141   2019-08-01 [1] CRAN (R 3.6.1)
nloptr             1.2.1     2018-10-03 [1] CRAN (R 3.6.1)
nnet               7.3-12    2016-02-02 [1] CRAN (R 3.6.1)
pan                1.6       2018-06-29 [1] CRAN (R 3.6.1)
VP pillar             1.4.3     2019-06-29 [?] CRAN (R 3.6.1)
pkgbuild           1.0.6     2019-10-09 [1] CRAN (R 3.6.1)
pkgconfig          2.0.3     2019-09-22 [1] CRAN (R 3.6.1)
pkgload            1.0.2     2018-10-29 [1] CRAN (R 3.6.1)
prettyunits        1.0.2     2015-07-13 [1] CRAN (R 3.6.1)
processx           3.4.1     2019-07-18 [1] CRAN (R 3.6.1)
ps                 1.3.0     2018-12-21 [1] CRAN (R 3.6.1)
purrr              0.3.3     2019-10-18 [1] CRAN (R 3.6.1)
VP R6                 2.4.1     2019-02-14 [?] CRAN (R 3.6.1)
R  radiator         * 1.1.5     <NA>       [?] <NA>          
VP Rcpp               1.0.3     2019-07-25 [?] CRAN (R 3.6.1)
RCurl              1.95-4.12 2019-03-04 [1] CRAN (R 3.6.1)
readr              1.3.1     2018-12-21 [1] CRAN (R 3.6.1)
remotes            2.1.0     2019-06-24 [1] CRAN (R 3.6.1)
VP rlang              0.4.5     2019-10-24 [?] CRAN (R 3.6.1)
rpart              4.1-15    2019-04-12 [1] CRAN (R 3.6.1)
rprojroot          1.3-2     2018-01-03 [1] CRAN (R 3.6.1)
S4Vectors          0.24.0    2019-10-29 [1] Bioconductor  
SeqArray           1.26.1    2019-11-04 [1] Bioconductor  
SeqVarTools        1.24.0    2019-10-29 [1] Bioconductor  
sessioninfo        1.1.1     2018-11-05 [1] CRAN (R 3.6.1)
stringi            1.4.3     2019-03-12 [1] CRAN (R 3.6.1)
survival           3.1-6     2019-11-06 [1] CRAN (R 3.6.1)
testthat           2.3.0     2019-11-05 [1] CRAN (R 3.6.1)
tibble             2.1.3     2019-06-06 [1] CRAN (R 3.6.1)
tidyr              1.0.0     2019-09-11 [1] CRAN (R 3.6.1)
VP tidyselect         1.0.0     2018-10-11 [?] CRAN (R 3.6.1)
usethis          * 1.5.1     2019-07-04 [1] CRAN (R 3.6.1)
vctrs              0.2.0     2019-07-05 [1] CRAN (R 3.6.1)
withr              2.1.2     2018-03-15 [1] CRAN (R 3.6.1)
XVector            0.26.0    2019-10-29 [1] Bioconductor  
zeallot            0.1.0     2018-01-28 [1] CRAN (R 3.6.1)
zlibbioc           1.32.0    2019-10-29 [1] Bioconductor`

I can send you a subset of my vcf if needed.
Thanks,
Best.

**Comment by thierrygosselin** [comment]
Dear qhelleu,
It's impossible for me to reproduce the error, 
please send the vcd or subset of it by email
Best
Thierry


before you do, try:

1. re-running but this time use the proper argument for the vcf file inside `filter_rad` (it's `data`)
2. `read_vcf`

If you still have the same error, it's a reading problem...
Which software generated the vcf ?

**Comment by qhelleu** [comment]
Hi Thierry,
I tried with the proper argument inside filter_rad and with read_vcf, I get the same error each time: Error: 'vec_as_subscript' is not an exported object from 'namespace:vctrs'

I used Freebayes to generate the vcf file.
I send you a small subset of the vcf (it's confidential). 
Thanks,
Best.

**Comment by thierrygosselin** [comment]
I think the reason is that the `GT` field inside the VCF is not recognized correctly:
Is it haploid data ?

**Comment by qhelleu** [comment]
Yes! Sorry I forgot to mention.

**Comment by thierrygosselin** [comment]
Doesn't work with radiator...
I'll make sure it's written in the doc in several places...

**Comment by thierrygosselin** [comment]
Try PGDSpider ....
