### ISSUE TITLE
genomic_converter() to convert genlight to pcadapt

### ISSUE THREAD

**Issue by PeiwenLi** [thierrygosselin/radiator#82]
Hi,
I am trying to convert my genlight file to a pcadapt file format for PCADAPT analyses using the following command:

PCADAPT411<-genomic_converter(GENLIGHT411ind_3$tidy.data,output = "pcadapt",filename = "PCADAPT411",  filter.common.markers = T, filter.monomorphic = T)

I got something like this:
################################################################################
################################################################################
Execution date@time: 20200525@1558
Scanning for common markers...

Computation time, overall: 2 sec
################################################################################
################################################################################
Execution date@time: 20200525@1558
Scanning for monomorphic markers...

Computation time, overall: 1 sec
######################## filter_monomorphic completed ##########################
writing pcadapt file with:
    Number of populations: 17
    Number of individuals: 411
    Number of markers: **3025**
################################### RESULTS ####################################
Data format of input: tbl_df
Biallelic data
Number of markers: **3055**
Number of chromosome/contig/scaffold: 670
Number of individuals: 411

Computation time, overall: 10 sec
######################### genomic_converter completed ##########################

My genlight input file has 3055 markers, and it seems the two filters in genomic_converter() did not remove any markers. However, my pcadapt file only has 3025 markers. Did the conversion remove markers with missing data? Is that what I want?

Sincere regards,
Peiwen

**Comment by thierrygosselin** [comment]
Could you try again after re-installing radiator to get the latest release/push

**Comment by thierrygosselin** [comment]
Couple of things:

- It says 3025 in the monomorphic section
- It's the last section that is probably not updating correctly
- In the example above, you seem to be using a tidy data set, not genlight, is that correct ?
- I'm surprise argument values are recognized, T is not always a short for TRUE. Please use the correct values (data = GENLIGHT411ind_3$tidy.data, output = "pcadapt", filename = "PCADAPT411", filter.common.markers = TRUE, filter.monomorphic = TRUE, verbose = TRUE)

with verbose on we might see a bit more things getting printed.

**Comment by thierrygosselin** [comment]
Re-open the issue if you're experiencing a problem with the new version.
