### ISSUE TITLE
error after release of dplyr 1.0.0

### ISSUE THREAD

**Issue by marclagu** [thierrygosselin/radiator#83]
Hi Thierry,
I am trying to re-run some data using exactly the same vcf files that worked in the past, but now I get the following error when trying to use the function tidy_vcf:
================================================
Reading VCF
Data summary: 
    number of samples: 639
    number of markers: 4921
done! timing: 2 sec

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0
Generating individual stats...
Error: Problem with `filter()` input `..1`.
x object 'MARKERS' not found
ℹ Input `..1` is `MARKERS %in% markers`.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
The `keep` argument of `group_split()` is deprecated as of dplyr 1.0.0.
Please use the `.keep` argument instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 

Computation time, overall: 6 sec
Computation time, overall: 9 sec
================================================

# When I check where the error occurred:
================================================
> rlang::last_error()
<error/dplyr_error>
Problem with `filter()` input `..1`.
x object 'MARKERS' not found
ℹ Input `..1` is `MARKERS %in% markers`.
Backtrace:
  1. radiator::tidy_vcf("iceland.clean.HW.vcf", strata = "strata.iceland.clean.tsv")
  2. radiator::read_vcf(...)
  6. radiator::generate_id_stats(...)
  7. radiator::extract_coverage(gds, markers = FALSE)
  8. radiator::extract_genotypes_metadata(...)
  9. [ `%<>%`(...) ] with 7 more calls
 18. dplyr:::filter.data.frame(...)
 19. dplyr:::filter_rows(.data, ...)
 20. base::tryCatch(...)
 21. base:::tryCatchList(expr, classes, parentenv, handlers)
 22. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 23. value[[3L]](cond)
 24. dplyr:::stop_dplyr(...)
Run `rlang::last_trace()` to see the full context.

When I check the full context:
================================================
> rlang::last_trace()
<error/dplyr_error>
Problem with `filter()` input `..1`.
x object 'MARKERS' not found
ℹ Input `..1` is `MARKERS %in% markers`.
Backtrace:
     █
  1. └─radiator::tidy_vcf("iceland.clean.HW.vcf", strata = "strata.iceland.clean.tsv")
  2.   └─radiator::read_vcf(...)
  3.     ├─`%$%`(...)
  4.     │ └─base::eval(lhs, parent, parent)
  5.     │   └─base::eval(lhs, parent, parent)
  6.     └─radiator::generate_id_stats(...)
  7.       └─radiator::extract_coverage(gds, markers = FALSE)
  8.         └─radiator::extract_genotypes_metadata(...)
  9.           └─`%<>%`(...)
 10.             ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
 11.             └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 12.               └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 13.                 └─radiator:::`_fseq`(`_lhs`)
 14.                   └─magrittr::freduce(value, `_function_list`)
 15.                     ├─base::withVisible(function_list[[k]](value))
 16.                     └─function_list[[k]](value)
 17.                       ├─dplyr::filter(., MARKERS %in% markers, INDIVIDUALS %in% individuals)
 18.                       └─dplyr:::filter.data.frame(...)
 19.                         └─dplyr:::filter_rows(.data, ...)
 20.                           └─base::tryCatch(...)
 21.                             └─base:::tryCatchList(expr, classes, parentenv, handlers)
 22.                               └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 23.                                 └─value[[3L]](cond)
 24.                                   └─dplyr:::stop_dplyr(...)
================================================

And finally the session info:
================================================
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Atlantic/Reykjavik          
 date     2020-06-05                  

─ Packages ───────────────────────────────────────────────────────────────
 package          * version    date       lib source                                   
 assertthat         0.2.1      2019-03-21 [1] CRAN (R 3.6.1)                           
 backports          1.1.7      2020-05-13 [1] CRAN (R 3.6.3)                           
 Biobase            2.46.0     2019-10-29 [1] Bioconductor                             
 BiocGenerics       0.32.0     2019-10-29 [1] Bioconductor                             
 Biostrings         2.54.0     2019-10-29 [1] Bioconductor                             
 bitops             1.0-6      2013-08-17 [1] CRAN (R 3.6.1)                           
 broom              0.5.6      2020-04-20 [1] CRAN (R 3.6.3)                           
 callr              3.4.3      2020-03-28 [1] CRAN (R 3.6.3)                           
 cli                2.0.2      2020-02-28 [1] CRAN (R 3.6.2)                           
 colorspace         1.4-1      2019-03-18 [1] CRAN (R 3.6.1)                           
 crayon             1.3.4      2017-09-16 [1] CRAN (R 3.6.1)                           
 desc               1.2.0      2018-05-01 [1] CRAN (R 3.6.1)                           
 devtools           2.3.0      2020-04-10 [1] CRAN (R 3.6.3)                           
 digest             0.6.25     2020-02-23 [1] CRAN (R 3.6.2)                           
 dplyr              1.0.0.9000 2020-06-05 [1] Github (tidyverse/dplyr@f089919)         
 ellipsis           0.3.1      2020-05-15 [1] CRAN (R 3.6.3)                           
 fansi              0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                           
 farver             2.0.3      2020-01-16 [1] CRAN (R 3.6.2)                           
 fs                 1.4.1      2020-04-04 [1] CRAN (R 3.6.3)                           
 gdsfmt             1.22.0     2019-10-29 [1] Bioconductor                             
 generics           0.0.2      2018-11-29 [1] CRAN (R 3.6.1)                           
 GenomeInfoDb       1.22.1     2020-03-27 [1] Bioconductor                             
 GenomeInfoDbData   1.2.2      2020-06-05 [1] Bioconductor                             
 GenomicRanges      1.38.0     2019-10-29 [1] Bioconductor                             
 ggplot2            3.3.1      2020-05-28 [1] CRAN (R 3.6.3)                           
 glue               1.4.1      2020-05-13 [1] CRAN (R 3.6.3)                           
 gridExtra          2.3        2017-09-09 [1] CRAN (R 3.6.1)                           
 gtable             0.3.0      2019-03-25 [1] CRAN (R 3.6.1)                           
 GWASExactHW        1.01       2013-01-05 [1] CRAN (R 3.6.1)                           
 hms                0.5.3      2020-01-08 [1] CRAN (R 3.6.2)                           
 IRanges            2.20.2     2020-01-13 [1] Bioconductor                             
 labeling           0.3        2014-08-23 [1] CRAN (R 3.6.1)                           
 lattice            0.20-41    2020-04-02 [4] CRAN (R 3.6.3)                           
 lifecycle          0.2.0      2020-03-06 [1] CRAN (R 3.6.3)                           
 logistf            1.23       2018-07-19 [1] CRAN (R 3.6.1)                           
 magrittr           1.5        2014-11-22 [1] CRAN (R 3.6.1)                           
 Matrix             1.2-18     2019-11-27 [4] CRAN (R 3.6.1)                           
 memoise            1.1.0      2017-04-21 [1] CRAN (R 3.6.1)                           
 mgcv               1.8-31     2019-11-09 [4] CRAN (R 3.6.1)                           
 mice               3.9.0      2020-05-14 [1] CRAN (R 3.6.3)                           
 munsell            0.5.0      2018-06-12 [1] CRAN (R 3.6.1)                           
 nlme               3.1-147    2020-04-13 [4] CRAN (R 3.6.3)                           
 pillar             1.4.4      2020-05-05 [1] CRAN (R 3.6.3)                           
 pkgbuild           1.0.8      2020-05-07 [1] CRAN (R 3.6.3)                           
 pkgconfig          2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                           
 pkgload            1.1.0      2020-05-29 [1] CRAN (R 3.6.3)                           
 plyr               1.8.6      2020-03-03 [1] CRAN (R 3.6.3)                           
 prettyunits        1.1.1      2020-01-24 [1] CRAN (R 3.6.2)                           
 processx           3.4.2      2020-02-09 [1] CRAN (R 3.6.2)                           
 ps                 1.3.3      2020-05-08 [1] CRAN (R 3.6.3)                           
 purrr              0.3.4      2020-04-17 [1] CRAN (R 3.6.3)                           
 R6                 2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                           
 radiator         * 1.1.5      2020-06-05 [1] Github (thierrygosselin/radiator@a13fe0a)
 Rcpp               1.0.4.6    2020-04-09 [1] CRAN (R 3.6.3)                           
 RCurl              1.98-1.2   2020-04-18 [1] CRAN (R 3.6.3)                           
 readr              1.3.1      2018-12-21 [1] CRAN (R 3.6.1)                           
 remotes            2.1.1      2020-02-15 [1] CRAN (R 3.6.3)                           
 rlang              0.4.6      2020-05-02 [1] CRAN (R 3.6.3)                           
 rprojroot          1.3-2      2018-01-03 [1] CRAN (R 3.6.1)                           
 rstudioapi         0.11       2020-02-07 [1] CRAN (R 3.6.2)                           
 S4Vectors          0.24.4     2020-04-09 [1] Bioconductor                             
 scales             1.1.1      2020-05-11 [1] CRAN (R 3.6.3)                           
 SeqArray           1.26.2     2019-12-26 [1] Bioconductor                             
 SeqVarTools        1.24.1     2020-03-17 [1] Bioconductor                             
 sessioninfo        1.1.1      2018-11-05 [1] CRAN (R 3.6.1)                           
 stringi            1.4.6      2020-02-17 [1] CRAN (R 3.6.3)                           
 testthat           2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                           
 tibble             3.0.1      2020-04-20 [1] CRAN (R 3.6.3)                           
 tidyr              1.1.0      2020-05-20 [1] CRAN (R 3.6.3)                           
 tidyselect         1.1.0      2020-05-11 [1] CRAN (R 3.6.3)                           
 UpSetR             1.4.0      2019-05-22 [1] CRAN (R 3.6.1)                           
 usethis            1.6.1      2020-04-29 [1] CRAN (R 3.6.3)                           
 vctrs              0.3.0      2020-05-11 [1] CRAN (R 3.6.3)                           
 withr              2.2.0      2020-04-20 [1] CRAN (R 3.6.3)                           
 XVector            0.26.0     2019-10-29 [1] Bioconductor                             
 zlibbioc           1.32.0     2019-10-29 [1] Bioconductor                             

[1] /home/marcos/R/x86_64-pc-linux-gnu-library/3.6
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library

================================================

Thank you for your help in advance!
Kind regards,

Marcos

**Comment by thierrygosselin** [comment]
Could you try with the latest radiator push/release ?

**Comment by thierrygosselin** [comment]
The problem was SeqArray...

**Comment by marclagu** [comment]
Hi Thierry,
thank you for addressing this issue. Unfortunately I am still unable to process some vcf files that I successfully analized with radiator in the past. Now when I run the function tidy_vcf I get a new error:
##################################################
Number of duplicate id: 0
radiator Genomic Data Structure (GDS) file: radiator_20200624@1521.gds

Computation time, overall: 13 sec

Genotypes formats generated with 4825 SNPs: 
    GT_BIN (the dosage of ALT allele: 0, 1, 2 NA): TRUE
    GT_VCF (the genotype coding VCFs: 0/0, 0/1, 1/1, ./.): TRUE
    GT_VCF_NUC (the genotype coding in VCFs, but with nucleotides: A/C, ./.): TRUE
    GT (the genotype coding 'a la genepop': 001002, 001001, 000000): TRUE
Error: All columns in a tibble must be vectors.
x Column `HQ` is a `SeqVarDataList` object.
##################################################
When I check the "last error":
> rlang::last_error()
<error/tibble_error_column_scalar_type>
All columns in a tibble must be vectors.
x Column `HQ` is a `SeqVarDataList` object.
Backtrace:
  1. radiator::tidy_vcf("iceland.clean.HW.vcf", strata = "strata.iceland.clean.tsv")
  2. [ `%<>%`(...) ] with 7 more calls
 15. purrr::map(...)
 16. radiator:::.f(.x[[i]], ...)
 17. tibble::tibble(...)
 18. tibble:::tibble_quos(xs[!is_null], .rows, .name_repair)
 19. tibble:::check_valid_col(res, col_names[[j]], j)
 20. tibble:::check_valid_cols(set_names(list(x), name))
##################################################
When I check the last trace:
> rlang::last_trace
function () 
{
    err <- last_error()
    err$rlang$internal$print_simplify <- "none"
    err
}
<bytecode: 0x55c0d492d990>
<environment: namespace:rlang>
##################################################
Here is the session info:
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Atlantic/Reykjavik          
 date     2020-06-24                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────
 package          * version  date       lib source                                   
 assertthat         0.2.1    2019-03-21 [1] CRAN (R 4.0.1)                           
 backports          1.1.8    2020-06-17 [1] CRAN (R 4.0.1)                           
 Biobase            2.48.0   2020-04-27 [1] Bioconductor                             
 BiocGenerics       0.34.0   2020-04-27 [1] Bioconductor                             
 Biostrings         2.56.0   2020-04-27 [1] Bioconductor                             
 bitops             1.0-6    2013-08-17 [1] CRAN (R 4.0.1)                           
 broom              0.5.6    2020-04-20 [1] CRAN (R 4.0.1)                           
 callr              3.4.3    2020-03-28 [1] CRAN (R 4.0.1)                           
 cli                2.0.2    2020-02-28 [1] CRAN (R 4.0.1)                           
 colorspace         1.4-1    2019-03-18 [1] CRAN (R 4.0.1)                           
 crayon             1.3.4    2017-09-16 [1] CRAN (R 4.0.1)                           
 curl               4.3      2019-12-02 [1] CRAN (R 4.0.1)                           
 data.table         1.12.8   2019-12-09 [1] CRAN (R 4.0.1)                           
 desc               1.2.0    2018-05-01 [1] CRAN (R 4.0.1)                           
 devtools         * 2.3.0    2020-04-10 [1] CRAN (R 4.0.1)                           
 digest             0.6.25   2020-02-23 [1] CRAN (R 4.0.1)                           
 dplyr            * 1.0.0    2020-05-29 [1] CRAN (R 4.0.1)                           
 ellipsis           0.3.1    2020-05-15 [1] CRAN (R 4.0.1)                           
 fansi              0.4.1    2020-01-08 [1] CRAN (R 4.0.1)                           
 farver             2.0.3    2020-01-16 [1] CRAN (R 4.0.1)                           
 fs                 1.4.1    2020-04-04 [1] CRAN (R 4.0.1)                           
 gdsfmt             1.24.1   2020-06-16 [1] Bioconductor                             
 generics           0.0.2    2018-11-29 [1] CRAN (R 4.0.1)                           
 GenomeInfoDb       1.24.2   2020-06-15 [1] Bioconductor                             
 GenomeInfoDbData   1.2.3    2020-06-24 [1] Bioconductor                             
 GenomicRanges      1.40.0   2020-04-27 [1] Bioconductor                             
 ggplot2            3.3.2    2020-06-19 [1] CRAN (R 4.0.1)                           
 glue               1.4.1    2020-05-13 [1] CRAN (R 4.0.1)                           
 gridExtra          2.3      2017-09-09 [1] CRAN (R 4.0.1)                           
 gtable             0.3.0    2019-03-25 [1] CRAN (R 4.0.1)                           
 GWASExactHW        1.01     2013-01-05 [1] CRAN (R 4.0.1)                           
 hms                0.5.3    2020-01-08 [1] CRAN (R 4.0.1)                           
 IRanges            2.22.2   2020-05-21 [1] Bioconductor                             
 labeling           0.3      2014-08-23 [1] CRAN (R 4.0.1)                           
 lattice            0.20-41  2020-04-02 [4] CRAN (R 4.0.0)                           
 lifecycle          0.2.0    2020-03-06 [1] CRAN (R 4.0.1)                           
 logistf            1.23     2018-07-19 [1] CRAN (R 4.0.1)                           
 magrittr           1.5      2014-11-22 [1] CRAN (R 4.0.1)                           
 Matrix             1.2-18   2019-11-27 [4] CRAN (R 4.0.0)                           
 memoise            1.1.0    2017-04-21 [1] CRAN (R 4.0.1)                           
 mgcv               1.8-31   2019-11-09 [4] CRAN (R 4.0.0)                           
 mice               3.9.0    2020-05-14 [1] CRAN (R 4.0.1)                           
 munsell            0.5.0    2018-06-12 [1] CRAN (R 4.0.1)                           
 nlme               3.1-147  2020-04-13 [4] CRAN (R 4.0.0)                           
 pillar             1.4.4    2020-05-05 [1] CRAN (R 4.0.1)                           
 pkgbuild           1.0.8    2020-05-07 [1] CRAN (R 4.0.1)                           
 pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 4.0.1)                           
 pkgload            1.1.0    2020-05-29 [1] CRAN (R 4.0.1)                           
 plyr               1.8.6    2020-03-03 [1] CRAN (R 4.0.1)                           
 prettyunits        1.1.1    2020-01-24 [1] CRAN (R 4.0.1)                           
 processx           3.4.2    2020-02-09 [1] CRAN (R 4.0.1)                           
 ps                 1.3.3    2020-05-08 [1] CRAN (R 4.0.1)                           
 purrr              0.3.4    2020-04-17 [1] CRAN (R 4.0.1)                           
 R6                 2.4.1    2019-11-12 [1] CRAN (R 4.0.1)                           
 radiator         * 1.1.6    2020-06-24 [1] Github (thierrygosselin/radiator@2904196)
 Rcpp               1.0.4.6  2020-04-09 [1] CRAN (R 4.0.1)                           
 RCurl              1.98-1.2 2020-04-18 [1] CRAN (R 4.0.1)                           
 readr              1.3.1    2018-12-21 [1] CRAN (R 4.0.1)                           
 remotes            2.1.1    2020-02-15 [1] CRAN (R 4.0.1)                           
 rlang              0.4.6    2020-05-02 [1] CRAN (R 4.0.1)                           
 rprojroot          1.3-2    2018-01-03 [1] CRAN (R 4.0.1)                           
 rstudioapi         0.11     2020-02-07 [1] CRAN (R 4.0.1)                           
 S4Vectors          0.26.1   2020-05-16 [1] Bioconductor                             
 scales             1.1.1    2020-05-11 [1] CRAN (R 4.0.1)                           
 SeqArray           1.28.1   2020-06-16 [1] Bioconductor                             
 SeqVarTools        1.26.0   2020-04-27 [1] Bioconductor                             
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 4.0.1)                           
 stringi            1.4.6    2020-02-17 [1] CRAN (R 4.0.1)                           
 testthat           2.3.2    2020-03-02 [1] CRAN (R 4.0.1)                           
 tibble             3.0.1    2020-04-20 [1] CRAN (R 4.0.1)                           
 tidyr              1.1.0    2020-05-20 [1] CRAN (R 4.0.1)                           
 tidyselect         1.1.0    2020-05-11 [1] CRAN (R 4.0.1)                           
 UpSetR             1.4.0    2019-05-22 [1] CRAN (R 4.0.1)                           
 usethis          * 1.6.1    2020-04-29 [1] CRAN (R 4.0.1)                           
 vctrs              0.3.1    2020-06-05 [1] CRAN (R 4.0.1)                           
 withr              2.2.0    2020-04-20 [1] CRAN (R 4.0.1)                           
 XVector            0.28.0   2020-04-27 [1] Bioconductor                             
 zlibbioc           1.34.0   2020-04-27 [1] Bioconductor    

##################################################
Let me know if you want me to send you the file that I have been using. Thanks a lot!
Kind regards,
Marcos

**Comment by thierrygosselin** [comment]
Hi Marcos, could you send by email the required files that will allow me to reproduce the error you're having ?
I could have a look at it today

**Comment by marclagu** [comment]
Sure thing! Will do it right away. Thanks! :)

**Comment by thierrygosselin** [comment]
HQ is in the VCF header in stacks 2.41 but it's not an info available in the actual file, I think it's an error from stacks to output these things, and I mentioned this before in stacks google group. Now for some reasons, SeqArray, the engine under the hood for reading vcd in radiator, is now taking this too literally. Will fix this.

**Comment by marclagu** [comment]
Thank you very much for taking care of this! :)

**Comment by thierrygosselin** [comment]
Hi Marcos, could you try again, after reinstalling radiator latest release ...

**Comment by marclagu** [comment]
Now it works! Thanks a lot!
