### ISSUE TITLE
Error on opening some VCF files from STACS

### ISSUE THREAD

**Issue by zjons** [thierrygosselin/radiator#84]
We just ran into problems opening certain VCF files generated with stacks populations (v 2.41) most of the time the files open without problem but occationally (presumably depending on parameters) radiator throws an error.  This is an example of the error we get with the current github code:

Reading VCF...you might have time for a espresso...
Data summary: 
    number of samples: 211
    number of markers: 129238
done! timing: 6 sec

Generating individual stats...
Error: Tibble columns must have compatible sizes.
* Size 27269218: Existing data.
* Size 27269007: Column `ALLELE_ALT_DEPTH`.
ℹ Only values of size one are recycled.
Run `rlang::last_error()` to see where the error occurred.

Pior to upgrading radiatour the error message was sligtly different (which may be

 informative):

Reading VCF...you might have time for a espresso...
Data summary:
     number of samples: 211
     number of markers: 129238
done! timing: 6 sec

Generating individual stats...
Error: Tibble columns must have consistent lengths, only values of 
length one are recycled:
* Length 27269007: Column `ALLELE_ALT_DEPTH`
* Length 27269218: Column `ALLELE_REF_DEPTH`
Run `rlang::last_error()` to see where the error occurred.

--- Example files are to big for github.  I will have to send them by filelink

**Comment by thierrygosselin** [comment]
Could you try again, after reinstalling radiator latest release ...

**Comment by IoDeflem** [comment]
Hi, I get a similar error message when trying to open a vcf file generated with stacks. I used radiator a few months ago and I did not have this issue. I installed the latest version but that did not solve the problem. How did you manage to solve this?  

Reading a large VCF...you actually have time for coffee or tea!
Data summary: 
    number of samples: 287
    number of markers: 114819
done! timing: 13 sec

Generating individual stats...
Error: Tibble columns must have compatible sizes.
* Size 2: Column `READ_DEPTH`.
* Size 32953053: Columns `ALLELE_REF_DEPTH` and `ALLELE_ALT_DEPTH`.
ℹ Only values of size one are recycled.
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 43 sec

Computation time, overall: 47 sec

**Comment by thierrygosselin** [comment]
Could you follow guideline to submit an issue to make your problem reproducible please.

**Comment by BrennaF** [comment]
Thierry, I am having the same problem, using the data set I uploaded previously for the HW error. I've reattached it here.

**Call:**

dat <- filter_rad(data="ralu_subset.vcf",
                  strata="RALUstrata.txt",
                  interactive.filter=T, output="vcf",
                  parallel.core = parallel::detectCores() - 7)

**Results:**
################################################################################
############################# radiator::filter_rad #############################
################################################################################
The function arguments names have changed: please read documentation

Execution date@time: 20200826@1310
Function call and arguments stored in: radiator_filter_rad_args_20200826@1310.tsv
File written: random.seed (961993)
Filters parameters file generated: filters_parameters_20200826@1310.tsv

Reading VCF
Data summary: 
    number of samples: 360
    number of markers: 1000
done! timing: 1 sec

Generating individual stats...
[==================================================] 100%, completed, 0s
Error: Tibble columns must have compatible sizes.
* Size 2: Column `READ_DEPTH`.
* Size 360000: Columns `ALLELE_REF_DEPTH` and `ALLELE_ALT_DEPTH`.
i Only values of size one are recycled.
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 40 sec

Computation time, overall: 40 sec
############################# completed filter_rad #############################

**Session info:**
- Session info --------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2020-08-26                  

- Packages ------------------------------------------------------------------------------------------------------------
 package          * version  date       lib source                                   
 assertthat         0.2.1    2019-03-21 [1] CRAN (R 3.6.2)                           
 backports          1.1.7    2020-05-13 [1] CRAN (R 3.6.3)                           
 Biobase            2.46.0   2019-10-29 [1] Bioconductor                             
 BiocGenerics       0.32.0   2019-10-29 [1] Bioconductor                             
 BiocManager        1.30.10  2019-11-16 [1] CRAN (R 3.6.3)                           
 Biostrings         2.54.0   2019-10-29 [1] Bioconductor                             
 bitops             1.0-6    2013-08-17 [1] CRAN (R 3.6.0)                           
 broom              0.7.0    2020-07-09 [1] CRAN (R 3.6.3)                           
 callr              3.4.3    2020-03-28 [1] CRAN (R 3.6.3)                           
 cli                2.0.2    2020-02-28 [1] CRAN (R 3.6.3)                           
 colorspace         1.4-1    2019-03-18 [1] CRAN (R 3.6.1)                           
 crayon             1.3.4    2017-09-16 [1] CRAN (R 3.6.2)                           
 data.table         1.13.0   2020-07-24 [1] CRAN (R 3.6.3)                           
 desc               1.2.0    2018-05-01 [1] CRAN (R 3.6.2)                           
 devtools           2.3.1    2020-07-21 [1] CRAN (R 3.6.3)                           
 digest             0.6.25   2020-02-23 [1] CRAN (R 3.6.3)                           
 dplyr              1.0.2    2020-08-18 [1] CRAN (R 3.6.3)                           
 ellipsis           0.3.1    2020-05-15 [1] CRAN (R 3.6.3)                           
 fansi              0.4.1    2020-01-08 [1] CRAN (R 3.6.3)                           
 fs                 1.5.0    2020-07-31 [1] CRAN (R 3.6.3)                           
 gdsfmt             1.22.0   2019-10-29 [1] Bioconductor                             
 generics           0.0.2    2018-11-29 [1] CRAN (R 3.6.2)                           
 GenomeInfoDb       1.22.0   2019-10-29 [1] Bioconductor                             
 GenomeInfoDbData   1.2.2    2020-01-04 [1] Bioconductor                             
 GenomicRanges      1.38.0   2019-10-29 [1] Bioconductor                             
 ggplot2            3.3.2    2020-06-19 [1] CRAN (R 3.6.3)                           
 glue               1.4.1    2020-05-13 [1] CRAN (R 3.6.3)                           
 gridExtra          2.3      2017-09-09 [1] CRAN (R 3.6.2)                           
 gtable             0.3.0    2019-03-25 [1] CRAN (R 3.6.2)                           
 GWASExactHW        1.01     2013-01-05 [1] CRAN (R 3.6.0)                           
 HardyWeinberg      1.6.6    2020-08-13 [1] CRAN (R 3.6.3)                           
 hms                0.5.3    2020-01-08 [1] CRAN (R 3.6.3)                           
 IRanges            2.20.2   2020-01-13 [1] Bioconductor                             
 lattice            0.20-41  2020-04-02 [1] CRAN (R 3.6.3)                           
 lifecycle          0.2.0    2020-03-06 [1] CRAN (R 3.6.3)                           
 logistf            1.23     2018-07-19 [1] CRAN (R 3.6.2)                           
 magrittr           1.5      2014-11-22 [1] CRAN (R 3.6.2)                           
 Matrix             1.2-18   2019-11-27 [2] CRAN (R 3.6.3)                           
 memoise            1.1.0    2017-04-21 [1] CRAN (R 3.6.2)                           
 mgcv               1.8-31   2019-11-09 [2] CRAN (R 3.6.3)                           
 mice               3.11.0   2020-08-05 [1] CRAN (R 3.6.3)                           
 munsell            0.5.0    2018-06-12 [1] CRAN (R 3.6.2)                           
 nlme               3.1-144  2020-02-06 [2] CRAN (R 3.6.3)                           
 pillar             1.4.6    2020-07-10 [1] CRAN (R 3.6.3)                           
 pkgbuild           1.1.0    2020-07-13 [1] CRAN (R 3.6.3)                           
 pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 3.6.2)                           
 pkgload            1.1.0    2020-05-29 [1] CRAN (R 3.6.3)                           
 plyr               1.8.6    2020-03-03 [1] CRAN (R 3.6.3)                           
 prettyunits        1.1.1    2020-01-24 [1] CRAN (R 3.6.3)                           
 processx           3.4.3    2020-07-05 [1] CRAN (R 3.6.3)                           
 ps                 1.3.4    2020-08-11 [1] CRAN (R 3.6.3)                           
 purrr              0.3.4    2020-04-17 [1] CRAN (R 3.6.3)                           
 R6                 2.4.1    2019-11-12 [1] CRAN (R 3.6.2)                           
 radiator         * 1.1.7    2020-08-26 [1] Github (thierrygosselin/radiator@232317c)
 Rcpp               1.0.5    2020-07-06 [1] CRAN (R 3.6.3)                           
 RCurl              1.98-1.2 2020-04-18 [1] CRAN (R 3.6.3)                           
 readr              1.3.1    2018-12-21 [1] CRAN (R 3.6.2)                           
 remotes            2.2.0    2020-07-21 [1] CRAN (R 3.6.3)                           
 rlang              0.4.7    2020-07-09 [1] CRAN (R 3.6.3)                           
 rprojroot          1.3-2    2018-01-03 [1] CRAN (R 3.6.2)                           
 Rsolnp             1.16     2015-12-28 [1] CRAN (R 3.6.2)                           
 rstudioapi         0.11     2020-02-07 [1] CRAN (R 3.6.3)                           
 S4Vectors          0.24.4   2020-04-09 [1] Bioconductor                             
 scales             1.1.1    2020-05-11 [1] CRAN (R 3.6.3)                           
 SeqArray           1.26.2   2019-12-26 [1] Bioconductor                             
 SeqVarTools        1.24.1   2020-03-17 [1] Bioconductor                             
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 3.6.2)                           
 SNPRelate          1.20.1   2019-11-22 [1] Bioconductor                             
 stringi            1.4.6    2020-02-17 [1] CRAN (R 3.6.2)                           
 testthat           2.3.2    2020-03-02 [1] CRAN (R 3.6.3)                           
 tibble             3.0.3    2020-07-10 [1] CRAN (R 3.6.3)                           
 tidyr              1.1.1    2020-07-31 [1] CRAN (R 3.6.3)                           
 tidyselect         1.1.0    2020-05-11 [1] CRAN (R 3.6.3)                           
 truncnorm          1.0-8    2018-02-27 [1] CRAN (R 3.6.2)                           
 UpSetR             1.4.0    2019-05-22 [1] CRAN (R 3.6.2)                           
 usethis            1.6.1    2020-04-29 [1] CRAN (R 3.6.3)                           
 vctrs              0.3.2    2020-07-15 [1] CRAN (R 3.6.3)                           
 withr              2.2.0    2020-04-20 [1] CRAN (R 3.6.3)                           
 XVector            0.26.0   2019-10-29 [1] Bioconductor                             
 zlibbioc           1.32.0   2019-10-29 [1] Bioconductor                             

[1] C:/Users/brf8-admin/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.3/library


[RALUsubsetstrata.zip](https://github.com/thierrygosselin/radiator/files/5131329/RALUsubsetstrata.zip)

**Comment by thierrygosselin** [comment]
weird, will have a look right away

**Comment by thierrygosselin** [comment]
I think it's a problem with an old version of SeqArray...
But it's weird because in the DESCRIPTION file of radiator it's written `SeqArray (>= 1.28.1)` so it should update to the newer version when installing radiator...

```
BiocManager::install(pkgs = "SeqArray")
```

Then use a fresh session and test again:

```
test1 <- radiator::read_vcf(data = "ralu_subset.vcf", strata = "RALUstrata.txt")
```

This works fine on my end

**Comment by thierrygosselin** [comment]
make sure you re-start R (hence the fresh session) and check that you no longer have `SeqArray 1.26.2` from last December, but the newer version from June.

**Comment by BrennaF** [comment]
It will only install SeqArray 1.26.2, I'm guessing because I'm using R v. 3.6.3?  Does this mean I have to upgrade to 4.X? [Ugh.]

**Comment by thierrygosselin** [comment]
I don't think so, let me check

**Comment by zjons** [comment]
I am glad to see this issue reopened.  I am still having this problem with some datasets.  I have tried several versions of SeqArray.  Currently I have 1.29.1 installed.  This does not solve the problem.  Also, trying to open the same datasets saved as genepop files does not work either.

**Comment by thierrygosselin** [comment]
https://bioconductor.org/packages/release/bioc/html/SeqArray.html

Works with older R versions...

**Comment by thierrygosselin** [comment]
@zjons 
SeqArray as not much to do with genepop tidying, but does for GDS creation. email me the problematic genepop file, I'll have a look.

And send me the error you have if running this:

```
test1 <- radiator::tidy_genepop(data = "your_file.gen", strata = "your_strata.tsv")
```

**Comment by thierrygosselin** [comment]
[SeqArray GitHub page confirm that older version should work
](https://github.com/zhengxwen/SeqArray)

I'll try running the dev version (1.29.2)

**Comment by thierrygosselin** [comment]
@zjons I have no problem running SeqArray development version 1.29.2

**Comment by zjons** [comment]
That's why I suspect the problem may lie somewhere else.

**Comment by BrennaF** [comment]
Thank you Thierry - at least for my problem the SeqArray dev version fixed it (1.29.2). Note, I could not get Bioconductor to install v 1.28.1; it would only install 1.26.2.

**Comment by thierrygosselin** [comment]
SeqArray is always a bit tricky with VCF and those generated by stacks are always a bit problematic because stacks author keeps changing the way the markers metadata are handled... so I have a lot of `if ... else...` depending on stacks version. 

genepop files are another kind of problems because their is so much room for errors. I consider the format a legacy format. I'm not a big fan and it's not really a noce format to work with RADseq data. But I'll continue to support it, but not all it's different flavours.

**Comment by thierrygosselin** [comment]
ok so we know that the `READ_DEPTH ` problem associated with VCF are caused by prior version of SeqArray.

I'll find out why it's not installing automatically the latest bioconductor version, and if I don't find a solution, I'll just generate a check for package version inside the code that will stop and raised an error if it detects the old version...

Re-open the issue if still having this sort of problem...

**Comment by thierrygosselin** [comment]
This might be PC related, not sure
Brenna, if you have the time, test this:

```
remove.packages(c("SeqVarTools", "gdsfmt", "SeqArray", "radiator"))
```

re-install radiator
```
packages:devtools::install_github("thierrygosselin/radiator")
```

Check **SeqArray** version installed and other stuff by using this:

```
devtools::package_info(pkgs = "SeqArray")
```

Let me know what you get, bacause on my machines I'm getting the latest bioconductor version of SeqArray, so everything is as expected on my end.
