### ISSUE TITLE
New MARKERS Error

### ISSUE THREAD

**Issue by cbossu** [thierrygosselin/radiator#87]
Hello,
	Your solution worked to read in my data (updating SeqArray). However, a new error occurred when I was running the pairwise FST with confidence interval that I feel like leads back to the input data because the error relates to the MARKERS column. I checked the read in data, and it does have a MARKERS column, all with different names.

The command I ran was:

heth_str.fst.ci<-fst_WC84(dat,snprelate=F,strata=str,pairwise=TRUE,ci=TRUE,iteration.ci=100,verbose=TRUE,digits=2,pop.levels=c("AZ1","UT1","Yosemite","CA1","CA2","HaidaGwaii","AK2","PrinceRupert","Exstew","Kispiox","Whistler","Golden","Maxan","FortFraser","MacKenzie","Hudson'sHope","Swan","PA1","ME2"),filename="PairwiseFST",parallel.core=4)

And the error I received was:

Execution date/time: 20200703@1058
Folder created: PairwiseFST_fst_WC84_20200703@1058
Importing data
Analyzing strata file
    Number of strata: 19
    Number of individuals: 164
Global fst calculation
New names:
* MARKERS -> MARKERS...1
* MARKERS -> MARKERS...3
Error: Can't subset columns that don't exist.
x Column `MARKERS1` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning messages:
1: Unknown or uninitialised column: `MARKERS`.
2: Unknown or uninitialised column: `MARKERS1`.

It looks like the error occurs when trying to change the MARKERS names? In the tidied vcf file, my marker names look like :  scaf_16__1__83120 , scaf_16__2__162968, scaf_16__3__163043, etc.

Thanks,

Ch

**Comment by thierrygosselin** [comment]
Ok so that's a dplyr code and it's fix in the next assigner release. Give me 5 min...

**Comment by eriqande** [comment]
Hey Thierry!

I just wanted to say hello and thanks for all your hard work developing and
maintaining this package (especially in the face of all the breaking
changes that the new versions of dplyr have been introducing 😱), and
introduce you to Christen, or "C.H." as we call her, in case you might have
only met her through GitHub Issues. She works with Kristen on the bird
genoscape project.

I hope that you are doing well and staying safe in these weird times!

Best,

eric
