### ISSUE TITLE
Data infile vcf VS csv : error message setallcol and no variable created with filtered data

### ISSUE THREAD

**Issue by clrbtl** [thierrygosselin/radiator#88]
Hello Thierry,

I'm a french student doing an internship in population genetics at the moment and I encounter some issues that are currently preventing me from going further...
I'm on Windows 10.

In order to help me visualise the R script I have to write, I was given a similar script from a different species, and I wanted to run it to see what exactly was doing your "filter_rad" function. The script was perfectly functionning back in May on 3 different computers, but it doesn't :
 - I have a strata file which is (.csv) : 
![strata_example_species_csv](https://user-images.githubusercontent.com/68548871/87949861-daa74a80-caa6-11ea-8fda-f75493b89d93.png)

- and the SNP genotyped in a .csv file : 
![snp_genotyped_from_example_species_csv](https://user-images.githubusercontent.com/68548871/87949873-e09d2b80-caa6-11ea-90a5-17173d343ca9.png)

They used radiator this way in order to filter the data : 
```
example.all <- radiator::filter_rad(
  data = data, strata = strata,
  output = "tidy",
  interactive.filter = TRUE,parallel.core = 22)
```
The infiles data and strata where well imported, that is not the problem. The problem is that the script was working very well according to the researchers who worked on it and when I try to run it, it doesn't completely work, I have the following message : 
<img width="362" alt="problem_with_examplespecies" src="https://user-images.githubusercontent.com/68548871/87950289-64efae80-caa7-11ea-9796-393b33d177c2.png">

Folder created: filter_rad_20200720@1616
Function call and arguments stored in: radiator_filter_rad_args_20200720@1616.tsv
File written: random.seed (778224)
Filters parameters file generated: filters_parameters_20200720@1616.tsv
Reading DArT file...
Number of blacklisted samples: 0
DArT SNP format: genotypes in 1 Row
Generating genotypes and calibrating REF/ALT alleles...
Number of markers recalibrated based on counts of allele: 21687
**Error in setalloccol(ans) : can't set ALTREP truelength**

Now, as for the set of data I have to work on and filter through radiator, I don't have a .csv entry file but a .vcf (from RAD sequencing, the SNP genotyped also) and it is organised as follows : 
<img width="753" alt="raw_data_myspecies_snpgenotyped_vcf" src="https://user-images.githubusercontent.com/68548871/87949944-fad70980-caa6-11ea-9638-2ccbaf9e7aaa.png">

Now, I have my strata (.tsv) with 2 columns, one for the individuals and the other for their location site : 
<img width="170" alt="strata_myspecies" src="https://user-images.githubusercontent.com/68548871/87955277-c9ae0780-caad-11ea-996f-b2f9b2f870ce.png">

I did as mentionned in your website and following the output : 
```
data_filtered <- radiator::filter_rad(
    data = "data.vcf",
    strata = "strata.tsv",
    interactive.filter = TRUE,
    output = "tidy"
    )
```

And it worked, after some tedious issues to tackle : I can choose the threshold to filter my data, it's okay but at the end, when filter_rad is done, there is no "data_filtered" variable created as I asked the script, so at the moment, I don't know how to extract the data which has been filtered through filter_rad... 

So, if you could enlighten me as to why the first script doesn't work now (he also doesn't work anymore on the researchers' computer, and we have installed the newest versions of R (4.0), Rstudio, rtools and the packages have all been updated, and some have been correctly installed (not from the CRAN but from the github for dartR or vcfR for instance).
Also, if you could tell me why no variable "data_filtered" is created, or how to extract the data filtered after it has been run through your function, it would truly help me (because I can't do anything without the proper filtered data)!

Let me know if you need more information to help me on this case,

Thank you for your time and help!
Claire

**Comment by Victaphanta** [comment]
Hi, did you ever work out wy you were getting the error "Error in setalloccol(ans) : can't set ALTREP truelength", Thanks
