### ISSUE TITLE
Cannot convert to heirfstat

### ISSUE THREAD

**Issue by TharinduTS** [thierrygosselin/radiator#95]
Hi Thierry,
 I am trying to convert a VCF to heirfstat format. But it gives an error I cannot understand. Can you please tell me what is wrong here.

my code

library(devtools)
library(hierfstat)
library(assigner)

samples<-radiator::genomic_converter(
				       data ="./all_samples_varient_chrs_only_header_scaffolds_cleared.vcf",
				         strata = "./strata_L_and_G_3.tsv",
				         output = c(
						        "hierfstat" # for Hierfstat
							  )
				       ) %>% dplyr::glimpse()

when I run it gives me this. I have the same number of samples on my strata

Execution date@time: 20200917@2312
Folder created: -127_radiator_genomic_converter_20200917@2312
Function call and arguments stored in: radiator_genomic_converter_args_20200917@2312.tsv
Filters parameters file generated: filters_parameters_20200917@2312.tsv

Importing data

Reading a large VCF...you actually have time for coffee or tea!

Data summary: 
    number of samples: 46
    number of markers: 2376960
done! timing: 183 sec

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 934008 / 934008

Strata with low sample size detected: fig <- FALSE

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 1401310 / 1401310
Generating individual stats...
Error: Can't recycle `..1` (size 1915532) to match `..2` (size 0).
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 318 sec

Computation time, overall: 318 sec

Computation time, overall: 318 sec

Computation time, overall: 319 sec
######################### completed genomic_converter ##########################

**Comment by thierrygosselin** [comment]
You don't have to load ´devtools', ´hierfstat' and ´assigner'
To use ´radiator::genomic_converter'

**Comment by thierrygosselin** [comment]
Could you sent via email the vcf and strata files?

**Comment by TharinduTS** [comment]
Hey,
Thanks. The VCF is bit too large to be sent via email. I'll send you a link with all the files

**Comment by TharinduTS** [comment]
Hey Thierry,
 Thanks a lot for reaching out. Please have a look.
All the files are here.
https://mcmasteru365-my.sharepoint.com/:f:/g/personal/premacht_mcmaster_ca/Er7eFOUwbLVKrG-QoM_GGQQB1zNly5YD8k4WPE9lP6vOkQ?email=reply%2BANWKKRXNHCFOPNKFK3RYHDN5OAF7JEVBNHHCT5XWYM%40reply.github.com&e=phN7lx

**Comment by TharinduTS** [comment]
a { color: #0072bc; text-decoration: none; }






    
    
    
    
    Time of Access


  Time of Access v2
  
  
  

table td {border-collapse:collapse;margin:0;padding:0;}










 











 


 








 
 
 


 
Hello,


 
For security purposes, you must enter the code below to verify your account to access files_for_radiator. The code will only work for 15 minutes and if you request a new code, this code will stop working.


 




Account verification code:


01964071






 
Having problems with the code?


 
View the error and make sure that the email identifier is "0QG0TCC". If it's not, look for an updated email or try requesting a new code.








 


 

© 2017 Microsoft   Privacy & Cookies

**Comment by TharinduTS** [comment]
a { color: #0072bc; text-decoration: none; }






    
    
    
    
    Heure d’accès


  Time of Access v2
  
  
  

table td {border-collapse:collapse;margin:0;padding:0;}










 











 


 








 
 
 


 
Bonjour,


 
Pour des raisons de sécurité, vous devez entrer le code ci-dessous pour vérifier votre compte de manière à accéder à files_for_radiator. Le code ne fonctionne que pendant 15 minutes et, si vous demandez un nouveau code, ce code ne fonctionnera plus.


 




Code de vérification du compte :


26814704






 
Vous rencontrez des problèmes avec le code ?


 
Consultez l’erreur et vérifiez que l’identificateur de courrier est « 3YFYJCB ». Si ce n’est pas le cas, rechercher un courrier mis à jour ou essayez de demander un nouveau code.








 


 

© 2017 Microsoft   Confidentialité et cookies

**Comment by thierrygosselin** [comment]
Try via my email please
thierrygosselin@icloud.com

I'll have a look at it in a few hours

**Comment by TharinduTS** [comment]
Thanks

**Comment by TharinduTS** [comment]
a { color: #0072bc; text-decoration: none; }






    
    
    
    
    Time of Access


  Time of Access v2
  
  
  

table td {border-collapse:collapse;margin:0;padding:0;}










 











 


 








 
 
 


 
Hello,


 
For security purposes, you must enter the code below to verify your account to access files_for_radiator. The code will only work for 15 minutes and if you request a new code, this code will stop working.


 




Account verification code:


72177504






 
Having problems with the code?


 
View the error and make sure that the email identifier is "Q6ZCZ2B". If it's not, look for an updated email or try requesting a new code.








 


 

© 2017 Microsoft   Privacy & Cookies

**Comment by thierrygosselin** [comment]
Dear Tharindu, 
I'm currently looking at the problem you're encountering. I'm able to reproduce the bug, good thing!

Question: what's the source of your VCF ?

Just a side note, the 2 strata files in the folder: `strata_L_and_G.tsv` and `strata_L_and_G_3.tsv` have a space character at the beginning of the id. It's taken care of in radiator, but other programs might have problem with this. Be careful.

**Comment by thierrygosselin** [comment]
VCF source : samtools ? via another RADseq pipeline ?

**Comment by thierrygosselin** [comment]
I have just updated GitHub, radiator should be able to read your VCF.

The strata: `strata_L_and_G.tsv` you provided as 15 strata for 46 individuals and several groups only have 1 sample. I would regroup those samples before using hierfstat.

*Test1*
```
test1 <- radiator::read_vcf(
    data = "all_samples_varient_chrs_only_header_scaffolds_cleared.vcf", 
    strata = "strata_L_and_G.tsv",
    filter.common.markers = FALSE, 
    filter.monomorphic = FALSE)
```

*test2*

```
test2 <- radiator::genomic_converter(
  data = "all_samples_varient_chrs_only_header_scaffolds_cleared.vcf", 
  strata = "strata_L_and_G.tsv", 
  output = "hierfstat"
  )
```

Re-open the issue if you're still experiencing a problem
Best,
Thierry

**Comment by TharinduTS** [comment]
Hi Thierry,
 Thanks for the reply. But it seems like I am getting the same error message. Can you please clarify the following?
 1) I just updated assigner using install_github("thierrygosselin/assigner”) and then tried your code
 2) Is having more than one sample per population is a must for the radiator to work?

Thanks,
Tharindu

**Comment by thierrygosselin** [comment]
Assigner package as nothing to do with this issue

Please reinstall radiator and re-start R.

**Comment by TharinduTS** [comment]
Okay. Thanks again.

**Comment by TharinduTS** [comment]
Sorry about the confusion. I have sent you the wrong code
