### ISSUE TITLE
Error: Problem with `mutate()` input `MISSING_PROP`.

### ISSUE THREAD

**Issue by fraser-combe** [thierrygosselin/radiator#97]
I keep getting the following error when trying to import a vcf file directly from stacks output, hopefully, you can help:

Generating individual stats...
Error: Problem with `mutate()` input `MISSING_PROP`.
x One of the nodes produced an error: Can not open file 'C:\Users\frasc\Dropbox\My PC (DESKTOP-4P6AFFC)\Documents\filter_rad_20201007@1646\01_radiator\radiator_20201007@1646.gds'. The process cannot access the file because it is being used by another process.

i Input `MISSING_PROP` is `round(...)`.
Run `rlang::last_error()` to see where the error occurred.

My input is:
 data <- radiator::filter_rad(data = "populations.snps.vcf", strata = "strata.filtered.tsv")

output:
################################################################################
################################################################################
Execution date@time: 20201007@1646
Folder created: filter_rad_20201007@1646
Function call and arguments stored in: radiator_filter_rad_args_20201007@1646.tsv
File written: random.seed (214838)
Filters parameters file generated: filters_parameters_20201007@1646.tsv

Reading VCF
Data summary: 
    number of samples: 94
    number of markers: 18041
done! timing: 9 sec

Generating individual stats...
Error: Problem with `mutate()` input `MISSING_PROP`.
x One of the nodes produced an error: Can not open file 'C:\Users\frasc\Dropbox\My PC (DESKTOP-4P6AFFC)\Documents\filter_rad_20201007@1646\01_radiator\radiator_20201007@1646.gds'. The process cannot access the file because it is being used by another process.

i Input `MISSING_PROP` is `round(...)`.
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 18 sec

Computation time, overall: 18 sec
############################# completed filter_rad #############################

I have also tried read_vcf simply :
 data <- radiator::read_vcf(data = "populations.snps.vcf")
Execution date@time: 20201007@1650
Folder created: read_vcf_20201007@1650
Function call and arguments stored in: radiator_read_vcf_args_20201007@1650.tsv
File written: random.seed (609688)

Reading VCF
Data summary: 
    number of samples: 94
    number of markers: 18041
done! timing: 7 sec

GDS file written: radiator_20201007@1650.gds

Analyzing the vcf...
VCF source: Stacks v2.53
Data is bi-allelic
Cleaning VCF's sample names
File written: cleaned.vcf.id.info_20201007@1650.tsv
Error in if (locus.missing) ref.genome <- FALSE : 
  argument is of length zero

Computation time, overall: 8 sec

VCF file header
##fileformat=VCFv4.2
##fileDate=20200915
##source="Stacks v2.53"
##INFO=<ID=AD,Number=R,Type=Integer,Description="Total Depth for Each Allele">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allele Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=loc_strand,Number=1,Type=Character,Description="Genomic strand the corresponding Stacks locus aligns on">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	MDNF021_R1	MDNF023_R1	MDNF029_R1	MDNF031_R1	NW_018326927.1	76729	8:27:-	A	G	.	PASS	NS=94;AF=0.011

**Comment by thierrygosselin** [comment]
radiator should have no problem reading stacks VCF, sorry about that.

Try this:

```
test1 <- radiator::read_vcf(data = "populations.snps.vcf", strata = "strata.filtered.tsv")
```
If the command above generate the same error you get when running `radiator::filter_rad`, try the next one:
```
test2 <- radiator::read_vcf(data = "populations.snps.vcf", strata = "strata.filtered.tsv", parallel.core = 1L)
```

**Comment by thierrygosselin** [comment]
I think it's similar to this issue #44 
PC and parallel computing problem, setting `parallel.core = 1L` should fix it. 

I have no idea why some PC works and others don't.

**Comment by fraser-combe** [comment]
Excellent thank you so much for a quick reply and an excellent package, this has solved the problem running

test2 <- radiator::read_vcf(data = "populations.snps.vcf", strata = "strata.filtered.tsv", parallel.core = 1L)

I had been searching through the issues pages but had missed the parallel sentence.

**Comment by thierrygosselin** [comment]
perfect, feel free to re-open the issue if you're still experiencing problem reading the file or filtering.
