### ISSUE TITLE
write_colony: could not find function "%>%"

### ISSUE THREAD

**Issue by rh565** [thierrygosselin/radiator#98]
Hi,

I am having some trouble with the write_colony function. When running:

data <- radiator::read_vcf(data = "populations.snps.vcf", parallel.core = 1L)
colony_file <- radiator::write_colony(data = data)

I get the error message:

Importing data...
Calibrating REF/ALT alleles...
Error in dplyr::select(x, -SPLIT_VEC) %>% dplyr::mutate(GT_VCF_NUC = dplyr::if_else(GT_BIN ==  : 
  could not find function "%>%"

I thought this might be a problem with my installation of dplyr or magrittr, but I have just updated R (now running R 4.0.3), RStudio (v1.3.1093) and re-installed all packages. %>% works with no problem in my own code.

- Session info ---------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 ctype    English_United Kingdom.1252 
 tz       Europe/London               
 date     2020-10-19                  

- Packages -------------------------------------------------------------------
 package          * version  date       lib
 assertthat         0.2.1    2019-03-21 [1]
 backports          1.1.10   2020-09-15 [1]
 Biobase            2.48.0   2020-04-27 [1]
 BiocGenerics       0.34.0   2020-04-27 [1]
 BiocManager        1.30.10  2019-11-16 [1]
 Biostrings         2.56.0   2020-04-27 [1]
 bitops             1.0-6    2013-08-17 [1]
 broom              0.7.1    2020-10-02 [1]
 callr              3.5.1    2020-10-13 [1]
 carrier            0.1.0    2018-10-16 [1]
 cli                2.1.0    2020-10-12 [1]
 codetools          0.2-16   2018-12-24 [1]
 colorspace         1.4-1    2019-03-18 [1]
 crayon             1.3.4    2017-09-16 [1]
 data.table         1.13.0   2020-07-24 [1]
 desc               1.2.0    2018-05-01 [1]
 devtools           2.3.2    2020-09-18 [1]
 digest             0.6.25   2020-02-23 [1]
 dplyr            * 1.0.2    2020-08-18 [1]
 ellipsis           0.3.1    2020-05-15 [1]
 fansi              0.4.1    2020-01-08 [1]
 farver             2.0.3    2020-01-16 [1]
 formula.tools      1.7.1    2018-03-01 [1]
 fs                 1.5.0    2020-07-31 [1]
 furrr              0.2.0    2020-10-12 [1]
 future           * 1.19.1   2020-09-22 [1]
 gdsfmt             1.24.1   2020-06-16 [1]
 generics           0.0.2    2018-11-29 [1]
 GenomeInfoDb       1.24.2   2020-06-15 [1]
 GenomeInfoDbData   1.2.3    2020-10-19 [1]
 GenomicRanges      1.40.0   2020-04-27 [1]
 ggplot2            3.3.2    2020-06-19 [1]
 globals            0.13.1   2020-10-11 [1]
 glue               1.4.2    2020-08-27 [1]
 gridExtra          2.3      2017-09-09 [1]
 gtable             0.3.0    2019-03-25 [1]
 GWASExactHW        1.01     2013-01-05 [1]
 hms                0.5.3    2020-01-08 [1]
 IRanges            2.22.2   2020-05-21 [1]
 labeling           0.3      2014-08-23 [1]
 lattice            0.20-41  2020-04-02 [1]
 lifecycle          0.2.0    2020-03-06 [1]
 listenv            0.8.0    2019-12-05 [1]
 logistf            1.24     2020-09-16 [1]
 magrittr         * 1.5      2014-11-22 [1]
 Matrix             1.2-18   2019-11-27 [1]
 memoise            1.1.0    2017-04-21 [1]
 mgcv               1.8-33   2020-08-27 [1]
 mice               3.11.0   2020-08-05 [1]
 munsell            0.5.0    2018-06-12 [1]
 nlme               3.1-149  2020-08-23 [1]
 operator.tools     1.6.3    2017-02-28 [1]
 pillar             1.4.6    2020-07-10 [1]
 pkgbuild           1.1.0    2020-07-13 [1]
 pkgconfig          2.0.3    2019-09-22 [1]
 pkgload            1.1.0    2020-05-29 [1]
 plyr               1.8.6    2020-03-03 [1]
 prettyunits        1.1.1    2020-01-24 [1]
 processx           3.4.4    2020-09-03 [1]
 ps                 1.4.0    2020-10-07 [1]
 purrr              0.3.4    2020-04-17 [1]
 R6                 2.4.1    2019-11-12 [1]
 radiator         * 1.1.8    2020-10-19 [1]
 Rcpp               1.0.5    2020-07-06 [1]
 RCurl              1.98-1.2 2020-04-18 [1]
 readr              1.4.0    2020-10-05 [1]
 remotes          * 2.2.0    2020-07-21 [1]
 rlang              0.4.8    2020-10-08 [1]
 rprojroot          1.3-2    2018-01-03 [1]
 rstudioapi         0.11     2020-02-07 [1]
 S4Vectors          0.26.1   2020-05-16 [1]
 scales             1.1.1    2020-05-11 [1]
 SeqArray           1.28.1   2020-06-16 [1]
 SeqVarTools        1.26.0   2020-04-27 [1]
 sessioninfo        1.1.1    2018-11-05 [1]
 stringi            1.5.3    2020-09-09 [1]
 testthat           2.3.2    2020-03-02 [1]
 tibble             3.0.4    2020-10-12 [1]
 tidyr              1.1.2    2020-08-27 [1]
 tidyselect         1.1.0    2020-05-11 [1]
 UpSetR             1.4.0    2019-05-22 [1]
 usethis            1.6.3    2020-09-17 [1]
 vctrs              0.3.4    2020-08-29 [1]
 withr              2.3.0    2020-09-22 [1]
 XVector            0.28.0   2020-04-27 [1]
 zlibbioc           1.34.0   2020-04-27 [1]
 source                                   
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 Bioconductor                             
 Bioconductor                             
 CRAN (R 4.0.3)                           
 Bioconductor                             
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.2)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.2)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 Bioconductor                             
 CRAN (R 4.0.3)                           
 Bioconductor                             
 Bioconductor                             
 Bioconductor                             
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 Bioconductor                             
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.2)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 Github (thierrygosselin/radiator@981a259)
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 Bioconductor                             
 CRAN (R 4.0.3)                           
 Bioconductor                             
 Bioconductor                             
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 CRAN (R 4.0.3)                           
 Bioconductor                             
 Bioconductor                             

[1] F:/R-4.0.3/library

**Comment by thierrygosselin** [comment]
Hi, sorry about the problem you're experiencing. I don't think the problem is on your side...
Over the week end I've been upgrading the codes to work better with Windows and the parallel mode.
I've switched to `future` package for parallelization and `carrier` to contains globals. Anyway, short story,
it's not you.

Do you mind sending the data (by email) so that I can try to replicate the problem on my Mac ?

Best
Thierry

**Comment by rh565** [comment]
Hi - thanks for your fast response. Will do!
Beki

**Comment by thierrygosselin** [comment]
Should work without problems now
Remove and install radiator
Re-open the issue if you're still experiencing problems
