### ISSUE TITLE
genomic_convertor() data types

### ISSUE THREAD

**Issue by mariaemilyd** [thierrygosselin/radiator#99]
Hi Thierry,

Thanks for making this great package. I came across it because I was looking to see if someone had made one R function to convert between the multitude of different pop genetics data formats, and genomic_convertor() does that! but I know this package is for RADseq data. At the moment I'm working with lowly microsatellites (although will have RADseq data in the future for another project). I just wanted to check whether genomic_convertor() only works with RADseq data?

Thanks,

Maria

**Comment by thierrygosselin** [comment]
Hi Maria, it should work with microsat, lately I've been doing some changes, so keep an eye on conversion and report back issues if you find any.

Best
Thierry

**Comment by mariaemilyd** [comment]
Thanks Thierry, that's good to hear. I will try it out and let you know if there are issues.
